tam_data_mapping = {"Adani Electricity Mumbai Limited": "Adani Electricity Mumbai Limited",
                    "Andhra Pradesh Central Power Distribution Corp Ltd": "Andhra Pradesh Central Power Distribution Corporation Limited",
                    "Andhra Pradesh Central Power Distribution Corp.ltd": "Andhra Pradesh Central Power Distribution Corporation Limited",
                    "APDCL (Assam)": "ASSAM POWER DISTRIBUTION COMPANY LIMITED",
                    "ArcelorMittal Nippon Steel India Limited": "ArcelorMittal Nippon Steel India Limited",
                    "Bharat Aluminium Company Limited": "BHARAT ALUMINIUM COMPANY LTD",
                    "Bharat Aluminum Company ltd (Bulk consumer)": "BHARAT ALUMINIUM COMPANY LTD (Bulk Consumer)",
                    "BHARAT ALUMINIUM COMPANY LTD (Bulk Consumer)": "BHARAT ALUMINIUM COMPANY LTD (Bulk Consumer)",
                    "Bihar State Power Holding Company Ltd Patna": "Bihar State Power (Holding) Company Limited",
                    "Bihar State Power Holding Company Limited": "Bihar State Power (Holding) Company Limited",
                    "Bihar State Power Holding Company": "Bihar State Power (Holding) Company Limited",
                    "BSES Yamuna Power Limited (BYPL)": "BSES Yamuna Power Limited",
                    "C.S.P.DISTRIBUTION_CO._LTD.": "CHHATTISGARH STATE POWER DISTRIBUTION COMPANY LIMITED",
                    "Central Railways_Maharashtra": "Central Railway",  # "Central Railway": "Central Railway",
                    "CESC": "CESC LIMITED", "CESC Limited": "CESC LIMITED",
                    "CSP Distribution  Company ltd": "CHHATTISGARH STATE POWER DISTRIBUTION COMPANY LIMITED",
                    "CSP Distribution Co Ltd": "CHHATTISGARH STATE POWER DISTRIBUTION COMPANY LIMITED",
                    "Dadra and Nagar Haveli and Daman and Diu Power Distribution Corporation Limited": "Dadra and Nagar Haveli and Daman and Diu Power Distribution Corporation Lim",
                    "DNH Power Distribution Corporation Ltd": "DNH Beneficiary",  # "DVC": "DVC",
                    "Electricity Department_Government of Goa WR": "Electricity Department, GOA_WR",
                    "Gift Power Company Ltd": "GIFT Power Company Limited",
                    "Gigaplex Estate Private Limited": "GIGAPLEX ESTATE PRIVATE LIMITED",
                    "Gigaplex Estate pvt ltd": "GIGAPLEX ESTATE PRIVATE LIMITED", "GRIDCO": "GRIDCO LIMITED",
                    # "GRIDCO LIMITED": "GRIDCO LIMITED",
                    "GUJARAT URJA VIKAS NIGAM LTD": "GUJARAT URJA VIKAS NIGAM LIMITED",
                    "GUVNL": "GUJARAT URJA VIKAS NIGAM LIMITED",
                    "Gujarat Urja Vikas Nigam Limited": "GUJARAT URJA VIKAS NIGAM LIMITED",
                    "Himachal Pradesh State Electricity Board Ltd": "HIMACHAL PRADESH STATE ELECTRICITY BOARD LIMITED",
                    "HPSEB": "HIMACHAL PRADESH STATE ELECTRICITY BOARD LIMITED",
                    "Kerala State Electricity Board (KSEB)": "KERALA STATE ELECTRICITY BOARD LIMITED",
                    "Kerala State Electricity Board Limited": "KERALA STATE ELECTRICITY BOARD  LIMITED",
                    "KRC Infrastructure and Projects Pvt Ltd": "KRC INFRASTRUCTURE AND PROJECTS PRIVATE LIMITED",
                    "KRC Infrastructure & Project Pvt Ltd": "KRC INFRASTRUCTURE AND PROJECTS PRIVATE LIMITED",
                    "Maharashtra State Electricity Distribution Company Limited (MSEDCL)": "Maharashtra State Electricity Distribution Co Limited",
                    "MSEDCL": "Maharashtra State Electricity Distribution Co Limited",
                    "Mind Space business Park pvt ltd": "MINDSPACE BUSINESS PARKS PRIVATE LIMITED",
                    "Mindspace Business Parks Pvt Ltd": "MINDSPACE BUSINESS PARKS PRIVATE LIMITED",
                    "Mindspace Business Parks Private Limited": "MINDSPACE BUSINESS PARKS PRIVATE LIMITED",
                    'New Delhi Municipal Council': "New Delhi Municipal Council",
                    "New_Delhi_Municipal council_NDMC": "New Delhi Municipal Council",
                    "Noida Power Company Limited": "Noida Power Company limited",
                    "Noida power Company ltd": "Noida Power Company limited",
                    "Noida Power Company.Ltd": "Noida Power Company limited", "NPCL": "Noida Power Company limited",
                    "North Western Railway": "North Western Railway", "Northern  Railway  UP": "Northern Railway UP",
                    "Northern  Railway UP": "Northern Railway UP", "Northern Railway UP": "Northern Railway UP",
                    "NORTHERN RAILWAY UP": "Northern Railway UP", "Northern Railway": "Northern Railway",
                    "Northern Railway Haryana": "Northern Railway-Haryana",
                    "Power Company of Karnataka Limited -PCKL": "Power Company of Karnataka Ltd",
                    "PCKL": "Power Company of Karnataka Ltd",
                    # "Power Company of Karnataka Ltd": "Power Company of Karnataka Ltd",
                    "Punjab State Power Corporation Ltd (PTC)": "Punjab State Power Corporation Limited",
                    "Rajasthan Urja Vikas Nigam Ltd (RUVNL)": "RAJASTHAN URJA VIKAS NIGAM LIMITED",
                    "Rajasthan Urja Vikas Nigam Ltd": "RAJASTHAN URJA VIKAS NIGAM LIMITED",
                    "Rajasthan Urja Vikas Nigam .ltd": "RAJASTHAN URJA VIKAS NIGAM LIMITED",
                    "Rajasthan Urja Vikas Nigam Limited": "RAJASTHAN URJA VIKAS NIGAM LIMITED",
                    "RUVNL": "RAJASTHAN URJA VIKAS NIGAM LIMITED", "South Western Railway": "South Western Railway",
                    "South  Western  Railway": "South Western Railway",
                    "South  Western Railway": "South Western Railway",
                    "Southern Power Distribution Company of Telangana Limited": "SOUTHERN POWER DISTRIBUTION COMPANY OF TELANGANA LIMITED",
                    "Southern Power Distribution Company of Telangana Limited (TSSPDCL)": "SOUTHERN POWER DISTRIBUTION COMPANY OF TELANGANA LIMITED",
                    "Tamilnadu Generation and Distribution Corporation Limited": "TAMILNADU GENERATION AND DISTRIBUTION CORPORATION LIMITED",
                    "Tamil Nadu  Generation and Distribution Corporation Limited": "TAMILNADU GENERATION AND DISTRIBUTION CORPORATION LIMITED",
                    "Tamilnadu Generation and Dist. Corp. Ltd TANGEDCO": "TAMILNADU GENERATION AND DISTRIBUTION CORPORATION LIMITED",
                    "TANGEDCO": "TAMILNADU GENERATION AND DISTRIBUTION CORPORATION LIMITED",
                    # "Torrent Power Ahmedabad": "Torrent Power Ahmedabad",
                    "TORRENT POWER LIMITED - AHMEDABAD DISTRIBUTION": "Torrent Power Ahmedabad",
                    "Torrent Power Limited - Dahej Distribution": "Torrent Power Limited - Dahej",
                    "TORRENT POWER LIMITED - SURAT DISTRIBUTION": "Torrent Power Surat",
                    "Torrent Power Ltd Surat": "Torrent Power Surat",
                    "Torrent Power Limited- Dahej": "Torrent Power Limited - Dahej",
                    "Torrent Power Ltd Dahej": "Torrent Power Limited - Dahej",
                    # "Torrent Power Surat": "Torrent Power Surat",
                    "U P Power Corporation Ltd": "UPPCL", "Uttar Pradesh Power Corporation Ltd (UPPCL)": "UPPCL",
                    "Uttar Pradesh Power Corporation Ltd": "UPPCL",
                    "Uttar Pradesh Power Corporation Limited (UPPCL)": "UPPCL",
                    "Uttarakhand Power Corporation Limited": "UTTARAKHAND POWER CORPORATION LIMITED",
                    "Uttarakhand Power Corporation": "UTTARAKHAND POWER CORPORATION LIMITED",
                    "Uttrakhand Power Corp Ltd": "UTTARAKHAND POWER CORPORATION LIMITED",
                    "Uttrakhand Power Corp.Ltd": "UTTARAKHAND POWER CORPORATION LIMITED",
                    "Vedanta Ltd_SEZ Unit_Jharsuguda": "Vedanta Limited SEZ UNIT, Jharsuguda",
                    "West Bengal State Electricity Distribution Company Limited (WBSEDCL)": "WEST BENGAL STATE ELECTRICITY DISTRIBUTION COMPANY LIMITED",
                    "West Central Railway": "WEST CENTRAL RAILWAY",

                    "Uttarakhand Power Corporation Ltd": "UTTARAKHAND POWER CORPORATION LIMITED",
                    # "Uttarakhand Power Corporation Limited (UPCL)": "UTTARAKHAND POWER CORPORATION LIMITED",
                    "TPL-Ahmedabad Discom": "TPL-Ahmedabad Discom", }

deep_data_mapping = {"JBVNL": "JHARKHAND BIJLI VITRAN NIGAM LIMITED",
                     "CSPDL": "CHHATTISGARH STATE POWER DISTRIBUTION COMPANY LIMITED",
                     "NUPLLP": "NIDAR UTILITIES PANVEL LLP",  # "REMCL": "Railway Energy Management Company Limited",
                     "LBSCML": "LAXMIPATI BALAJI SUPPLY CHAIN MANAGEMENT LIMITED",
                     "RUVNL": "RAJASTHAN URJA VIKAS NIGAM LIMITED", "BSES": "BSES Rajdhani Power Limited",
                     "BYPL": "BSES Yamuna Power Limited", "IPCL": "India Power Corporation Limited",
                     "APPCC": "Andhra Pradesh Power Coordination Committee",
                     "GUVNL": "Gujarat Urja Vikas Nigam Limited", "MSEZL": "Mangalore SEZ Limited",
                     "APDCL": "ASSAM POWER DISTRIBUTION COMPANY LIMITED",
                     # "MPPMCL": "Madhya Pradesh Power Management Company Limited",
                     "PCKL": "Power Company of Karnataka Ltd", "PSPCL": "Punjab State Power Corporation Limited",
                     "EON KHARADI INFRASTRUCTURE PVT LTD": "EON KHARADI INFRASTRUCTURE PRIVATE LIMITED, Phase -2",
                     # "SEZ BIOTECH SERVICES PRIVATE LIMITED": "RAIPUR ENERGEN LIMITED",
                     # "PFC Consulting Limited": "LAXMIPATI BALAJI SUPPLY CHAIN MANAGEMENT LIMITED",
                     # "Sundew Properties Limited": "LAXMIPATI BALAJI SUPPLY CHAIN MANAGEMENT LIMITED",
                     "TAMILNADU ELECTRICITY BOARD": "Tamil Nadu Electricity Board",
                     "Andhra Pradesh Power Co-Ordination Committee (APPCC)": "Andhra Pradesh Power Coordination Committee",
                     "TANGEDCO ltd": "TAMILNADU GENERATION AND DISTRIBUTION CORPORATION LIMITED",
                     # "MADC LTD": "Maharashtra Airport Development Company Limited",
                     # "RELIANCE ENERGY MUMBAI DISCOM": "TPL-Surat Discom",
                     "UPCL": "UTTARAKHAND POWER CORPORATION LIMITED", "KSEBL": "KSEB",
                     "MAHARASHTRA STATE ELECTRICITY CO LTD": "Maharashtra State Electricity Distribution Co Limited",
                     "CESC": "CESC LIMITED",
                     "HARYANA POWER PURCHASE CENTRE(A JOINT FORUM OF UHBVN&DHBVN)": "Haryana Power Purchase Centre",
                     # "AEML": "AEML SEEPZ Limited",
                     # "TPCL": "TPCL_U7 RLNG / The Tata Power Co Ltd (MTPS)",
                     "TAMILNADU GENERATION AND DISTRIBUTION CORPN LTD": "TAMILNADU GENERATION AND DISTRIBUTION CORPORATION LIMITED",
                     "HPSEBL": "HIMACHAL PRADESH STATE ELECTRICITY BOARD LIMITED", "BEST": "BEST Undertaking",
                     "Chandigarh Electricity Department": "CHANDIGARH",
                     "KRC Infrastructure and Projects Pvt Ltd": "KRC INFRASTRUCTURE AND PROJECTS PRIVATE LIMITED",
                     "MP Power Management Company Ltd": "M.P. POWER MANAGEMENT COMPANY LIMITED",
                     "Assam Power Distribution Company Ltd": "ASSAM POWER DISTRIBUTION COMPANY LIMITED",
                     "Torrent Power Limited": "Torrent Power Limited - Dahej",
                     "MPSEZ Utilities Private Limited": "MPSEZ Utilities Limited",
                     "SOUTHERN POWER DISTRIBUTION COMPANY OF TELANGANA LTD": "SOUTHERN POWER DISTRIBUTION COMPANY OF TELANGANA LIMITED",
                     "WEST BENGAL STATE ELECTRICITY DISTRIBUTION COMPANY LIMITED": "WEST BENGAL STATE ELECTRICITY DISTRIBUTION COMPANY LIMITED",
                     "Noida Power Company Limited": "Noida Power Company limited",
                     "JAWAHARLAL NEHRU PORT TRUST": "Jawaharlal Nehru Port Trust",
                     "GUJARAT URJA VIKAS NIGAM LIMITED": "GUJARAT URJA VIKAS NIGAM LIMITED",
                     "TATA POWER DELHI DISTRIBUTION LIMITED": "Tata Power Delhi Distribution Limited",
                     "MINDSPACE BUSINESS PARKS PRIVATE LIMITED": "MINDSPACE BUSINESS PARKS PRIVATE LIMITED",
                     "BSPHCL": "BSPHCL", "NIDP DEVELOPERS PRIVATE LIMITED": "NIDP DEVELOPERS PRIVATE LIMITED",
                     "GRIDCO LIMITED": "GRIDCO LIMITED",
                     "Gigaplex Estate Private Limited": "GIGAPLEX ESTATE PRIVATE LIMITED",
                     'Andhra Pradesh Power Co-Ordination Committee (Andhra Pradesh Power Coordination Committee)': 'Andhra Pradesh Power Coordination Committee'}

deep_tam_mapping = {"Adani Electricity Mumbai Limited": "Adani Electricity Mumbai Limited",
                    "Andhra Pradesh Central Power Distribution Corp Ltd": "Andhra Pradesh Central Power Distribution Corporation Limited",
                    "Andhra Pradesh Central Power Distribution Corp.ltd": "Andhra Pradesh Central Power Distribution Corporation Limited",
                    "APDCL (Assam)": "ASSAM POWER DISTRIBUTION COMPANY LIMITED",
                    "ArcelorMittal Nippon Steel India Limited": "ArcelorMittal Nippon Steel India Limited",
                    "Bharat Aluminium Company Limited": "BHARAT ALUMINIUM COMPANY LTD",
                    "Bharat Aluminum Company ltd (Bulk consumer)": "BHARAT ALUMINIUM COMPANY LTD (Bulk Consumer)",
                    "BHARAT ALUMINIUM COMPANY LTD (Bulk Consumer)": "BHARAT ALUMINIUM COMPANY LTD (Bulk Consumer)",
                    "Bihar State Power Holding Company Ltd Patna": "Bihar State Power (Holding) Company Limited",
                    "Bihar State Power Holding Company Limited": "Bihar State Power (Holding) Company Limited",
                    "Bihar State Power Holding Company": "Bihar State Power (Holding) Company Limited",
                    "BSES Yamuna Power Limited (BYPL)": "BSES Yamuna Power Limited",
                    "C.S.P.DISTRIBUTION_CO._LTD.": "CHHATTISGARH STATE POWER DISTRIBUTION COMPANY LIMITED",
                    "Central Railways_Maharashtra": "Central Railway",  # "Central Railway": "Central Railway",
                    "CESC": "CESC LIMITED", "CESC Limited": "CESC LIMITED",
                    "CSP Distribution  Company ltd": "CHHATTISGARH STATE POWER DISTRIBUTION COMPANY LIMITED",
                    "CSP Distribution Co Ltd": "CHHATTISGARH STATE POWER DISTRIBUTION COMPANY LIMITED",
                    "Dadra and Nagar Haveli and Daman and Diu Power Distribution Corporation Limited": "Dadra and Nagar Haveli and Daman and Diu Power Distribution Corporation Lim",
                    "DNH Power Distribution Corporation Ltd": "DNH Beneficiary",  # "DVC": "DVC",
                    "Electricity Department_Government of Goa WR": "Electricity Department, GOA_WR",
                    "Gift Power Company Ltd": "GIFT Power Company Limited",
                    "Gigaplex Estate Private Limited": "GIGAPLEX ESTATE PRIVATE LIMITED",
                    "Gigaplex Estate pvt ltd": "GIGAPLEX ESTATE PRIVATE LIMITED", "GRIDCO": "GRIDCO LIMITED",
                    # "GRIDCO LIMITED": "GRIDCO LIMITED",
                    "GUJARAT URJA VIKAS NIGAM LTD": "GUJARAT URJA VIKAS NIGAM LIMITED",
                    "GUVNL": "GUJARAT URJA VIKAS NIGAM LIMITED",
                    "Gujarat Urja Vikas Nigam Limited": "GUJARAT URJA VIKAS NIGAM LIMITED",
                    "Himachal Pradesh State Electricity Board Ltd": "HIMACHAL PRADESH STATE ELECTRICITY BOARD LIMITED",
                    "HPSEB": "HIMACHAL PRADESH STATE ELECTRICITY BOARD LIMITED",
                    "Kerala State Electricity Board (KSEB)": "KERALA STATE ELECTRICITY BOARD LIMITED",
                    "Kerala State Electricity Board Limited": "KERALA STATE ELECTRICITY BOARD  LIMITED",
                    "KRC Infrastructure and Projects Pvt Ltd": "KRC INFRASTRUCTURE AND PROJECTS PRIVATE LIMITED",
                    "KRC Infrastructure & Project Pvt Ltd": "KRC INFRASTRUCTURE AND PROJECTS PRIVATE LIMITED",
                    "Maharashtra State Electricity Distribution Company Limited (MSEDCL)": "Maharashtra State Electricity Distribution Co Limited",
                    "MSEDCL": "Maharashtra State Electricity Distribution Co Limited",
                    "Mind Space business Park pvt ltd": "MINDSPACE BUSINESS PARKS PRIVATE LIMITED",
                    "Mindspace Business Parks Pvt Ltd": "MINDSPACE BUSINESS PARKS PRIVATE LIMITED",
                    "Mindspace Business Parks Private Limited": "MINDSPACE BUSINESS PARKS PRIVATE LIMITED",
                    'New Delhi Municipal Council': "New Delhi Municipal Council",
                    "New_Delhi_Municipal council_NDMC": "New Delhi Municipal Council",
                    "Noida Power Company Limited": "Noida Power Company limited",
                    "Noida power Company ltd": "Noida Power Company limited",
                    "Noida Power Company.Ltd": "Noida Power Company limited", "NPCL": "Noida Power Company limited",
                    "North Western Railway": "North Western Railway", "Northern  Railway  UP": "Northern Railway UP",
                    "Northern  Railway UP": "Northern Railway UP", "Northern Railway UP": "Northern Railway UP",
                    "NORTHERN RAILWAY UP": "Northern Railway UP", "Northern Railway": "Northern Railway",
                    "Northern Railway Haryana": "Northern Railway-Haryana",
                    "Power Company of Karnataka Limited -PCKL": "Power Company of Karnataka Ltd",
                    "PCKL": "Power Company of Karnataka Ltd",
                    # "Power Company of Karnataka Ltd": "Power Company of Karnataka Ltd",
                    "Punjab State Power Corporation Ltd (PTC)": "Punjab State Power Corporation Limited",
                    "Rajasthan Urja Vikas Nigam Ltd (RUVNL)": "RAJASTHAN URJA VIKAS NIGAM LIMITED",
                    "Rajasthan Urja Vikas Nigam Ltd": "RAJASTHAN URJA VIKAS NIGAM LIMITED",
                    "Rajasthan Urja Vikas Nigam .ltd": "RAJASTHAN URJA VIKAS NIGAM LIMITED",
                    "Rajasthan Urja Vikas Nigam Limited": "RAJASTHAN URJA VIKAS NIGAM LIMITED",
                    "RUVNL": "RAJASTHAN URJA VIKAS NIGAM LIMITED", "South Western Railway": "South Western Railway",
                    "South  Western  Railway": "South Western Railway",
                    "South  Western Railway": "South Western Railway",
                    "Southern Power Distribution Company of Telangana Limited": "SOUTHERN POWER DISTRIBUTION COMPANY OF TELANGANA LIMITED",
                    "Southern Power Distribution Company of Telangana Limited (TSSPDCL)": "SOUTHERN POWER DISTRIBUTION COMPANY OF TELANGANA LIMITED",
                    "Tamilnadu Generation and Distribution Corporation Limited": "TAMILNADU GENERATION AND DISTRIBUTION CORPORATION LIMITED",
                    "Tamil Nadu  Generation and Distribution Corporation Limited": "TAMILNADU GENERATION AND DISTRIBUTION CORPORATION LIMITED",
                    "Tamilnadu Generation and Dist. Corp. Ltd TANGEDCO": "TAMILNADU GENERATION AND DISTRIBUTION CORPORATION LIMITED",
                    "TANGEDCO": "TAMILNADU GENERATION AND DISTRIBUTION CORPORATION LIMITED",
                    # "Torrent Power Ahmedabad": "Torrent Power Ahmedabad",
                    "TORRENT POWER LIMITED - AHMEDABAD DISTRIBUTION": "Torrent Power Ahmedabad",
                    "Torrent Power Limited - Dahej Distribution": "Torrent Power Limited - Dahej",
                    "TORRENT POWER LIMITED - SURAT DISTRIBUTION": "Torrent Power Surat",
                    "Torrent Power Ltd Surat": "Torrent Power Surat",
                    "Torrent Power Limited- Dahej": "Torrent Power Limited - Dahej",
                    "Torrent Power Ltd Dahej": "Torrent Power Limited - Dahej",
                    # "Torrent Power Surat": "Torrent Power Surat",
                    "U P Power Corporation Ltd": "UPPCL", "Uttar Pradesh Power Corporation Ltd (UPPCL)": "UPPCL",
                    "Uttar Pradesh Power Corporation Ltd": "UPPCL",
                    "Uttar Pradesh Power Corporation Limited (UPPCL)": "UPPCL",
                    "Uttarakhand Power Corporation Limited": "UTTARAKHAND POWER CORPORATION LIMITED",
                    "Uttarakhand Power Corporation": "UTTARAKHAND POWER CORPORATION LIMITED",
                    "Uttrakhand Power Corp Ltd": "UTTARAKHAND POWER CORPORATION LIMITED",
                    "Uttrakhand Power Corp.Ltd": "UTTARAKHAND POWER CORPORATION LIMITED",
                    "Vedanta Ltd_SEZ Unit_Jharsuguda": "Vedanta Limited SEZ UNIT, Jharsuguda",
                    "West Bengal State Electricity Distribution Company Limited (WBSEDCL)": "WEST BENGAL STATE ELECTRICITY DISTRIBUTION COMPANY LIMITED",
                    "West Central Railway": "WEST CENTRAL RAILWAY",

                    "Uttarakhand Power Corporation Ltd": "UTTARAKHAND POWER CORPORATION LIMITED",
                    # "Uttarakhand Power Corporation Limited (UPCL)": "UTTARAKHAND POWER CORPORATION LIMITED",
                    "TPL-Ahmedabad Discom": "TPL-Ahmedabad Discom",

                    "JBVNL": "JHARKHAND BIJLI VITRAN NIGAM LIMITED",
                    "CSPDL": "CHHATTISGARH STATE POWER DISTRIBUTION COMPANY LIMITED",
                    "NUPLLP": "NIDAR UTILITIES PANVEL LLP",  # "REMCL": "Railway Energy Management Company Limited",
                    "LBSCML": "LAXMIPATI BALAJI SUPPLY CHAIN MANAGEMENT LIMITED",
                    "RUVNL": "RAJASTHAN URJA VIKAS NIGAM LIMITED", "BSES": "BSES Rajdhani Power Limited",
                    "BYPL": "BSES Yamuna Power Limited", "IPCL": "India Power Corporation Limited",
                    "APPCC": "Andhra Pradesh Power Coordination Committee", "GUVNL": "Gujarat Urja Vikas Nigam Limited",
                    "MSEZL": "Mangalore SEZ Limited", "APDCL": "ASSAM POWER DISTRIBUTION COMPANY LIMITED",
                    # "MPPMCL": "Madhya Pradesh Power Management Company Limited",
                    "PCKL": "Power Company of Karnataka Ltd", "PSPCL": "Punjab State Power Corporation Limited",
                    "EON KHARADI INFRASTRUCTURE PVT LTD": "EON KHARADI INFRASTRUCTURE PRIVATE LIMITED, Phase -2",
                    # "SEZ BIOTECH SERVICES PRIVATE LIMITED": "RAIPUR ENERGEN LIMITED",
                    # "PFC Consulting Limited": "LAXMIPATI BALAJI SUPPLY CHAIN MANAGEMENT LIMITED",
                    # "Sundew Properties Limited": "LAXMIPATI BALAJI SUPPLY CHAIN MANAGEMENT LIMITED",
                    "TAMILNADU ELECTRICITY BOARD": "Tamil Nadu Electricity Board",
                    "Andhra Pradesh Power Co-Ordination Committee (APPCC)": "Andhra Pradesh Power Coordination Committee",
                    "TANGEDCO ltd": "TAMILNADU GENERATION AND DISTRIBUTION CORPORATION LIMITED",
                    # "MADC LTD": "Maharashtra Airport Development Company Limited",
                    # "RELIANCE ENERGY MUMBAI DISCOM": "TPL-Surat Discom",
                    "UPCL": "UTTARAKHAND POWER CORPORATION LIMITED", "KSEBL": "KSEB",
                    "MAHARASHTRA STATE ELECTRICITY CO LTD": "Maharashtra State Electricity Distribution Co Limited",
                    "CESC": "CESC LIMITED",
                    "HARYANA POWER PURCHASE CENTRE(A JOINT FORUM OF UHBVN&DHBVN)": "Haryana Power Purchase Centre",
                    # "AEML": "AEML SEEPZ Limited",
                    # "TPCL": "TPCL_U7 RLNG / The Tata Power Co Ltd (MTPS)",
                    "TAMILNADU GENERATION AND DISTRIBUTION CORPN LTD": "TAMILNADU GENERATION AND DISTRIBUTION CORPORATION LIMITED",
                    "HPSEBL": "HIMACHAL PRADESH STATE ELECTRICITY BOARD LIMITED", "BEST": "BEST Undertaking",
                    "Chandigarh Electricity Department": "CHANDIGARH",
                    "KRC Infrastructure and Projects Pvt Ltd": "KRC INFRASTRUCTURE AND PROJECTS PRIVATE LIMITED",
                    "MP Power Management Company Ltd": "M.P. POWER MANAGEMENT COMPANY LIMITED",
                    "Assam Power Distribution Company Ltd": "ASSAM POWER DISTRIBUTION COMPANY LIMITED",
                    "Torrent Power Limited": "Torrent Power Limited - Dahej",
                    "MPSEZ Utilities Private Limited": "MPSEZ Utilities Limited",
                    "SOUTHERN POWER DISTRIBUTION COMPANY OF TELANGANA LTD": "SOUTHERN POWER DISTRIBUTION COMPANY OF TELANGANA LIMITED",
                    "WEST BENGAL STATE ELECTRICITY DISTRIBUTION COMPANY LIMITED": "WEST BENGAL STATE ELECTRICITY DISTRIBUTION COMPANY LIMITED",
                    "Noida Power Company Limited": "Noida Power Company limited",
                    "JAWAHARLAL NEHRU PORT TRUST": "Jawaharlal Nehru Port Trust",
                    "GUJARAT URJA VIKAS NIGAM LIMITED": "GUJARAT URJA VIKAS NIGAM LIMITED",
                    "TATA POWER DELHI DISTRIBUTION LIMITED": "Tata Power Delhi Distribution Limited",
                    "MINDSPACE BUSINESS PARKS PRIVATE LIMITED": "MINDSPACE BUSINESS PARKS PRIVATE LIMITED",
                    "BSPHCL": "BSPHCL", "NIDP DEVELOPERS PRIVATE LIMITED": "NIDP DEVELOPERS PRIVATE LIMITED",
                    "GRIDCO LIMITED": "GRIDCO LIMITED",
                    "Gigaplex Estate Private Limited": "GIGAPLEX ESTATE PRIVATE LIMITED",
                    'Andhra Pradesh Power Co-Ordination Committee (Andhra Pradesh Power Coordination Committee)': 'Andhra Pradesh Power Coordination Committee'}

trader_state_mapping = {"Rajasthan": "Rajasthan", "Madhya Pradesh": "Madhya Pradesh", "Meghalaya": "Meghalaya",
                        "Odisha": "Odisha", "Telangana": "Telangana", "Delhi": "Delhi",
                        "Andhra Pradesh": "Andhra Pradesh", "Tamil Nadu": "Tamil Nadu", "Tripura": "Tripura",
                        "Goa": "Goa", "Uttar Pradesh": "Uttar Pradesh", "Punjab": "Punjab", "Haryana": "Haryana",
                        "Jharkhand": "Jharkhand", "Mizoram": "Mizoram", "Karnataka": "Karnataka",
                        "West Bengal": "West Bengal", "Himachal Pradesh": "Himachal Pradesh", "Nagaland": "Nagaland",
                        "Uttarakhand": "Uttarakhand", "Arunachal Pradesh": "Arunachal Pradesh", "Manipur": "Manipur",
                        "Maharashtra": "Maharashtra", "Sikkim": "Sikkim", "Chhattisgarh": "Chhattisgarh",
                        "Assam": "Assam", "Gujarat": "Gujarat", "Kerala": "Kerala", "Bihar": "Bihar",
                        "Chandigarh": "Chandigarh", "Puducherry": "Puducherry",
                        "Jammu and Kashmir": "Jammu and Kashmir", "Himachal Prades": "Himachal Pradesh",
                        "Madhya Pradhesh": "Madhya Pradesh", "Arunachal Prades": "Arunachal Pradesh",
                        "Himanchal Pradesh": "Himachal Pradesh", "Andhara Pradesh": "Andhra Pradesh",
                        "Andhrai Pradesh": "Andhra Pradesh", "Himachal\n Pradesh": "Himachal Pradesh",
                        "Madhya\n Pradesh": "Madhya Pradesh", "Arunachal\n Pradesh": "Arunachal Pradesh",
                        "Chhatisgarh": "Chhattisgarh", "West  Bengal": "West Bengal", "W est Bengal": "West Bengal",
                        "Chhattisga rh": "Chhattisgarh", "Uttar Pradhesh": "Uttar Pradesh",
                        "Andhra Prades": "Andhra Pradesh", "Chhattisg arh": "Chhattisgarh",
                        "Uttarakh and": "Uttarakhand", "Uttar Prades h": "Uttar Pradesh",
                        "Chhattishgarh": "Chhattisgarh", "Chhattisga\nrh": "Chhattisgarh",
                        "Chhattisgar h": "Chhattisgarh", "Chhattisgharh": "Chhattisgarh",
                        "Uttar Pradaesh": "Uttar Pradesh", "Maharashtr a": "Maharashtra",
                        "Maharashtr\na": "Maharashtra", "hhattisgarh": "Chhattisgarh",
                        "Madhya Prades": "Madhya Pradesh", "ndhra Pradesh": "Andhra Pradesh",
                        "Chhattisg\narh": "Chhattisgarh", "Chhattisgar": "Chhattisgarh",
                        "MadhyaPradesh": "Madhya Pradesh", "West Benagal": "West Bengal",
                        "Uttar\n Pradesh": "Uttar Pradesh", "Maharastra": "Maharashtra", "Uttrakhand": "Uttarakhand",
                        "TamilNadu": "Tamil Nadu", "Karnatak a": "Karnataka", "WestBengal": "West Bengal",
                        "West Benga": "West Bengal", "Telangan\na": "Telangana", "Maharshtra": "Maharashtra",
                        "Meghalaya ": "Meghalaya", "Meghalay": "Meghalaya", "Himachal\nPradesh": "Himachal Pradesh",
                        "Rajsthan": "Rajasthan", "Karnatka": "Karnataka", "Himachal Predesh": "Himachal Pradesh",
                        "runachal Prades": "Arunachal Pradesh", "Jammu And Kashmir": "Jammu and Kashmir",
                        "Meghalya": "Meghalaya", "Himachal Praedsh": "Himachal Pradesh", "Karnatak": "Karnataka",
                        "Arunachal\nPradesh": "Arunachal Pradesh", "himachal Pradesh": "Himachal Pradesh",
                        "Himachal pradesh": "Himachal Pradesh", "Madhya\nPradesh": "Madhya Pradesh",
                        "Madhya pradesh": "Madhya Pradesh", "madhya Pradesh": "Madhya Pradesh",
                        "Andhra\nPradesh": "Andhra Pradesh", "Himachal Prade": "Himachal Pradesh",
                        "Andhra pradesh": "Andhra Pradesh", "Madhya  Prades": "Madhya Pradesh",
                        "Madhva Pradesh": "Madhya Pradesh", "Madhya Pradosh": "Madhya Pradesh", "Gujarat ": "Gujarat",
                        "andhra Pradesh": "Andhra Pradesh", "Gujrat": "Gujarat", "Uttar\nPradesh": "Uttar Pradesh",
                        "Chattishgarh": "Chhattisgarh", "Uttar pradesh": "Uttar Pradesh",
                        "Andhra Prade": "Andhra Pradesh", "Odisha ": "Odisha", "Madhya Prade": "Madhya Pradesh",
                        "Odish a": "Odisha", "Uttar Pradosh": "Uttar Pradesh", "Uttar Pracesh": "Uttar Pradesh",
                        "Uttar Predesh": "Uttar Pradesh", " Punjab": "Punjab", "Punja b": "Punjab",
                        "Utter Pradesh": "Uttar Pradesh", " Odisha": "Odisha", "West BengaL": "West Bengal",
                        "West\nBengal": "West Bengal", "West bengal": "West Bengal", "West Bangal": "West Bengal",
                        "West Benaal": "West Bengal", "Odsha": "Odisha", "Maharashrra": "Maharashtra",
                        "west Bengal": "West Bengal", "Tamil nadu": "Tamil Nadu", "Tamil\nNadu": "Tamil Nadu",
                        "Maharasht": "Maharashtra", "Uttarakha": "Uttarakhand", "nachal Pradesh": "Arunachal Pradesh",
                        "Himachal Prad": "Himachal Pradesh", "AAadhya Pradesh": "Madhya Pradesh",
                        "Madhya Pradesh/WR": "Madhya Pradesh", "Uttar Pradesh/NR": "Uttar Pradesh",
                        "meghalaya": "Meghalaya", "karnataka": "Karnataka", "Chhattisgarh rh": "Chhattisgarh",
                        "Maghalaya": "Meghalaya", "Chhattisgarh\nrh": "Chhattisgarh", "KArnataka": "Karnataka",
                        "Telengana": "Telangana", "Madhya Pradei": "Madhya Pradesh", "Madhya Prade<": "Madhya Pradesh",
                        "Jammu & Kashmir": "Jammu and Kashmir", "Andhra Prad": "Andhra Pradesh",
                        "adhya Prade": "Madhya Pradesh", "ndhra Prade": "Andhra Pradesh",
                        "West Bengal/ER": "West Bengal", "Maharashtra ra": "Maharashtra",
                        "Himanchal Prad": "Himachal Pradesh", "Uttar Prad": "Uttar Pradesh",
                        "Jammu Kashmir": "Jammu and Kashmir", "Chhattisagr": "Chhattisgarh",
                        "Chattisaarh": "Chhattisgarh", "MadhyaPradesh/WR": "Madhya Pradesh",
                        "Madhya\npradesh": "Madhya Pradesh", "gujarat": "Gujarat", "Guiarat": "Gujarat",
                        "Karnataka/SR": "Karnataka", "UttarPradesh/NR": "Uttar Pradesh", "Chhattisg": "Chhattisgarh",
                        "GUjarat": "Gujarat", "DVC\nWest Bengal": "West Bengal", "andhra Prade": "Andhra Pradesh",
                        "madhya Prade": "Madhya Pradesh", "Jammu  & Kashmir": "Jammu and Kashmir",
                        "Chhatisgarh/WR": "Chhattisgarh", "Madhya Pradt": "Madhya Pradesh", "Tamilnadu": "Tamil Nadu",
                        "Jammu &Kashmir": "Jammu and Kashmir", "Madhya\nPradesh/WR": "Madhya Pradesh",
                        "Kerela": "Kerala", "Odissa": "Odisha", "sikkim": "Sikkim", "odisha": "Odisha",
                        "Andhra Pra": "Andhra Pradesh", "Odhisa": "Odisha", "Siikim": "Sikkim", "Odtsha": "Odisha",
                        "Odishn": "Odisha", "Odlsha": "Odisha", "WestBengal/ER": "West Bengal",
                        "Uttar\nPradesh/NR": "Uttar Pradesh", "Maharastra/WR": "Maharashtra", "kerala": "Kerala",
                        "Arunachal Pr": "Arunachal Pradesh", "west bengal": "West Bengal", "karnatka": "Karnataka",
                        "Mabarashzra": "Maharashtra", "WB, Jharkhand": "Jharkhand",
                        "Madhya Pradesh/WRLDC": "Madhya Pradesh", "Gujarat/WR": "Gujarat",
                        "Andhra Pradesh/SRLDC": "Andhra Pradesh", "Jammu & kashmir": "Jammu and Kashmir",
                        "Arunachal Pradesh (Assam)": "Arunachal Pradesh (Assam)", "delhi": "Delhi", "DElhi": "Delhi",
                        "Tamilnad u": "Tamil Nadu", "Jammu and_x000D_Kashmir": "Jammu and Kashmir",
                        "Uttarpardesh": "Uttar Pradesh", "TAMil Nadu": "Tamil Nadu", "Tamilanadu": "Tamil Nadu",
                        "Delhi(Andhra Pradesh)": "Delhi (Andhra Pradesh)", "B-har": "Bihar", "Briar": "Bihar",
                        "Sikkim/ER": "Sikkim", "Odisha/ER": "Odisha", "Punjab/NR": "Punjab",
                        "Himachal_x000D_Pradesh": "Himachal Pradesh",
                        "Arunachal Pradesh (Sikkim)": "Arunachal Pradesh (Sikkim)", "Madhya PradESH": "Madhya Pradesh",
                        "Meghayala": "Meghalaya", "Uttarprade": "Uttar Pradesh", "Madhya Pr": "Madhya Pradesh",
                        "Haryana DVC": "Haryana", "For Haryana": "Haryana", "Tamilnad": "Tamil Nadu",
                        "Telangana SLDC": "Telangana", "dhya Prad": "Madhya Pradesh", "Himachal P": "Himachal Pradesh",
                        "Chhattisgar_x000D_h": "Chhattisgarh",
                        "Arunachal Pradesh (Manipur)": "Arunachal Pradesh (Manipur)", "Tamil Nadu/SRLDC": "Tamil Nadu",
                        "Delhi/NR": "Delhi", "Bihar/ER": "Bihar", "Raipur": "Manipur", "achal Prad": "Himachal Pradesh",
                        "Andhra_x000D_Pradesh": "Andhra Pradesh", "Madhya_x000D_Pradesh": "Madhya Pradesh",
                        "Arunachal Pradesh (Himachal)": "Arunachal Pradesh (Himachal Pradesh)",
                        "Delhi(West Bengal)": "Delhi (West Bengal)", "Delhi(Maharashtra)": "Delhi (Maharashtra)",
                        "arnil Nadu": "Tamil Nadu", "Uttar_x000D_Pradesh": "Uttar Pradesh",
                        "Telangana/SRLDC": "Telangana", "KeralaSLDC": "Kerala",
                        "Hiamchal_x000D_Pradesh": "Himachal Pradesh", "Cdsha": "Odisha",
                        "Dadra and Nagar Havel i": "Dadra and Nagar Haveli and Daman and Diu",
                        "uttarpardesh": "Uttar Pradesh", "Haryana (Uttar Pradesh)": "Haryana",
                        "Madhya_x000D_pradesh": "Madhya Pradesh",
                        "Dadra and Nagar Haveli": "Dadra and Nagar Haveli and Daman and Diu", "Odisha SLDC": "Odisha",
                        "Guiaiat": "Gujarat", "Assam/NER": "Assam", "New Delhi": "Delhi", "Pradesh": "Uttar Pradesh",
                        "Gujarat/WRLDC": "Gujarat", "Telangana Haryana": "Telangana",
                        "Haryana (West Bengal)": "Haryana", "Andhra State": "Andhra Pradesh",
                        "Dadra and Nagar Haveli (UT)": "Dadra and Nagar Haveli and Daman and Diu",
                        "Jammu &_x000D_Kashmir": "Jammu and Kashmir",
                        "Arunachal Pradesh (Uttar Pradesh)": "Arunachal Pradesh", "GoA": "Goa", "Orissa": "Odisha",
                        "Himachal": "Himachal Pradesh", "Orrisa": "Odisha",
                        "Arunachal Pradesh (Andhra Pradesh)": "Arunachal Pradesh", "Delhi(Haryana)": "Delhi",
                        "Odftha": "Odisha", "Debi": "Delhi", "Gon": "Goa", "Manipur/NERLDC": "Manipur",
                        "Tamil": "Tamil Nadu",
                        "Dadra and\nNagar Haveli (UT)": "Dadra and Nagar Haveli and Daman and Diu",
                        "Dadra\nand Nagar Haveli (UT)": "Dadra and Nagar Haveli and Daman and Diu",
                        "Dadar And Nagar Haveli": "Dadra and Nagar Haveli and Daman and Diu",
                        "West Bengal (Uttar Pradesh)": "West Bengal (Uttar Pradesh)",
                        "adra and Nagar Have": "Dadra and Nagar Haveli and Daman and Diu",
                        "Haryana (Meghalaya)": "Haryana (Meghalaya)",
                        "Dadra & Nagar Haveli": "Dadra and Nagar Haveli and Daman and Diu", "Odisha Odisha": "Odisha",
                        "Dadra Nagar Haveli": "Dadra and Nagar Haveli and Daman and Diu",
                        "UTTAR\nPradesh": "Uttar Pradesh", "Uttar": "Uttarakhand",
                        "Dadara & Nagar Haveli": "Dadra and Nagar Haveli and Daman and Diu",
                        "Tamil Nadu & Rajasthan": "Tamil Nadu",
                        "Dadra & Nagar Havel": "Dadra and Nagar Haveli and Daman and Diu",
                        "Dad ar Nagar Haveli": "Dadra and Nagar Haveli and Daman and Diu",
                        "Haryana (Orrisa)": "Haryana (Odisha)", "Andhra": "Andhra Pradesh",
                        "Dadra & Nagar\nHaveli": "Dadra and Nagar Haveli and Daman and Diu",
                        "Dadra &\nNagar Haveli": "Dadra and Nagar Haveli and Daman and Diu",
                        "Dadra\n& Nagar Haveli": "Dadra and Nagar Haveli and Daman and Diu", "Deltv": "Delhi",
                        "Dadar Nagar Haveli": "Dadra and Nagar Haveli and Daman and Diu",
                        "adra and Nagar Haw": "Dadra and Nagar Haveli and Daman and Diu",
                        "Dadra Nager Haveli": "Dadra and Nagar Haveli and Daman and Diu",
                        "adra And Nagar have": "Dadra and Nagar Haveli and Daman and Diu",
                        "Haryana (Manipur)": "Haryana (Manipur)", "Arunach": "Arunachal Pradesh",
                        "Dadar &\nNagar Haveli": "Dadra and Nagar Haveli and Daman and Diu",
                        "Daman and Diu\n- Dadra and Nagar Haveli": "Dadra and Nagar Haveli and Daman and Diu",
                        "Uttarpradesh": "Uttar Pradesh", "Himachal Pradesh/SR": "Himachal Pradesh",
                        "Chhattishgarh/WR": "Chhattisgarh", "Andrapradesh": "Andhra Pradesh",
                        "Chhatisgarh ": "Chhattisgarh", "Rajasthan/NR": "Rajasthan", "Chhattisgar/SR": "Chhattisgarh",
                        "Madhya\nPardesh": "Madhya Pradesh", "Andhra Prade sh": "Andhra Pradesh",
                        "andhra pradesh": "Andhra Pradesh", "west  bengal": "West Bengal", "Karanataka": "Karnataka",
                        "utttar Pradesh": "Uttar Pradesh", "Punjab /NR": "Punjab", "TamilNadu/SR": "Tamil Nadu",
                        "Tamil Nadu/SR": "Tamil Nadu", "Himachal pradesh/SR": "Himachal Pradesh",
                        "andhra  Pradesh": "Andhra Pradesh", "madhya  Pradesh": "Madhya Pradesh",
                        "Madhya Pradesh/SR": "Madhya Pradesh", "Jammu and  Kashmir": "Jammu and Kashmir",
                        "AndhraPradesh/SR": "Andhra Pradesh", "Tamilnadu/SR": "Tamil Nadu",
                        "Uttarpradesh/NR": "Uttar Pradesh", "Chhattishgarh/ SR": "Chhattisgarh",
                        "DVC/West Bengal": "West Bengal", "Chattisgarh/WR": "Chhattisgarh",
                        "Jammu  &Kashmir": "Jammu and Kashmir", "andhrapradesh": "Andhra Pradesh",
                        "Haryana\nDVC": "Haryana", "Telangana\nSLDC": "Telangana", "Telangana\nHaryana": "Telangana",
                        "Dadra and Nagar Haveli\n(UT)": "Dadra and Nagar Haveli and Daman and Diu",
                        "Daman and Diu - Dadra and Nagar Haveli": "Dadra and Nagar Haveli and Daman and Diu",
                        "Bangladesh": "Bangladesh", "Haryana (Himachal)": "Haryana (Himachal Pradesh)",
                        "Delhi (Nepal)": "Delhi (Nepal)",
                        "Daman and Diu -\n Dadra and Nagar Haveli": "Dadra and Nagar Haveli and Daman and Diu",
                        "Daman and Diu - Dadra and Nagar\n Haveli": "Dadra and Nagar Haveli and Daman and Diu",
                        "Bhutan": "Bhutan", "Dadra and Nagar": "Dadra and Nagar Haveli and Daman and Diu",
                        "Nepal": "Kerala", "Haryana (AAeghalaya)": "Haryana (Meghalaya)",
                        "Daman and Diu - Dadra and Nagar\nHaveli": "Dadra and Nagar Haveli and Daman and Diu",
                        "HIMACHAL pradesh": "Himachal Pradesh", "Hyderabad": "Hyderabad",
                        "Daman and Diu": "Dadra and Nagar Haveli and Daman and Diu", "for Bangladesh": "Bangladesh",
                        "Delhi(Himachal)": "Delhi (Himachal Pradesh)",
                        "Daman and Diu UT": "Dadra and Nagar Haveli and Daman and Diu", "Chennai": "Chennai",
                        "Dadra & Na": "Dadra and Nagar Haveli and Daman and Diu", "Tangedco": "Tangedco",
                        "Mumbai": "Mumbai", "Discom": "Discom", "Jammu": "Jammu and Kashmir",
                        "Daman & Diu": "Dadra and Nagar Haveli and Daman and Diu",
                        "Daman &\nDiu": "Dadra and Nagar Haveli and Daman and Diu", "Solar\nProjects": "Solar Projects",
                        "Orissa/ERLDC": "Odisha", "biiutan": "Bhutan",
                        "a & Nagar H": "Dadra and Nagar Haveli and Daman and Diu",
                        "DADRA Nagar": "Dadra and Nagar Haveli and Daman and Diu", "bhutan": "Bhutan",
                        "Dadra & N": "Dadra and Nagar Haveli and Daman and Diu", "Orissa       ,": "Odisha",
                        "U P": "Uttar Pradesh", "J & K": "Jammu and Kashmir",
                        "Damodar Valley Corporation/ER": "Dadra and Nagar Haveli and Daman and Diu",
                        "Depending on Source": "Depending on Source", "GOA": "Goa",
                        "Damodar VallyCorporation/ER": "Damodar Vally Corporation", "GCA": "Goa", "WB": "West Bengal",
                        "TAMIL NADU": "Tamil Nadu", "ISGS": "ISGS", "TELANGANA a": "Telangana",
                        "TAMNIL NADU": "Tamil Nadu", "AP": "AP", "MeECL": "MeECL", "for NEA": "for NEA",
                        "RAJASTHAN N": "Tamil Nadu", "UTTAR PRA": "Uttar Pradesh", "UP": "Uttar Pradesh",
                        "DADRA & NAGAR HAVELI": "Dadra and Nagar Haveli and Daman and Diu",
                        "UTTAR PRAD": "Uttar Pradesh", "BHUTAN": "Bhutan", "DNH": "DNH", "HP": "Himachal Pradesh",
                        "DVC": "DVC", "MP": "Madhya Pradesh", "SR": "SR", "ANDHRA PRA": "Andhra Pradesh", "KR": "KR",
                        "HIMACHAL PR": "Himachal Pradesh",
                        "DADRA AND NAGAR HAVELI": "Dadra and Nagar Haveli and Daman and Diu", "M.P": "Madhya Pradesh",
                        "DRA & NAGAR HAV": "Dadra and Nagar Haveli and Daman and Diu", "TTAR PRADES": "Uttar Pradesh",
                        "ADHYA PRADE": "Madhya Pradesh", "NDHRA PRADE": "Andhra Pradesh", "WBSLDC": "West Bengal",
                        "ADRA & NAGAR HAVE": "Dadra and Nagar Haveli and Daman and Diu",
                        "DADRA & NAGAR HA": "Dadra and Nagar Haveli and Daman and Diu",
                        "MADHYA PRADES": "Madhya Pradesh", "GUJRAT": "Gujarat", "TAMILNAD": "Tamil Nadu",
                        "DAMAN& DIU": "Dadra and Nagar Haveli and Daman and Diu", "J&K": "Jammu and Kashmir",
                        "PSEB": "Punjab", "ASEB": "Assam", "GJSLDC": "GJSLDC", "CSEB": "CSEB", "BSEB": "BSEB",
                        "RAJASTHAN": "Rajasthan", "TELANGANA": "Telangana", "TELENGANA": "Telangana",
                        "TAMILNADU": "Tamil Nadu", "DAMAN & DIU": "Dadra and Nagar Haveli and Daman and Diu",
                        "UTTAR PRADESH H": "Uttar Pradesh", "UPSLDC": "Uttar Pradesh", "DELHI": "Delhi",
                        "GUJARAT": "Gujarat", "BIHAR": "Bihar", "ASSAM": "Assam", "NEPAL": "Nepal",
                        "MPPMCL": "Madhya Pradesh", "WESTBENGAL": "West Bengal", "JAMMU KASHMIR": "Jammu and Kashmir",
                        "UTTRAKHAND": "Uttar Pradesh", "RYANA": "Haryana", "ANDHRA PRADESH H": "Andhra Pradesh",
                        "APSLDC": "APSLDC", "WEST": "West Bengal", "UTTARAKHAND": "Uttarakhand",
                        "JAMMU& KASHMIR": "Jammu and Kashmir", "TELANGANA A": "Telangana", "MANIPUR": "Manipur",
                        "WEST BENGAL": "West Bengal", "HIMANCHAL PRADESH": "Himachal Pradesh",
                        "ADRA NAGAR HAVE": "Dadra and Nagar Haveli and Daman and Diu",
                        "HIMACHAL PRADES H": "Himachal Pradesh", "KWHEP": "KWHEP", "PUNJAB": "Punjab",
                        "ODISHA": "Odisha", "KERALA": "Kerala", "ER": "ER", "PSPCL": "PSPCL", "OSIDHA": "Odisha",
                        "DAMAN &D": "Dadra and Nagar Haveli and Daman and Diu", "KERELA": "Kerala", "ARYANA": "Haryana",
                        "ORISSA": "Odisha", "PUNJA3": "Punjab", "JHSLDC": "Jharkhand", "DLSLDC": "DLSLDC",
                        "KPTCL": "KPTCL", "JITPL": "JITPL", "TRIPURA": "Tripura", "HARYANA": "Haryana",
                        "SIKKIM": "Sikkim", "MEGHALAYA": "Meghalaya", "MAHARAS": "Maharashtra", "MIZORAM": "Mizoram",
                        "DISTRIBUTION CORPORATI": "Distribution Corporation", "JHARKHAND D": "Jharkhand",
                        "JAMMU AND_x000D_KASHMIR": "Jammu and Kashmir", "JAMMU &_x000D_KASHMIR": "Jammu and Kashmir",
                        "BANGLA DESH": "Bangladesh", "JHARKHAND": "Jharkhand", "MAHAR ASHTRA": "Maharashtra",
                        "BANGLADESH": "Bangladesh", "MAHARASH": "Maharashtra", "WEST_x000D_BENGAL": "West Bengal",
                        "UTTAR PRADESH": "Uttar Pradesh", "ANDHRAPRADESH": "Andhra Pradesh",
                        "DAMODAR VALLY CORPORATION": "Damodar Vally Corporation",
                        "DAMODAR VALLY": "Damodar Vally Corporation", "KARNATAKA": "Karnataka",
                        "ANDHRA PRADESH": "Andhra Pradesh", "CHATTISGARH": "Chattisgarh",
                        "MADHYA PRADESH": "Madhya Pradesh", "CHATTISHGAR": "Chattisgarh", "CHHATTISGAR": "Chattisgarh",
                        "KARANATAK": "Karnataka", "CHHATTISGARH": "Chattisgarh", "MAHARSHTRA": "Maharashtra",
                        "HIMACHAL PRADESH": "Himachal Pradesh", "MAHARASHTR": "Maharashtra",
                        "CHATTISHGARH": "Chattisgarh", "MAHSRSHTRA": "Maharashtra", "MAHARASHTRA": "Maharashtra",
                        "MAHARAS HTRA": "Maharashtra", "UTTAR_x000D_PRADESH": "Uttar Pradesh",
                        "HIMACHAL_x000D_PRADESH": "Himachal Pradesh",
                        "CHATTISGARH CHATTISGARH CHATTISGARH CHATTISGARH CHATTISGARH CHATTISGARH": "Chattisgarh",
                        'ANDHRA\nPRADESH': 'Andhra Pradesh', 'Chattisgarh': 'Chhattisgarh',
                        'Chhattisagrh     ': 'Chhattisagrh', 'Chhattisagrh': 'Chhattisagrh',
                        'HIMACHAL\nPRADESH': 'Himachal Pradesh', 'HIMACHAL PRADESH\nH': 'Himachal Pradesh',
                        'HIMACHAL PRADESH H': 'Himachal Pradesh', 'HIMACHAL PRADES\nH': 'Himachal Pradesh',
                        'JAMMU\n& KASHMIR': 'Jammu and Kashmir', 'JAMMU & KASHMIR': 'Jammu and Kashmir',
                        'JAMMU &\nKASHMIR': 'Jammu and Kashmir', 'MADHYA\nPRADESH': 'Madhya Pradesh',
                        'MADHYA PRADESH H': 'Madhya Pradesh', 'MADHYA PRADESH\nH': 'Madhya Pradesh',
                        'WEST\nBENGAL': 'West Bengal', 'MAHARAS\nHTRA': 'Maharashtra',
                        'UTTAR\nPRADESH': 'Uttar Pradesh', }

trader_category_mapping = {"IPP": "IPP", "ISGS": "ISGS", "Distribution Licensee": "Distribution Licensee",
                           "Government": "Government", "Generator": "Generator", "Captive": "Captive",
                           "Discom Consumer": "Discom Consumer", "State Utility": "State Utility", "Discom": "Discom",
                           "Industrial Consumer": "Industrial Consumer", "Consumer": "Consumer",
                           "Utility": "State Utility", "Thermal": "Thermal", "RE Power": "RE Power", "Hydro": "Hydro",
                           "Deemed Distribution Licensee": "Deemed Distribution Licensee",
                           "Trading Licensee": "Trading Licensee", "Industry": "Industry", "Non Solar": "Non Solar",
                           "SPD": "SPD", "WPD": "WPD", "HPD": "HPD", "Power Exchange": "Power Exchange",
                           "OA Consumer": "OA Consumer", "DVVNL": "DVVNL", "Trader/Discom": "Trader/Discom",
                           "Trader/OAC": "Trader/OAC", "Bulk Consumer": "Bulk Consumer", "Solar": "Solar",
                           "Industrial Buyer": "Industrial Buyer", "IEX": "IEX", "Small Hydro": "Small Hydro",
                           "Bulk Power": "Bulk Power", "Trader (Government)": "Trader (Government)", "Hotel": "Hotel",
                           "Buyer": "Buyer", "Biomass": "Biomass", "Nodal Agency": "Nodal Agency",
                           "Central Govt. Organisation": "Central Government Organisation",
                           "District Licensee": "District Licensee", "Bagasse": "Baggasse", "IPP ": "IPP",
                           "Commercial": "Commercial", "Cogen": "Cogen", "District Licencee": "District Licensee",
                           "Dicsom": "Discom", "Disocm": "Discom", "Deisom": "Discom", "Oiscom": "Discom",
                           "Drstnoution Licensee": "Distribution Licensee",
                           "Dctrfcution Licensee": "Distribution Licensee", "cogen": "Cogen", "hydro": "Hydro",
                           "DeemedDistribution": "Distribution Licensee", "Dist. licensee": "District Licensee",
                           "Power": "Power Exchange", "Discorn": "Discom",
                           "Ootnbuton Licensee": "Distribution Licensee",
                           "Dtstrrtxrton Licensee": "Distribution Licensee", "Trader": "Trader", "IPP I": "IPP",
                           "Exchange": "Power Exchange", "Trader (Consumer)": "Trader (Consumer)",
                           "Power_x000D_Exchnage": "Power Exchange", "State Licensee": "State Licensee",
                           "Di scorn": "Discom", "Trader/DISCOM": "Trader/Discom",
                           "Govt. Organisation": "Central Government Organisation", "CPP": "IPP",
                           "StateLicensee": "State Licensee", "fPP": "IPP", "State DISCOM": "State Discom",
                           "SHEP": "SHEP", "GAS": "Gas", "Seller": "Seller", "DISCOMS": "Discom",
                           "DISTRIBUTION Licensee": "Distribution Licensee",
                           "Govt. of UP": "Government of Uttar Pradesh", "Co-Gen IPP": "Cogen IPP",
                           "StateDISCOM": "State Discom", "HYDRO": "Hydro",
                           "DaofciXion bcw.sea": "Distribution Licensee",
                           "Ofe.-ritnyjon Lk-sroeo": "Distribution Licensee", "DISCOM": "Discom",
                           "PX": "Power Exchange", "Tamilnadu": "Tamil Nadu", "Meghalaya": "Meghalaya",
                           "OA CONSUMER": "OA Consumer", "INDUSTRY": "Industry", "GED": "GED", "TRADER": "Trader",
                           "BUYER": "Buyer", "TRUST": "Trust", "CONSUMER": "Consumer", "SELLER": "Seller", "ipp": "IPP",
                           "GENERATOR": "Generator", "UTILITY": "State Utility", '-': '', 'Capative': 'Captive',
                           'Deemed Distribution Licencee': 'Deemed Distribution Licensee',
                           'State_x000D_Utility': 'State Utility', '  Discom': 'Discom',
                           'Distribution_x000D_Licensee': 'Distribution Licensee', 'Trader/ Discom': 'Trader/Discom',
                           'Industrial\nConsumer': 'Industrial Consumer', 'Industrial': 'Industrial Consumer',
                           'Deemed_x000D_Distribution': 'Deemed Distribution Licensee',
                           'Deemed_x000D_Distribution_x000D_Licencee': 'Deemed Distribution Licensee',
                           'Deemed\nDistribution\nLicencee': 'Deemed Distribution Licensee',
                           'Deemed_x000D_Distribution_x000D_Licensee': 'Deemed Distribution Licensee',
                           'Deemed\nDistribution': 'Deemed Distribution Licensee', 'Utilitiy': 'State Utility',
                           'State Utilit': 'State Utility', 'State': 'State Utility',
                           'State Utility_x000D_State Utility_x000D_State Utility': 'State Utility',
                           'Distributio': 'Distribution Licensee', 'Governme': 'Government',
                           'Distribution': 'Distribution Licensee', 'Distribution\nLicensee': 'Distribution Licensee',
                           'OA_x000D_Consumer': 'OA Consumer', ' Industry': 'Industry', 'Dicom': 'Discom',
                           'OA\nConsumer': 'OA Consumer', 'vernment': 'Government', 'vernmentHA': 'Government',
                           'Industries': 'Industry', 'T rader (Government)': 'Trader (Government)',
                           'T rader {Government)': 'Trader (Government)',
                           'O-.tnbutcn Licensee': 'Distribution Licensee',
                           'DseritxAon Lsoer.seo': 'Distribution Licensee',
                           "Grzn.'xZkn Licensee": 'Distribution Licensee',
                           'Distribution License©': 'Distribution Licensee', 'Govornmont': 'Government',
                           'Open\n Access consumer': 'Open Access Consumer',
                           'Open Access consumer': 'Open Access Consumer',
                           'Open Access\n consumer': 'Open Access Consumer', 'Distribution l': 'Distribution Licensee',
                           'Distribution licens': 'Distribution Licensee', 'Power Exchanges': 'Power Exchange',
                           'dustrial Consume': 'Industrial Consumer', 'State_x000D_DISCOM': 'State Discom',
                           'Generators': 'Generator', 'Generator s': 'Generator', 'Power Exchnage': 'Power Exchange',
                           'tate Utility': 'State Utility', 'bagasse': 'Baggase', 'State\nUtility': 'State Utility',
                           'State Utility_x000D_State Utility': 'State Utility', 'Power\nExchange': 'Power Exchange',
                           'Dist. Licencee': 'Distribution Licensee', 'State\nDISCOM': 'State Discom',
                           'Discern': 'Discom', '.HYDRO': 'Hydro', 'Uility': 'State Utility',
                           'District licencee': 'District Licensee', 'Power  Exchange': 'Power Exchange',
                           'Disco m': 'Discom', 'Open Access Consumer': 'OA Consumer',
                           'Open\n Access Consumer': 'OA Consumer', 'State Utiity': 'State Utility',
                           'State\nLicensee': 'State Licensee', 'Trader/Disco': 'Trader/Discom',
                           'Distribution License': 'Distribution Licensee', }

trader_entity_name = ['SEIL ENERGY INDIA LIMITED', 'Jhabua Power Limited', 'Jaypee Nigrie Super Thermal Power Plant',
                      'BSES Yamuna Power Limited', 'BSES Rajdhani Power Limited',
                      'ADHUNIK POWER & NATURAL RESOURCES LIMITED', 'RAIPUR ENERGEN LIMITED',
                      'GOODWILL ENERGY ENTERPRISES', 'JINDAL POWER LIMITED',
                      'HIMACHAL PRADESH STATE ELECTRICITY BOARD LIMITED', 'MALANA POWER COMPANY LIMITED',
                      'NAVA BHARAT ENERGY INDIA LIMITED', 'NAVA BHARAT VENTURES LIMITED',
                      'Punjab State Power Corporation Limited', 'BANNARI AMMAN SUGARS LIMITED',
                      'NSL SUGARS LIMITED, KOPPA', 'Yogindera Powers Limited', 'Power Company of Karnataka Ltd',
                      'Singoli Bhatwari HEP', 'Jindal Power Limited, Stage-2', 'MB POWER (MADHYA PRADESH) LIMITED',
                      'Haryana Power Purchase Centre', 'Jindal India Thermal Power Limited',
                      'Department of Power Government of Nagaland', 'KSK MAHANADI POWER COMPANY LIMITED',
                      'Andhra Pradesh Central Power Distribution Corporation Limited',
                      'MANIPUR STATE POWER DISTRIBUTION COMPANY LIMITED', 'ASSAM POWER DISTRIBUTION COMPANY LIMITED',
                      'DOP, Govt. of Arunachal Pradesh', 'POWER DEPARTMENT,GOVERNMENT OF SIKKIM',
                      'Adani Electricity Mumbai Limited', 'D B Power Limited',
                      'SOUTHERN POWER DISTRIBUTION COMPANY OF TELANGANA LIMITED', 'GODAVARI BIOREFINERIES LIMITED',
                      'NSL Krishnaveni sugars limited', 'IL&FS TAMIL NADU POWER COMPANY LIMITED',
                      'Dalmia Cement Bharat Limited', 'TAMILNADU GENERATION AND DISTRIBUTION CORPORATION LIMITED',
                      'MEGHALAYA POWER DISTRIBUTION CORPORATION LIMITED', 'Jaypee Bina Thermal Power Plant',
                      'BLA POWER PRIVATE LIMITED', 'Jindal Power Limited, Stage-1', 'RAIGARH ENERGY GENERATION LIMITED',
                      'ADANI POWER RAJASTHAN LIMITED', 'UDUPI POWER CORPORATION LIMITED',
                      'BHILANGANA HYDRO POWER LIMITED', 'Government of Himachal Pradesh',
                      'Prayagraj Power Generation Company Limited', 'CHOUDHARY POWER PROJECTS PVT LTD',
                      'MRN CANE POWER INDIA LIMITED', 'SHAMANUR SUGARS LIMITED', 'Sainj HEP', 'PUNJAB', 'HARYANA',
                      'Dikchu Hydro Electric Project (Sneha Kinetic Power Projects Pvt. Ltd.)', 'B S ISPAT LIMITED',
                      'MAHAN ENERGEN LIMITED.', 'Electricity Department, GOA_WR',
                      'ADANI WIND ENERGY KUTCHH FIVE LIMITED', 'SBESS Services Projectco Two Private Limited',
                      'Southern Power Distribution Company Of AP LIMITED',
                      'Dalmia Cement Bharat Ltd, Unit kapilas Cement Manufacturing Works',
                      'ADANI SOLAR ENERGY JODHPUR TWO LIMITED', 'New Delhi Municipal Council',
                      'SBSR Power Cleantech Eleven Private Limited', 'Ostro Energy Private Limited',
                      'COROMANDEL SUGARS LIMITED', 'Meghalaya Power Limited', 'Adani Power Ltd-Stage-3 (U-9)',
                      'LANCO AMARKANTAK POWER LIMITED', 'Maruti Clean Coal and Power Limited',
                      'MYTRAH VAYU (SOM) PRIVATE LIMITED', 'Torrent Power Limited - Dahej',
                      'SHIVASHAKTI SUGARS LIMITED', 'MAITHON POWER LIMITED', 'KERALA STATE ELECTRICITY BOARD  LIMITED',
                      'WEST BENGAL STATE ELECTRICITY DISTRIBUTION COMPANY LIMITED', 'Noida Power Company limited',
                      'TADAS WIND ENERGY PRIVATE LIMITED', 'ODISHA', 'JHARKHAND',
                      'CONTINUUM POWER TRADING (TN) PRIVATE LIMITED', 'Ayana Renewable Power Six Private Limited',
                      'ADANI SOLAR ENERGY JAISALMER TWO PRIVATE LIMITED(Project-2)', 'JSW RENEW ENERGY TWO LIMITED',
                      'India Power Corporation Limited', 'B L A POWER PRIVATE LIMITED',
                      'Lloyds Metals And Energy Limited', 'SHREE CEMENT LIMITED TPS', 'MPSEZ Utilities Limited',
                      'ReNew Surya Ravi Private Limited', 'SHREE CEMENT LIMITED CPP',
                      'JHARKHAND BIJLI VITRAN NIGAM LIMITED', 'JSW ENERGY LIMITED, KARNATAKA',
                      'SMC POWER GENERATION LIMITED (UNIT II)', 'SHREE GANESH METALIKS LIMITED',
                      'GMR BAJOLI HOLI HYDROPOWER PRIVATE LIMITED', 'SMC POWER GENERATION LTD',
                      'JSW ISPAT SPECIAL PRODUCTS LIMITED', 'V S LIGNITE POWER PRIVATE LIMITED',
                      'CHHATTISGARH STATE POWER DISTRIBUTION COMPANY LIMITED',
                      'MAGPIE HYDEL CONSTRUCTION OPERATION INDUSTRIES (P) LTD', 'AD HYDRO POWER LIMITED',
                      'MASS N-ERGY PRIVATE LIMITED', 'SUNIL ISPAT AND POWER PRIVATE LIMITED', 'GRIDCO LIMITED',
                      'R.K.M POWERGEN PRIVATE LIMITED', 'BHARAT ALUMINIUM COMPANY LTD',
                      'East Delhi Waste Processing Company Limited', 'KSEB',
                      'RASHMI SPONGE IRON AND POWER INDUSTRIES PRIVATE LIMITED',
                      'Bihar State Power (Holding) Company Limited', 'TATA STEEL LIMITED',
                      'UTTARAKHAND POWER CORPORATION LIMITED', 'The Tata Power Company Limited Haldia Division',
                      'KARCHAM WANGTOO HYDRO ELECTRIC PLANT.', 'JINDAL STAINLESS LIMITED', 'BSPHCL',
                      'INDIAN CANE POWER LTD', 'Shri Prabhulingeshwar Sugars and Chemicals Limited', 'GEM SUGARS LTD',
                      'SHIRAGUPPI SUGAR WORKS LIMITED', 'SANDHYA HYDRO POWER PROJECTS BALARGHA PRIVATE LIMITED',
                      'AGRAWAL SOLAR POWER VENTURES(RAJASTHAN) PRIVATE LIMITED-RRECL REGISTRATION NO. S/1123/2014',
                      'HIRANYAKESHI SAHAKARI SAKKARE KARKHANE NIYAMIT', 'DAVANAGERE SUGAR COMPANY LTD',
                      'NIRANI SUGARS LIMITED', 'Narmada Sugar Pvt. Ltd.', 'UPPCL', 'SIKKIM',
                      'Tata Power Delhi Distribution Limited', 'RAJASTHAN URJA VIKAS NIGAM LIMITED',
                      'Adani Power Limited Stage 2', 'DALMIA CEMENT (BHARAT) LIMITED, ARIYALUR',
                      'BANGLADESH POWER DEVELOPMENT BOARD', 'DVC',
                      'MAGPIE HYDEL CONSTRUCTION OPERATION INDUSTRIES PVT LTD', 'ENERGY DEVELOPMENT COMPANY LIMITED',
                      'Damodar Valley Corporation', 'COASTAL ENERGEN PRIVATE LIMITED',
                      'NATEMS SOLAR POWER PRIVATE LIMITED', 'HARSH NIRMAN INFRAWORLD LLP',
                      'ARUNODAYA TECHSOLAR POWER PROJECTS PRIVATE LIMITED', 'CESC LIMITED',
                      'SAI WARDHA POWER GENERATION PRIVATE LIMITED', 'GIGAPLEX ESTATE PRIVATE LIMITED',
                      'DGEN MEGA POWER PROJECT', 'Vedanta Limited SEZ UNIT, Jharsuguda',
                      'Bansal Wire Industries Limited B-3', 'ArcelorMittal Nippon Steel India Limited', 'MSPL LIMITED',
                      'ACB (INDIA) LIMITED', 'HILLS CEMENT COMPANY LIMITED', 'Mangalore SEZ Limited',
                      'MAHAKAUSHAL SUGAR AND POWER INDUSTRIES LIMITED', 'THE TATA POWER CO LTD', 'GOA SR',
                      'M/s Torrent Power 382.5 MW UNOSUGEN, Kamrej', 'NTPC Solapur', 'TULSYAN NEC LTD',
                      'SHRI BAJRANG POWER AND ISPAT LIMITED TILDA DIVISION', 'VISA STEEL LIMITED',
                      'Adani Power Limited-Raipur TPP', 'WIND FIVE RENERGY LIMITED',
                      'B L A Power Private Limited Unit - 1', 'Dhariwal ISTS', 'DHARIWAL STU OTH',
                      'Sikkim Urja Limited', 'Sorang HEP (Himachal Sorang Power Pvt. Ltd.))',
                      'MASAYA SOLAR ENERGY PRIVATE LIMITED', 'Amp Energy Green Six Private Limited',
                      'ORISSA SPONGE IRON AND STEEL LIMITED', 'KRC INFRASTRUCTURE AND PROJECTS PRIVATE LIMITED',
                      'BALRAMPUR CHINI MILLS LTD', 'KIRLOSKAR FERROUS INDUSTRIES LTD', 'OPG Energy Private Limited',
                      'Ratnagiri Gas & Power Private Limited', 'SURYADEV ALLOYS AND POWER PRIVATE LIMITED',
                      'SATHAVAHANA ISPAT LIMITED', 'ARYAN ISPAT & POWER PVT LTD', 'MANALI SUGARS LIMITED',
                      'IDEAL ENERGY PROJECTS LIMITED', 'VISH WIND INFRASTRUKTURE LLP PHASE I',
                      'LANCO ANPARA POWER LIMITED', 'SEIL Energy India Limited Project II', 'Vandana Global Limited',
                      'DHRUVDESH METASTEEL PVT LTD', 'MAITHAN ISPAT LIMITED', 'MSP METALLICS LIMITED',
                      'OPG Power Generation Private Limited 230KV Unit 2',
                      'ADANI WIND ENERGY KUTCHH FOUR Ltd. Nakhatrana', 'Tata Steel Limited, Meramandali',
                      'Reliance Industries Ltd', 'ADANI HYBRID ENERGY JAISALMER FOUR LIMITED AHW',
                      'SA POWER UTILITIES PRIVATE LIMITED', 'SATISH SUGARS LIMITED', 'SNJ SUGARS AND PRODUCTS LIMITED',
                      'FERRO ALLOYS CORPORATION LTD(POWER PLANT)', 'TPL-Ahmedabad Discom', 'MES DELHI CANTT',
                      'GUJARAT URJA VIKAS NIGAM LIMITED', 'MINDSPACE BUSINESS PARKS PRIVATE LIMITED',
                      'Ambica Steels Limited', 'ENERSHELL ALLOYS AND STEEL PRIVATE LIMITED', 'THE ASSAM TUBES LIMITED',
                      'NIRMAL FIBRES PRIVATE LIMITED', 'TATA STEEL MINING LIMITED', 'BEST Undertaking',
                      'ASIAN HOTELS (NORTH) LIMITED', 'Max Super Speciality Hospital',
                      'STT GLOBAL DATA CENTRES INDIA PRIVATE LIMITED', 'Ginni Filaments Limited (Mathura)',
                      'LODHI PROPERTY COMPANY LIMITED', 'PRIDE HOTELS LIMITED', 'B L KAPUR MEMORIAL HOSPITAL',
                      'BIRD AIRPORT HOTEL PRIVATE LIMITED', 'WAVE HOSPITALITY PRIVATE LIMITED',
                      'EROS GRAND RESORTS AND HOTELS PRIVATE LIMITED', 'EROS RESORTS AND HOTELS PRIVATE LIMITED',
                      'Rimjhim Ispat Limited', 'Novel Sugar Limited', 'Rimjhim Stainless Limited',
                      'VACMET INDIA LIMITED', 'AMBA SHAKTI STEELS LIMITED', 'FERRO ALLOYS CORPORATION LIMITED',
                      'SPARSH INDUSTRIES PRIVATE LIMITED', 'VEDANTA LTD', 'TPL-Surat Discom', 'AEML SEEPZ Limited',
                      'Dadra and Nagar Haveli and Daman and Diu Power Distribution Corporation Lim',
                      'THE DHAMRA PORT COMPANY LIMITED', 'Jindal Steel & Power Limited Barbil Odisha',
                      'Ambashakti Industries Limited', 'DELHI', 'JAI JAGDAMBA METALLOYS LIMITED',
                      'JINDAL QUALITY TUBULAR LIMITED', 'K L RATHI STEELS LTD', 'Rathi Steel and Power Limited',
                      'MAA MAHAMAYA ALLOYS Private Limited Unit-1', 'MAA MAHAMAYA ALLOYS Private Limited Unit-2',
                      'SUMITI ALLOYS PRIVATE LIMITED', 'SHANTI GOPAL CONCAST LIMITED',
                      'JAINARAIN FABTECH PRIVATE LIMITED', 'JPS STEELS PRIVATE LIMITED',
                      'Maruti Suzuki India Limited, Gurgaon', 'ANJANI TILES LIMITED', 'Suven Pharmaceuticals Limited',
                      'KANORIA CHEMICALS AND INDUSTRIES LIMITED', 'VENNAR CERAMICS LIMITED',
                      'VASUDHA PHARMA CHEM LIMITED', 'KUSALAVA INTERNATIONAL LIMITED', 'ZUARI CEMENT LIMITED KADAPA',
                      'ELECTROSTEEL CASTINGS LIMITED TPT 230', 'BHARAT ALUMINIUM COMPANY LTD (Bulk Consumer)',
                      'TEHRI IRON AND STEEL CASTING LIMITED', 'SML Films Ltd', 'Ankur Udyog Ltd.',
                      'RISHIK SPINNING PVT LTD', 'AMAN ROLLING MILLS PRIVATE LIMITED',
                      'SAINT GOBAIN INDIA PRIVATE LIMITED', 'THE MAHABIR JUTE MILLS LTD', 'NIKITA PAPERS LIMITED',
                      'SAINI ALLOYS LIMITED', 'CHL LIMITED', 'ATC Tires Private Limited', 'SUGNA METALS LIMITED',
                      'Agarwal foundries', 'DLF EMPORIO LIMITED', 'DLF PROMENADE LIMITED', 'AMBATTUR INFRA DEVELOPERS',
                      'GASHA STEELS PRIVATE LIMITED', 'Bharti Airtel Ltd-224', 'THIEH INGOTS PVT.LTD',
                      'KAIRALI STEELS & ALLOYS PRIVATE LIMITED', 'PARADEEP PHOSPHATES LTD',
                      'GIFT Power Company Limited', 'South Western Railway', 'Denso Haryana Private Limited',
                      'NESTLE INDIA LIMITED', 'MAX HEALTHCARE INSTITUTE LIMITED', 'Bharti Airtel Ltd-184',
                      'Bharti Airtel Ltd-234', 'DEVKI DEVI FOUNDATION', 'Continental India Private Limited',
                      'SRI KUMARAN STEELS INDIA PRIVATE LIMITED', 'TOYOTA TSUSHO INDIA PRIVATE LIMITED',
                      'JUNIPER HOTELS PRIVATE LIMITED', 'MEENAKSHI ENERGY LIMITED', 'APTRANSCO',
                      'Ganesha Ecosphere Limited', 'Central Railway', 'U P POWER CORPORATION LTD',
                      'GREEN VALLIEY INDUSTRIES LIMITED', 'RNB CEMENTS PRIVATE LIMITED', 'SUNRISE CONCAST LIMITED',
                      'SHYAM CENTURY FERROUS LIMITED', 'DEVPRIYA INDUSTRIES PRIVATE LIMITED',
                      'HARI OM STEEL INDUSTRIES', 'GANGA PAPER MILL', 'CROSSLAY REMEDIES LIMITED',
                      'SEQUENCE FERRO PRIVATE LIMITED', 'SWASTIK GRAINS PRODUCTS PRIVATE LIMITED',
                      'CHIEF ELECTRICAL ENGINEER', 'DEENDAYAL PORT TRUST', 'NAVA BHARAT VENTURES LTD., Odisha-IPP',
                      'KANCHANJUNGA POWER COMPANY PVT. LTD.', 'OSTRO KANNADA POWER PRIVATE  LIMITED',
                      'ABC Renewable Energy (RJ-01) Private Limited',
                      'CHIDANAND BASAPRABHU KORE SAHAKARI SAKKARE KARKHANE NIYAMIT,CHIKODI',
                      'Ultratech Cement Limited (Unit Sidhi Cement Works)', 'Nandi Sahakari Sakkare Karkhane Niyamit',
                      'Bansal High Carbons Private Limited', 'GRASIM INDUSTRIES LIMITED,CHEMICAL DIVISION ,GANJAM',
                      'JK TYRE & INDUSTRIES LTD HTSC 917', 'RAMAA SHYAMA PAPERS PRIVATE LIMITED',
                      'DALMIA CEMENT (BHARAT) LIMITED, Meghalaya', 'Dalmia Cement (Bharat) Limited, Rajgangpur, Odisha',
                      'ADANI HYBRID ENERGY JAISALMER THREE LIMITED AHS', 'Jamkhandi Sugars Limited (Unit-2)',
                      'SHRI DURGA KHANDSARI SUGAR MILLS', 'Tamil Nadu Electricity Board', 'NTPC Korba Stage I &II',
                      'KUNDAN HYDRO (GANGTOK) PRIVATE LIMITED.  Meyong Chu',
                      'Tadas Wind Energy Private Limited-Karnata', 'NSL Sugars Tungabhadra Limited',
                      'Kundan Hydro (Gangtok)Private Limited, Lower Lagyap (HEP)',
                      'HINDUSTHAN NATIONAL GLASS & INDUSTRIES LTD- HINSLDCD02',
                      'BHAARATHI SPINTEX INDIA PRIVATE LIMITED (HTSC-0350)', 'MS AGARWAL FOUNDRIES PVT LTD',
                      'ADANI HYBRID ENERGY JAISALMER FOUR LIMITED AHS', 'Adani Power Limited Stage-2_STU',
                      'Adani Power Limited - Kawai TPP', 'Adani Power Limited - Raigarh TPP', 'MANGLAM METALS',
                      'vsm weavess india Pvt ltd (HTSC-0388)', 'RENEW SURYA ROSHNI PRIVATE LIMITED Koppal PS',
                      'NSL Sugars Limited (Aland)', 'BALRAMPUR CHINI MILLS LTD. Unit HCM',
                      'INOX AIR PRODUCTS PRIVATE LIMITED-TN', 'Bansal Wire Industries Limited B-5&6',
                      'DIAMOND CEMENT (PROP HEIDELBERGCEMENT INDIA LIMITED)',
                      'ESCORTS HEART INSTITUTE AND RESEARCH CENTRE LIMITED',
                      'Tripura State Electricity Corporation Limited', 'SKS Power Generation Chhattisgarh Limited',
                      'Maharashtra State Electricity Distribution Co Limited', 'JSW RENEW ENERGY LIMITED',
                      'Jamkhandi Sugars Limited (Unit-1)', 'MOTHI SPINNER PRIVATE LIMITED  UNIT III',
                      'Jindal Steel & Power Limited, Angul, Odisha', 'Bongaigaon Thermal Power Station  NTPC',
                      'DHARIWAL INFRASTRUCTURE LIMITED, CTU', 'AMRIT BOTTLERS PRIVATE LIMITED',
                      'Power & Electricity Department Government of Mizoram', 'NTPC Mouda Stage I', 'NTPC Singrauli',
                      'NTPC Farakka stage I', 'DHARIWAL INFRASTRUCTURE LIMITED, STU', 'Hindustan Zinc Limited Debari',
                      'J K CEMENT WORKS ALIGARH', 'NTPC DADRI GAS POWER STATION',
                      'NEPAL ELECTRICITY AUTHORITY TANAKPUR', 'STEEL EXCHANGE INDIA LIMITED VIZIANAGARAM',
                      'NTPC Kawas GPS', 'ARCELORMITTAL NIPPON STEEL INDIA LTD., Paradeep/Orissa',
                      'OPG Power Generation Private Limited 230KV', 'GMR KAMALANGA ENERGY LIMITED-STU',
                      'SHREE RENUKA SUGARS LTD', 'SHREE RENUKA SUGARS LIMITED ATHANI',
                      'SHREE RENUKA SUGARS LIMITED HAVALGA', 'SHREE RENUKA SUGARS LIMITED MUNOLI',
                      'SHAMLI STEELS PVT LTD', 'SHAHI EXPORTS PRIVATE LIMITED GHAZIABAD',
                      'ARIA HOTELS AND CONSULTANCY SERVICES PRIVATE LIMITED (JW MARRIOT, AEROCITY)',
                      'ELECTROSTEEL CASTINGS LIMITED TPT 2547', 'SAINT - GOBAIN INDIA PRIVATE LIMITED.',
                      'AVADH ALLOYS P LTD', 'Saint-Gobain India Private Limited HTSC 499', 'ORIENT BELL LIMITED I',
                      'ORIENT BELL LIMITED.', 'Agni Steels Private Limited', 'GUHAN TEXTILES MILLS PVT LTD',
                      'Parani Spinning Mills Pvt Ltd', 'Sundaram Clayton ltd HTSC 1514',
                      'Sundaram Clayton Ltd  HTSC 903', 'Sundaram Clayton Ltd HTSC 1290',
                      'Rohini Textile Industry Pvt Ltd', 'KOTHARI FERMENTATION AND BIOCHEM LIMITED',
                      'UltraTech cement Limited (HT-0053)', 'ACC LIMITED, HP', 'M/s Ultra Tech Cement Ltd.',
                      'ORCHID PHARMA LIMITED', 'Ashok Leyland Limited (Foundry division)',
                      'ASHOK LEYLAND LIMITED FOUNDRY DIVISION 1347', 'Prime Gold International Limited',
                      'JR METAL CHENNAI LIMITED HTSC 1923', 'ASHOK LEYLAND LIMITED FOUNDRY DIVISION 1072',
                      'Reliance Industries Limited Vadodara', 'STEEL AUTHORITY OF INDIA LTD',
                      'HINDALCO INDUSTRIES LIMITED- HINSLDCD04', 'Dalmia Cement (Bharat) Ltd. Kadapa , AP',
                      'BALAJI MEDICAL AND DIAGNOSTIC RESEARCH CENTRE', 'Shri Jagannath Steels & Power Ltd',
                      'Shyam Metalics & Energy Ltd., Sambalpur', 'Anandeshwar Industries Private  Limited',
                      'Jammu and Kashmir Power Corporation Ltd.', 'HeidelbergCement India Limited-MP',
                      'NTPC AURAIYA GPS', 'VISHWARAJ SUGAR INDUSTRIES LIMITED',
                      'THE RAJARATNA MILLS PRIVATE LIMITED-HT0006', 'THE RAJARATNA MILLS PRIVATE LIMITED-HT0091',
                      'SHREE SHAILJA IRON AND STEELS PRIVATE LIMITED', 'THE ANDHRA PETROCHEMICALS LIMITED',
                      'GAYATRI POWER PRIVATE LIMITED', 'NTPC AURAIYA  GPS RLNG', 'GMR KAMALANGA ENERGY LTD-CTU',
                      'TAJ SATS AIR CATERING LIMITED', 'KANSAI NEROLAC PAINTS LIMITED',
                      'Shri Mahavir Ferro Alloys Pvt. Limited', 'TATA MOTORS LIMITED,PANTNAGAR',
                      'TRN ENERGY PRIVATE LIMITED', 'WBSETCL', 'NIDAR UTILITIES PANVEL LLP', 'NTPC ANTA GPS',
                      'Sri Jayavilas Subbaraj Spinning Mills Private Limited', 'ASAHI INDIA GLASS LIMITED-TN HT-0424',
                      'jeevaka industries (p) ltd', 'GMR Warora Energy Limited', 'A A Energy Private Limited',
                      'M.P. POWER MANAGEMENT COMPANY LIMITED', 'RENEW SURYA ROSHNI PRIVATE LIMITED Koppal PS_Infirm',
                      'SRG Apparels Limited', 'ESSAR POWER GUJARAT LIMITED', 'Doyang HPS, NEEPCO', 'NTPP BRBCL',
                      'KAMENG HYDRO POWER STATION', 'TPTCL(DAGACHHU HYDRO POWER PLANT, BHUTAN)',
                      'NTPC SOLAPUR SOLAR PV Station', 'AARTI STEELS LTD', 'MSEDCL DHARNI', 'Atul Ltd',
                      'Ramagundam Floating solar', 'ALTILIUM VENTI PRIVATE LIMITED', 'HPCL MITTAL PIPELINES LIMITED',
                      'GSECL DGBPS 1', 'BHUBANESHWAR POWER PRIVATE LIMITED.', 'RGPPL MSEB',
                      'AMPLUS SOLAR SHAKTI PRIVATE LIMITED', 'Caplin Steriles Limited', 'HP',
                      'Arvind Ltd (Division Arvind Intex Point 2)', 'MAGPIE HYDEL CONST OPERATIONS PVT LTD',
                      'JORETHANG LOOP HEP, DANS ENERGY PRIVATE LIMITED', 'Tata Steel Limited Ferro Alloys Plant Joda',
                      'LR Energy (Unit of Roop Ram Industries Pvt Ltd)', 'M/s Tata Steel Ltd, FAP, Bamnipal',
                      'ESSAR VIZAG TERMINALS LIMITED', 'UTTARAKHAND', 'ITC Limited PSPD Bollaram',
                      'NTPC Jhanor Gandhar GPS', 'NTPC Sipat Stage II', 'NTPC KOLDAM',
                      'Tashiding HEP, Shiga Energy Private Limited', 'ACC LIMITED Bargarh Cement Works',
                      'JSW Steel Limited GOAR', 'GREEN INFRA CLEAN WIND POWER LTD',
                      'Malana II (Everest Power Private Limited)', 'TEESTA V POWER STATION',
                      'AGARTALA GAS BASED POWER STATION', 'AMPLUS RJ SOLAR Pvt. Ltd',
                      'CALCOM CEMENT INDIA LIMITED,UMRANGSO', 'NTPC Kawas Solar PV',
                      'Bihar Cement Plant (A Unit of Shree Cement Ltd)', 'DNHDDPDCL',
                      'BRIJBIHARI CONCAST PRIVATE LIMITED', 'ANY seller - WR Region', 'MPSEB Beneficiary',
                      'LIKHU-iV NEA', 'Amba Shakti Steels Limited Rolling Division',
                      'Dadri Cement Works (A unit of Ultratech Cement Limited)', 'Varrsana Ispat Ltd. Varsana',
                      'INDIAN RAILWAYS GUJARAT', 'THE INDIAN HOTELS COMPANY LTD, DWARKA, NEW DELHI',
                      'VODAFONE IDEA LIMITED, Udyog Nagar',
                      'HYACINTH HOTELS PRIVATE LIMITED (LEMON TREE, AEROCITY, NEW DELHI)', 'CHANDIGARH',
                      'TEHRI IRON & STEEL INDUSTRIES', 'ZUARI CEMENT LIMITED CPP MELLACHERUVU', 'TPCL_U7 RLNG',
                      'GHCL LIMITED HTSC 3', 'MANTORA OIL PRODUCTS PRIVATE LIMITED',
                      'AMARJOTHI SPINNING MILLS LIMITED HTSC 036', 'PRECOT LIMITED',
                      'Ultratech Cement Limited (Unit - Sikandrabad Cement Works)', 'Grasim Industries Limited.',
                      'Tanda Cement Works (A unit of Ultratech Cement Limited)', 'BHARTI AIRTEL LIMITED (Moradabad)',
                      'Ultratech Cement Limited (Unit Aligarh Cement Works)', 'UNISON HOTELS PRIVATE LIMITED',
                      'Vedanta Ltd. - CPP, (9 X 135MW), Jharsuguda', 'South Eastern Railway',
                      'KAJARIA CERAMICS LIMITED', 'VACMET INDIA LIMITED UNIT-3', 'NEA - UP STU', 'NTPC Dadri Stage I',
                      'CENTRAL PARK INFRASTRUCTURE DEVLOPMENT PRIVATE LIMITED', 'DAUJI ISPAT PRIVATE LIMITED',
                      'RAJASTHAN', 'KM Power Pvt Ltd', 'Nani Virani Wind Energy Private Limited',
                      'SKJ POWER PROJECTS PRIVATE LIMITED', 'RNS POWER LIMITED', 'NTPC AURAIYA GPS LF',
                      'The Ugar Sugar Works Limited, Belagavi (Unit-1)',
                      'SARVOTTAM ROLLING MILLS PRIVATE LIMITED UNIT I',
                      'STEEL AUTHORITY OF INDIA LIMITED,ROURKELA STEEL PLANT',
                      'THE TRAVANCORE COCHIN CHEMICALS LIMITED', 'RITVIK STEEL PRIVATE LIMITED',
                      'GINNI FILAMENTS LIMITED-GUJ', 'ANRAK ALUMINIUM LIMITED',
                      'Indian sugar Manufacturing Company Limited', 'Ayana Renewable Power Three Private Limited',
                      'ESSARMPL', 'JAYDEEP COTTON FIBRES PRIVATE LIMITED', 'L K Power Corporation Limited',
                      'ORIENT BOARD AND PAPER MILLS PRIVATE LIMITED', 'DALMIA CEMENT (BHARAT) LIMITED (RCW)',
                      'DHARANI TEXTILES PRIVATE LIMITED HTSC-0135', 'SHREE SIDHBALI STEELS PRIVATE LIMITED',
                      'ATC LIMITED', 'Renew Sandur Green Energy Private Limited Solar', 'JSW ENERGY LIMITED-MH',
                      'Soubhagya Laxmi Sugars Private Limited', '3F INDUSTRIES LIMITED', 'SVR SPINNING MILLS PVT LTD',
                      'AGARWAL FERRO METALLIC PRIVATE LIMITED', 'VEHLNA STEELS AND ALLOYS PRIVATE LIMITED',
                      'ITC Limited Dairy Plant', 'LAXMIPATI BALAJI SUPPLY CHAIN MANAGEMENT LIMITED',
                      'Philips carbon black limited', 'G I POWER CORPORATION LTD.',
                      'HEG LIMITED Tawa Hydro Electric Power Plant',
                      'LINCOLN ELECTRIC COMPANY (INDIA) PRIVATE LIMITED HTSC 701.', 'THE ANDHRA SUGARS LIMITED',
                      'K D IRON AND STEEL CO', 'SALAL POWER STATION',
                      'EON KHARADI INFRASTRUCTURE PRIVATE LIMITED, Phase -2',
                      'AGRAWAL SOLAR POWER VENTURES(RAJASTHAN) PRIVATE LIMITED-RRECL REGISTRATION NO. S/1100/2014',
                      'EON KHARADI INFRASTRUCTURE PRIVATE LIMITED, Phase -1', 'GRETA ENERGY LIMITED',
                      'INDIA GLYCOLS LTD', 'PRISM JOHNSON LIMITED (Cement Division- Unit II)',
                      'SD International Private Limited (BL-12)', 'Birla Textile mills Baddi', 'B R METALLICS',
                      'NTPC NOKHRA Solar PV', 'CAVENDISH INDUSTRIES LIMITED', 'S M S SMELTERS LTD',
                      'APL HEALTHCARE LTD', 'SANGAM MILK PRODUCER COMPANY LIMITED..', 'E I D PARRY, NELLIKUPPAM',
                      'IND SYNERGY LIMITED', 'NEKKANTI MEGA FOOD PARK PRIVATE LIMITED',
                      'NAVA BHARAT VENTURES LIMITED (Odisha CPP)', 'RADIANCE KA SUNRISE THREE PRIVATE LIMITED',
                      'Shree Cement Limited SURATGARH', 'Mylan Laboratories Limited, unit-2',
                      'H L AGRO PRODUCTS PRIVATE LIMITED', 'Vish Wind Infrastrukture LLP Phase III',
                      'WEST CENTRAL RAILWAY', 'A ONE ISPAT PRIVATE LIMITED',
                      'SRI LAKSHMI NARASIMHA SPINNING MILLS India PVT LTD', 'NTPC Ettayapuram Solar PV',
                      'Torrent Power 1147.5 Mw Sugen Ccpp Collective',
                      'Oil and Natural Gas Corporation Limited - Hazira', 'MOTHI SPINNER PRIVATE LIMITED UNIT IV',
                      'HeidelbergCement India Limited-Karnataka',
                      'New Bihar Cement Plant (A Unit of Shree Cement Limited)',
                      'ALL INDIA SOCIETY FOR HEALTH AID EDUUCATION & RESEARCH (A.S.H.A)',
                      'UP Grinding Unit (A Unit of Shree Cement Limited)', 'AIA Engineering Limited -Unit 12',
                      'NTPC JhanorGandhar GPS RLNG', 'ADANI ENNORE CONTAINER TERMINAL PRIVATE LIMITED',
                      'GOYAL MG GASES P LTD', 'Woco Tech Elastomere Noida Limited',
                      'LAKSHMI MACHINE WORKS LIMITED - FOUNDRY AND MACHINE SHOP',
                      'GUJARMAL MODI HOSPITAL AND RESEARCH CENTRE FOR MEDICAL SCIENCES', 'GOA Beneficiary',
                      'SARDA METALS & ALLOYS LIMITED', 'SHAKTI KRAFTS & TISSUES',
                      'P & R ENGINEERING SERVICES PRIVATE LIMITED.',
                      'NEW TIRUPUR AREA DEVELOPMENT CORPORATION LIMITED_HTSC 190',
                      'HINDALCO Industries Ltd.(Unit: Aditya Aluminium),Lapanga,Odisha',
                      'Sudhan Spinning Mills Private limited, HTSC: 102', 'BANK NOTE PAPER MILL INDIA PRIVATE LIMITED',
                      'Shilpa Medicare Limited 0.6MW', 'DUGGAR FIBER PVT LTD', 'Juhi Alloys Limited',
                      'Ultratech Cement Limited, Unit - Jhajjar Cement Works, Jharli', 'Malabar Cements Limited',
                      'RELIANCE INDUSTRIES LIMITED-BARABANKI MANUFACTURING DIVISION', 'Janki corp Limited',
                      'SUPRIYA SPINNING MILLS PRIVATE LIMITED', 'Balaji Wires Private Limited',
                      'SATYAM ISPAT (NORTH EAST) LIMITED', 'M/S Calcom Cement India Ltd Sankardev Nagar',
                      'PUNJAB GENERAL INDUSTRIES PRIVATE LIMITED',
                      'DMRC LTD  THROUGH CONCESSIONAIRE M/S PACIFIC DEVELOPMENT CORPORATION LIMITED',
                      'MUZAFFARNAGAR MEDICAL COLLEGE RUN BY FATEH CHAND CHARITABLE TRUST',
                      'Chilime Hydro Power Project NEPAL ELECTRICITY AUTHORITY',
                      'Kabeli B-1 Hydro Power Project NEPAL ELECTRICITY AUTHORITY',
                      'Galwalia Ispat Udyog Private Limited', 'SRI CHAMUNDESWARI SUGARS LIMITED',
                      'ALSTHOM INDUSTRIES LIMITED', 'Shreemahakaal Concast Private Limited', 'DVC RTPS',
                      'SHREE KEDARNATH SUGAR AND AGRO PRODUCTS LIMITED', 'KPTCL', 'NU VISTA LIMITED',
                      'PARAMESU BIOTECH PRIVATE LIMITED', 'ENERSHELL ALLOYS AND STEEL PRIVATE LIMITED UNIT-II',
                      'SARVOTTAM ROLLING MILLS PRIVATE LIMITED UNIT II', 'Agrocel Industries Pvt Ltd Cons.No.31607',
                      'PARTH THREAD PRIVATE LIMITED', 'PALLAVA TEXTILES PRIVATE LIMITED- PALSLDCD14', 'BPCL (99917)',
                      'NTS Power_', 'CHEMPLAST CUDDALORE VINYLS LIMITED', 'RSUPL FTG2', 'DVC DSTPS', 'Canara PCC Poles',
                      'APL Stage 3', 'RCCPL Private Limited-MP', 'THE INDIA CEMENTS LIMITED YERRAGUNTLA',
                      'Nagaland Ben', 'ASSAM GAS BASED POWER STATION', 'AADHI VINAYAGA SPINNERS',
                      'RAS POLYTEX PRIVATE LIMITED', 'Hindustan Coca Cola Beverages Pvt Ltd',
                      'RANGER COTTON MILLS INDIA PVT LTD', 'DR REDDYS LABORATORIES LIMITED unit 1',
                      'Mankameshwar Steels Unit-II Private Limited', 'cargill india private limited', 'GOEL ASSOCIATES',
                      'ARUN SPINNING MILLS (P) LTD', 'SL LUMAX LIMITED', 'GOLD PLUS GLASS INDUSTRY LIMITED',
                      'MSP SPONGE IRON LIMITED', 'CHENNAI PETROLEUM CORPORATION LIMITED', 'EMAMI AGROTECH LIMITED',
                      'GROWELFEEDS PRIVATE LIMITED', 'TOPWORTH URJA AND METALS LIMITED', 'BST Textile Mills Pvt Ltd',
                      'Sundram Fasteners Limited', 'The Ramaraju Surgical Cotton Mills Limited',
                      'GLAND PHARMA LIMITED MCL766', 'POLYPLEX CORPORATION LIMITED', 'RAMESH STEELS',
                      'EASTMAN INTERNATIONAL, 15MW', 'RPP  LIMITED', 'TATA MOTORS LIMITED, LKO',
                      'PVSR STEEL AND POWER PRIVATE LIMITED', 'SREE RENGARAJ ISPAT INDUSTRIES PVT LTD',
                      'RELIANCE CHEMOTEX INDUSTRIES LIMITED', 'Calpro Specialities Private Limited',
                      'Reliance Jio Infocomm Ltd', 'SUNDRAM FASTENERS LIMITED- SUNSLDCD03', 'MSPL LTD',
                      'SREE SIDDAGANGA MATH', 'NPCIL KAKRAPAR ATOMIC POWER STATION UNITS 3 & 4', 'Tripura Ben',
                      'SOLAIRE SURYA URJA PRIVATE LIMITED PLOT 10', 'Rongnichu HEP', 'Meghalaya Ben', 'DVC BTPS',
                      'Tehri HPP', 'SURYAANS PAPER', 'SHREE SHYAM ISPAT', 'SRI MAHAVIR STEEL',
                      'Jindal Steel & Power Ltd , DCPP', 'STEEL STRIPS WHEELS LTD', 'SHRIRAM FOUNDRY PRIVATE LIMITED',
                      'U.S.M.ALLOYS & CASTINGS PVT LTD', 'Hindustan Organic Chemicals Limited',
                      'ITC LIMITED DEVANAHALLI', 'SREE KADERI AMBAL MILLS PRIVATE LIMITED HTSC 75',
                      'J.K. FENNER (INDIA) LIMITED SGR034', 'Shree Cement Limited JOBNER', 'AMRIT CEMENT LTD',
                      'RSEJ3PL FTG2', 'TPSL Banderwala SECI 100_INF', 'KANTI BIJLEE UTPADAN NIGAM LIMITED',
                      'NTPC KUDGI', 'AP41PL BHDL', 'ARP1PL BKN', 'Manali Petrochemicals Limited 1449 -Plant 1',
                      'PENNA CEMENT, TALARICHERUVU (ATP230)', 'NEA Nepal Upper Dordi A Hydropower Project',
                      'ITC LTD Kidderpore', 'RMG POLYVINYL INDIA LIMITED', 'JUBILANT INGREVIA LTD', 'RGPPL IR',
                      'SMARTCHEM TECHNOLOGIES LIMITED SKL092', 'RBA EXPORTS PVT LTD', 'APOLLO TYRES LIMITED  TPT2568',
                      'Adani Power Limited Stage 3', 'Adani Power Limited Stage 1', 'BLA Power Private Limited Unit-2',
                      'SMC POWER GENERATION Ltd (UNIT-II)', 'Adani Power Limited', 'ADANI POWER LIMITED STAGE 3',
                      'NTPC Farakka Stage 3', 'Orient Bell Limited Unit 1', 'Orient Bell Limited Unit 2',
                      'SUGEN MEGA POWER PROJECT', 'ADANI POWER LIMITED STAGE 3', 'SKS POWER GENERATION LTD',
                      'ReNew Energy Markets Private Limited', 'Viraj Steel And Energy Private Limited',
                      'Apraava Energy Private Limited']

uttarakhand_uksldc_generator = {'AB renewable energy pvt ltd': '1345', 'Ballupur solar power project pvt ltd': '1365',
                                'Bazpur Solar Plant': '1236', 'Bhagwanpur solar projects private ltd': '1335',
                                'Bhilangana Hydro Power Ltd.': '1229',
                                'Bindookharak solar power project pvt ltd': '1333',
                                'Canal Bank Solar PV Plant 7': '1349', 'Canal Bank Solar PV Plant 7.5': '1351',
                                'Chibro Power House': '1022', 'Chilla Power House': '1002',
                                'Chudiala solar power project pvt ltd': '1367',
                                'Devishi renewal energy pvt ltd': '1357', 'Devishi solar power': '1359',
                                'Dhakrani Power House': '1016', 'Dhalipur Power House': '1018',
                                'Dharasu Power House': '1012', 'Electryone Power Private Limited': '1329',
                                'Eminent solar power pvt ltd': '1361', 'Gaderpur Solar Plant': '1238',
                                'Gama Infroprop (p) Ltd.': '1231', 'Haridwar Solar Plant': '1287',
                                'Haridwar solar project pvt ltd 1': '1371', 'Haridwar solar project pvt ltd 2': '1373',
                                'Khatima Power House': '1026', 'Khodri Power House': '1024',
                                'Kulhal Power House': '1020', 'Laksar Solar Plant': '1240',
                                'M/s Kranti Infra Power Pvt Ltd 1.4': '1323',
                                'M/s Kranti Infra Power Pvt Ltd 4.3': '1321', 'M/s Sunlayer Energy Pvt Ltd': '1302',
                                'Madhav renewables pvt ltd': '1355', 'Maneri Power House': '1014',
                                'Mohammadpur Power House': '1006', 'Pathri Power House': '1003',
                                'PL solar renewable ltd': '1341', 'PL Sunrays power limited': '1337',
                                'PL surya vidyut ltd': '1339', 'Pochampad Construction Company Pvt Ltd': '1325',
                                'Ramganga Power House': '1028', 'Sakhumbhari Solar Plant': '1242',
                                'Shakumbhari solar power project pvt ltd': '1369', 'Sravanthi Energy (p) Ltd.': '1234',
                                'Sunheti solar power proj pvt ltd': '1343', 'Sunlayer energy pvt ltd plant-II': '1347',
                                'Sunworld energy pvt ltd': '1363', 'Svarog Global Power Pvt Ltd 1': '1319',
                                'Svarog Global Power Pvt Ltd 7': '1317', 'Svarog Global Power Pvt Ltd 7.5': '1315',
                                'Technique Solaire Invest-l India Pvt Ltd': '1331', 'Uttam Sugar Mills Ltd': '1353',
                                'Vyasi Hydro Power Plant': '1304'}

uttarakhand_uksldc_oa = {'Alfa Ingot Private Limited': '1075', 'Alpla India Private Limited': '1054',
                         'Alps Industries Ltd Plot 1A': '1093', 'Ambuja Cement Ltd': '1089',
                         'Anchor Ispat Pvt Ltd': '1034', 'Ashok Leyland Ltd': '1031',
                         'Bahl Paper Mills  Limited': '1289', 'Balaji Action Buildwell': '1074',
                         'Britannia Industries Limited': '1115', 'Bst Textile Mills Pvt Limited': '1042',
                         'Cavendish Industries Limited': '1032', 'Cosmos Ferrous Pvt. Ltd': '1310',
                         'D S Rolling Mills Private Limited': '1069', 'Dabur India Limited Unit-2': '1040',
                         'Ester Industries Ltd': '1039', 'Flexituff International Ltd.': '1007',
                         'Galwalia Ispat Udyog Pvt. Ltd': '1050', 'Gama Infroprop (p) Ltd.': '1231',
                         'Ganesha Ecosphere Limited': '1073', 'Gold Plus Glass Industry Limited': '1114',
                         'Greenpanel Industries Ltd Unit 2': '1101', 'Hero Motocorp Limited': '1079',
                         'Hindusthan National Glass & Industries Ltd': '1081', 'India Glycols Ltd. Dehradun': '1005',
                         'India Glycols Ltd. Kashipur': '1004', 'Indian Toners And Developers Limited': '1059',
                         'Innovative Textiles Limited': '1096', 'Itc Limited': '1047',
                         'Itc Limited Ppd Division': '1046', 'Jmv Ispat Private Limited': '1067',
                         'Kama Metal & Alloys Pvt Ltd': '1102', 'Kashi Vishwanath Steels Pvt Ltd': '1108',
                         'Katyayini Paper Mills Pvt Ltd': '1095', 'Kie Engineering Pvt Ltd': '1065',
                         'La Opala Rg Limited': '1060', 'Linde India Limited': '1094',
                         'M/S Air Liquid North Indi Pvt. Ltd': '1064', 'M/S Asahi India Glass Limited': '1063',
                         'M/s Brijbihari Concast Private Limited': '1313', 'M/S Endurance Technologies Limited': '1092',
                         'M/S Hindustan Lever Limited': '1057', 'M/S Hindustan Unilever Limited': '1062',
                         'M/S Hindustan Zinc Limited': '1087', 'M/S Kashi Vishvanath Textile Mill Ltd.': '1038',
                         'M/S Mahabal Auto Ancillaries Pvt. Ltd': '1107', 'M/s Manjushree Technopack Ltd': '1295',
                         'M/S Munjal Showa Limited': '1120', 'M/S Nestle India Limited': '1037',
                         'M/S Patanjali Food & Herbal Park Pvt. Ltd': '1058', 'M/S Perfetti Van Melle Pvt. Ltd': '1066',
                         'M/S Pioneer Polyleathers  Limited': '1118', 'M/S Pure & Cure Healthcare Pvt. Ltd': '1056',
                         'M/S Radico Khaitan Limited': '1077', 'M/S Roquette Riddhi Siddhi Pvt. Ltd': '1072',
                         'M/S Sansera Engineering Pvt. Ltd': '1052', 'M/S Shivam Autotech Limited': '1119',
                         'M/S Shree Grinding Unit Laksar': '1048', 'M/S Srf Limited': '1043',
                         'M/S Srf Limited Unit-2': '1084', 'M/S Surya Roshni Limited': '1106',
                         'M/s TPAC Packaging India Pvt Ltd': '1033', 'M/S Umashakti Steels Pvt. Ltd': '1104',
                         'M/S Up Bone Mills Pvt. Ltd': '1098', 'M/s Uttaranchal Ispat Pvt Ltd': '1292',
                         'Magic Wires Pvt Ltd': '1327', 'Mahalaxmi Polypack Pvt Ltd': '1116',
                         'Mantri Metallics Pvt Ltd': '1086', 'Motiram Rolling Mills Ltd': '1110',
                         'Mutual Automotive Private Limited': '1071', 'Naini Papers Limited': '1045',
                         'Naini Tissues Limited': '1044', 'Pashupati Laminators Private Limited': '1049',
                         'Pashupati Polytex Private Limited': '1041', 'Penta Latex': '1030',
                         'Polyplex Corporation Limited Bazpur': '1070', 'Polyplex Corporation Limited Khatima': '1053',
                         'Prime Industries': '1068', 'Prince Pipes And Fittings Ltd': '1113',
                         'Radiant Bar Limited': '1097', 'Rana Industries': '1076', 'Rana Ispat Pvt Ltd': '1300',
                         'Rockman Industries Limited': '1082', 'Roop Polymers Ltd': '1078',
                         'Rukmini Iron Pvt Ltd': '1085', 'Sahota Papers Limited': '1061',
                         'Shree Aekanya Steels LLP': '1100', 'Shree Sidhbali Industries Ltd': '1111',
                         'Shriram Foundry Pvt Ltd': '1083', 'Sravanthi Energy (p) Ltd.': '1234',
                         'Sundram Fasteners Limited': '1036', 'Suryodaya Textiles Private Limited': '1051',
                         'Tata Motors Limited': '1091', 'Tcpl Packaging Limited': '1112',
                         'Tehri Iron & Steel Industries': '1099', 'Tidc India': '1121',
                         'Time Technoplast Limited Unit- I': '1088', 'Time Technoplast Limited Unit-II': '1090',
                         'Tvs Srichakra Limited': '1055', 'Ultratech Cement Limited Unit: Roorkee Cement Works': '1105',
                         'Uttaranchal Steels Pvt Ltd': '1109', 'Vimlesh Coils & Conductors': '1103',
                         'Vishvakarma Paper & Boards Ltd': '1117', 'Vista Furnishing Limited': '1080',
                         'Wipro Enterprises Private Limited': '1035'}
