tam_data_mapping = {"Adani Electricity Mumbai Limited": "Adani Electricity Mumbai Limited",
                    "Andhra Pradesh Central Power Distribution Corp Ltd": "Andhra Pradesh Central Power Distribution Corporation Limited",
                    "Andhra Pradesh Central Power Distribution Corp.ltd": "Andhra Pradesh Central Power Distribution Corporation Limited",
                    "APDCL (Assam)": "ASSAM POWER DISTRIBUTION COMPANY LIMITED",
                    "ArcelorMittal Nippon Steel India Limited": "ArcelorMittal Nippon Steel India Limited",
                    "Bharat Aluminium Company Limited": "BHARAT ALUMINIUM COMPANY LTD",
                    "Bharat Aluminum Company ltd (Bulk consumer)": "BHARAT ALUMINIUM COMPANY LTD (Bulk Consumer)",
                    "BHARAT ALUMINIUM COMPANY LTD (Bulk Consumer)": "BHARAT ALUMINIUM COMPANY LTD (Bulk Consumer)",
                    "Bihar State Power Holding Company Ltd Patna": "Bihar State Power (Holding) Company Limited",
                    "Bihar State Power Holding Company Limited": "Bihar State Power (Holding) Company Limited",
                    "Bihar State Power Holding Company": "Bihar State Power (Holding) Company Limited",
                    "BSES Yamuna Power Limited (BYPL)": "BSES Yamuna Power Limited",
                    "C.S.P.DISTRIBUTION_CO._LTD.": "CHHATTISGARH STATE POWER DISTRIBUTION COMPANY LIMITED",
                    "Central Railways_Maharashtra": "Central Railway",  # "Central Railway": "Central Railway",
                    "CESC": "CESC LIMITED", "CESC Limited": "CESC LIMITED",
                    "CSP Distribution  Company ltd": "CHHATTISGARH STATE POWER DISTRIBUTION COMPANY LIMITED",
                    "CSP Distribution Co Ltd": "CHHATTISGARH STATE POWER DISTRIBUTION COMPANY LIMITED",
                    "Dadra and Nagar Haveli and Daman and Diu Power Distribution Corporation Limited": "Dadra and Nagar Haveli and Daman and Diu Power Distribution Corporation Lim",
                    "DNH Power Distribution Corporation Ltd": "DNH Beneficiary",  # "DVC": "DVC",
                    "Electricity Department_Government of Goa WR": "Electricity Department, GOA_WR",
                    "Gift Power Company Ltd": "GIFT Power Company Limited",
                    "Gigaplex Estate Private Limited": "GIGAPLEX ESTATE PRIVATE LIMITED",
                    "Gigaplex Estate pvt ltd": "GIGAPLEX ESTATE PRIVATE LIMITED", "GRIDCO": "GRIDCO LIMITED",
                    # "GRIDCO LIMITED": "GRIDCO LIMITED",
                    "GUJARAT URJA VIKAS NIGAM LTD": "GUJARAT URJA VIKAS NIGAM LIMITED",
                    "GUVNL": "GUJARAT URJA VIKAS NIGAM LIMITED",
                    "Gujarat Urja Vikas Nigam Limited": "GUJARAT URJA VIKAS NIGAM LIMITED",
                    "Himachal Pradesh State Electricity Board Ltd": "HIMACHAL PRADESH STATE ELECTRICITY BOARD LIMITED",
                    "HPSEB": "HIMACHAL PRADESH STATE ELECTRICITY BOARD LIMITED",
                    "Kerala State Electricity Board (KSEB)": "KERALA STATE ELECTRICITY BOARD LIMITED",
                    "Kerala State Electricity Board Limited": "KERALA STATE ELECTRICITY BOARD  LIMITED",
                    "KRC Infrastructure and Projects Pvt Ltd": "KRC INFRASTRUCTURE AND PROJECTS PRIVATE LIMITED",
                    "KRC Infrastructure & Project Pvt Ltd": "KRC INFRASTRUCTURE AND PROJECTS PRIVATE LIMITED",
                    "Maharashtra State Electricity Distribution Company Limited (MSEDCL)": "Maharashtra State Electricity Distribution Co Limited",
                    "MSEDCL": "Maharashtra State Electricity Distribution Co Limited",
                    "Mind Space business Park pvt ltd": "MINDSPACE BUSINESS PARKS PRIVATE LIMITED",
                    "Mindspace Business Parks Pvt Ltd": "MINDSPACE BUSINESS PARKS PRIVATE LIMITED",
                    "Mindspace Business Parks Private Limited": "MINDSPACE BUSINESS PARKS PRIVATE LIMITED",
                    'New Delhi Municipal Council': "New Delhi Municipal Council",
                    "New_Delhi_Municipal council_NDMC": "New Delhi Municipal Council",
                    "Noida Power Company Limited": "Noida Power Company limited",
                    "Noida power Company ltd": "Noida Power Company limited",
                    "Noida Power Company.Ltd": "Noida Power Company limited", "NPCL": "Noida Power Company limited",
                    "North Western Railway": "North Western Railway", "Northern  Railway  UP": "Northern Railway UP",
                    "Northern  Railway UP": "Northern Railway UP", "Northern Railway UP": "Northern Railway UP",
                    "NORTHERN RAILWAY UP": "Northern Railway UP", "Northern Railway": "Northern Railway",
                    "Northern Railway Haryana": "Northern Railway-Haryana",
                    "Power Company of Karnataka Limited -PCKL": "Power Company of Karnataka Ltd",
                    "PCKL": "Power Company of Karnataka Ltd",
                    # "Power Company of Karnataka Ltd": "Power Company of Karnataka Ltd",
                    "Punjab State Power Corporation Ltd (PTC)": "Punjab State Power Corporation Limited",
                    "Rajasthan Urja Vikas Nigam Ltd (RUVNL)": "RAJASTHAN URJA VIKAS NIGAM LIMITED",
                    "Rajasthan Urja Vikas Nigam Ltd": "RAJASTHAN URJA VIKAS NIGAM LIMITED",
                    "Rajasthan Urja Vikas Nigam .ltd": "RAJASTHAN URJA VIKAS NIGAM LIMITED",
                    "Rajasthan Urja Vikas Nigam Limited": "RAJASTHAN URJA VIKAS NIGAM LIMITED",
                    "RUVNL": "RAJASTHAN URJA VIKAS NIGAM LIMITED", "South Western Railway": "South Western Railway",
                    "South  Western  Railway": "South Western Railway",
                    "South  Western Railway": "South Western Railway",
                    "Southern Power Distribution Company of Telangana Limited": "SOUTHERN POWER DISTRIBUTION COMPANY OF TELANGANA LIMITED",
                    "Southern Power Distribution Company of Telangana Limited (TSSPDCL)": "SOUTHERN POWER DISTRIBUTION COMPANY OF TELANGANA LIMITED",
                    "Tamilnadu Generation and Distribution Corporation Limited": "TAMILNADU GENERATION AND DISTRIBUTION CORPORATION LIMITED",
                    "Tamil Nadu  Generation and Distribution Corporation Limited": "TAMILNADU GENERATION AND DISTRIBUTION CORPORATION LIMITED",
                    "Tamilnadu Generation and Dist. Corp. Ltd TANGEDCO": "TAMILNADU GENERATION AND DISTRIBUTION CORPORATION LIMITED",
                    "TANGEDCO": "TAMILNADU GENERATION AND DISTRIBUTION CORPORATION LIMITED",
                    # "Torrent Power Ahmedabad": "Torrent Power Ahmedabad",
                    "TORRENT POWER LIMITED - AHMEDABAD DISTRIBUTION": "Torrent Power Ahmedabad",
                    "Torrent Power Limited - Dahej Distribution": "Torrent Power Limited - Dahej",
                    "TORRENT POWER LIMITED - SURAT DISTRIBUTION": "Torrent Power Surat",
                    "Torrent Power Ltd Surat": "Torrent Power Surat",
                    "Torrent Power Limited- Dahej": "Torrent Power Limited - Dahej",
                    "Torrent Power Ltd Dahej": "Torrent Power Limited - Dahej",
                    # "Torrent Power Surat": "Torrent Power Surat",
                    "U P Power Corporation Ltd": "UPPCL", "Uttar Pradesh Power Corporation Ltd (UPPCL)": "UPPCL",
                    "Uttar Pradesh Power Corporation Ltd": "UPPCL",
                    "Uttar Pradesh Power Corporation Limited (UPPCL)": "UPPCL",
                    "Uttarakhand Power Corporation Limited": "UTTARAKHAND POWER CORPORATION LIMITED",
                    "Uttarakhand Power Corporation": "UTTARAKHAND POWER CORPORATION LIMITED",
                    "Uttrakhand Power Corp Ltd": "UTTARAKHAND POWER CORPORATION LIMITED",
                    "Uttrakhand Power Corp.Ltd": "UTTARAKHAND POWER CORPORATION LIMITED",
                    "Vedanta Ltd_SEZ Unit_Jharsuguda": "Vedanta Limited SEZ UNIT, Jharsuguda",
                    "West Bengal State Electricity Distribution Company Limited (WBSEDCL)": "WEST BENGAL STATE ELECTRICITY DISTRIBUTION COMPANY LIMITED",
                    "West Central Railway": "WEST CENTRAL RAILWAY",

                    "Uttarakhand Power Corporation Ltd": "UTTARAKHAND POWER CORPORATION LIMITED",
                    # "Uttarakhand Power Corporation Limited (UPCL)": "UTTARAKHAND POWER CORPORATION LIMITED",
                    "TPL-Ahmedabad Discom": "TPL-Ahmedabad Discom", }

deep_data_mapping = {"JBVNL": "JHARKHAND BIJLI VITRAN NIGAM LIMITED",
                     "CSPDL": "CHHATTISGARH STATE POWER DISTRIBUTION COMPANY LIMITED",
                     "NUPLLP": "NIDAR UTILITIES PANVEL LLP",  # "REMCL": "Railway Energy Management Company Limited",
                     "LBSCML": "LAXMIPATI BALAJI SUPPLY CHAIN MANAGEMENT LIMITED",
                     "RUVNL": "RAJASTHAN URJA VIKAS NIGAM LIMITED", "BSES": "BSES Rajdhani Power Limited",
                     "BYPL": "BSES Yamuna Power Limited", "IPCL": "India Power Corporation Limited",
                     "APPCC": "Andhra Pradesh Power Coordination Committee",
                     "GUVNL": "Gujarat Urja Vikas Nigam Limited", "MSEZL": "Mangalore SEZ Limited",
                     "APDCL": "ASSAM POWER DISTRIBUTION COMPANY LIMITED",
                     # "MPPMCL": "Madhya Pradesh Power Management Company Limited",
                     "PCKL": "Power Company of Karnataka Ltd", "PSPCL": "Punjab State Power Corporation Limited",
                     "EON KHARADI INFRASTRUCTURE PVT LTD": "EON KHARADI INFRASTRUCTURE PRIVATE LIMITED, Phase -2",
                     # "SEZ BIOTECH SERVICES PRIVATE LIMITED": "RAIPUR ENERGEN LIMITED",
                     # "PFC Consulting Limited": "LAXMIPATI BALAJI SUPPLY CHAIN MANAGEMENT LIMITED",
                     # "Sundew Properties Limited": "LAXMIPATI BALAJI SUPPLY CHAIN MANAGEMENT LIMITED",
                     "TAMILNADU ELECTRICITY BOARD": "Tamil Nadu Electricity Board",
                     "Andhra Pradesh Power Co-Ordination Committee (APPCC)": "Andhra Pradesh Power Coordination Committee",
                     "TANGEDCO ltd": "TAMILNADU GENERATION AND DISTRIBUTION CORPORATION LIMITED",
                     # "MADC LTD": "Maharashtra Airport Development Company Limited",
                     # "RELIANCE ENERGY MUMBAI DISCOM": "TPL-Surat Discom",
                     "UPCL": "UTTARAKHAND POWER CORPORATION LIMITED", "KSEBL": "KSEB",
                     "MAHARASHTRA STATE ELECTRICITY CO LTD": "Maharashtra State Electricity Distribution Co Limited",
                     "CESC": "CESC LIMITED",
                     "HARYANA POWER PURCHASE CENTRE(A JOINT FORUM OF UHBVN&DHBVN)": "Haryana Power Purchase Centre",
                     # "AEML": "AEML SEEPZ Limited",
                     # "TPCL": "TPCL_U7 RLNG / The Tata Power Co Ltd (MTPS)",
                     "TAMILNADU GENERATION AND DISTRIBUTION CORPN LTD": "TAMILNADU GENERATION AND DISTRIBUTION CORPORATION LIMITED",
                     "HPSEBL": "HIMACHAL PRADESH STATE ELECTRICITY BOARD LIMITED", "BEST": "BEST Undertaking",
                     "Chandigarh Electricity Department": "CHANDIGARH",
                     "KRC Infrastructure and Projects Pvt Ltd": "KRC INFRASTRUCTURE AND PROJECTS PRIVATE LIMITED",
                     "MP Power Management Company Ltd": "M.P. POWER MANAGEMENT COMPANY LIMITED",
                     "Assam Power Distribution Company Ltd": "ASSAM POWER DISTRIBUTION COMPANY LIMITED",
                     "Torrent Power Limited": "Torrent Power Limited - Dahej",
                     "MPSEZ Utilities Private Limited": "MPSEZ Utilities Limited",
                     "SOUTHERN POWER DISTRIBUTION COMPANY OF TELANGANA LTD": "SOUTHERN POWER DISTRIBUTION COMPANY OF TELANGANA LIMITED",
                     "WEST BENGAL STATE ELECTRICITY DISTRIBUTION COMPANY LIMITED": "WEST BENGAL STATE ELECTRICITY DISTRIBUTION COMPANY LIMITED",
                     "Noida Power Company Limited": "Noida Power Company limited",
                     "JAWAHARLAL NEHRU PORT TRUST": "Jawaharlal Nehru Port Trust",
                     "GUJARAT URJA VIKAS NIGAM LIMITED": "GUJARAT URJA VIKAS NIGAM LIMITED",
                     "TATA POWER DELHI DISTRIBUTION LIMITED": "Tata Power Delhi Distribution Limited",
                     "MINDSPACE BUSINESS PARKS PRIVATE LIMITED": "MINDSPACE BUSINESS PARKS PRIVATE LIMITED",
                     "BSPHCL": "BSPHCL", "NIDP DEVELOPERS PRIVATE LIMITED": "NIDP DEVELOPERS PRIVATE LIMITED",
                     "GRIDCO LIMITED": "GRIDCO LIMITED",
                     "Gigaplex Estate Private Limited": "GIGAPLEX ESTATE PRIVATE LIMITED",
                     'Andhra Pradesh Power Co-Ordination Committee (Andhra Pradesh Power Coordination Committee)': 'Andhra Pradesh Power Coordination Committee'}

deep_tam_mapping = {"Adani Electricity Mumbai Limited": "Adani Electricity Mumbai Limited",
                    "Andhra Pradesh Central Power Distribution Corp Ltd": "Andhra Pradesh Central Power Distribution Corporation Limited",
                    "Andhra Pradesh Central Power Distribution Corp.ltd": "Andhra Pradesh Central Power Distribution Corporation Limited",
                    "APDCL (Assam)": "ASSAM POWER DISTRIBUTION COMPANY LIMITED",
                    "ArcelorMittal Nippon Steel India Limited": "ArcelorMittal Nippon Steel India Limited",
                    "Bharat Aluminium Company Limited": "BHARAT ALUMINIUM COMPANY LTD",
                    "Bharat Aluminum Company ltd (Bulk consumer)": "BHARAT ALUMINIUM COMPANY LTD (Bulk Consumer)",
                    "BHARAT ALUMINIUM COMPANY LTD (Bulk Consumer)": "BHARAT ALUMINIUM COMPANY LTD (Bulk Consumer)",
                    "Bihar State Power Holding Company Ltd Patna": "Bihar State Power (Holding) Company Limited",
                    "Bihar State Power Holding Company Limited": "Bihar State Power (Holding) Company Limited",
                    "Bihar State Power Holding Company": "Bihar State Power (Holding) Company Limited",
                    "BSES Yamuna Power Limited (BYPL)": "BSES Yamuna Power Limited",
                    "C.S.P.DISTRIBUTION_CO._LTD.": "CHHATTISGARH STATE POWER DISTRIBUTION COMPANY LIMITED",
                    "Central Railways_Maharashtra": "Central Railway",  # "Central Railway": "Central Railway",
                    "CESC": "CESC LIMITED", "CESC Limited": "CESC LIMITED",
                    "CSP Distribution  Company ltd": "CHHATTISGARH STATE POWER DISTRIBUTION COMPANY LIMITED",
                    "CSP Distribution Co Ltd": "CHHATTISGARH STATE POWER DISTRIBUTION COMPANY LIMITED",
                    "Dadra and Nagar Haveli and Daman and Diu Power Distribution Corporation Limited": "Dadra and Nagar Haveli and Daman and Diu Power Distribution Corporation Lim",
                    "DNH Power Distribution Corporation Ltd": "DNH Beneficiary",  # "DVC": "DVC",
                    "Electricity Department_Government of Goa WR": "Electricity Department, GOA_WR",
                    "Gift Power Company Ltd": "GIFT Power Company Limited",
                    "Gigaplex Estate Private Limited": "GIGAPLEX ESTATE PRIVATE LIMITED",
                    "Gigaplex Estate pvt ltd": "GIGAPLEX ESTATE PRIVATE LIMITED", "GRIDCO": "GRIDCO LIMITED",
                    # "GRIDCO LIMITED": "GRIDCO LIMITED",
                    "GUJARAT URJA VIKAS NIGAM LTD": "GUJARAT URJA VIKAS NIGAM LIMITED",
                    "GUVNL": "GUJARAT URJA VIKAS NIGAM LIMITED",
                    "Gujarat Urja Vikas Nigam Limited": "GUJARAT URJA VIKAS NIGAM LIMITED",
                    "Himachal Pradesh State Electricity Board Ltd": "HIMACHAL PRADESH STATE ELECTRICITY BOARD LIMITED",
                    "HPSEB": "HIMACHAL PRADESH STATE ELECTRICITY BOARD LIMITED",
                    "Kerala State Electricity Board (KSEB)": "KERALA STATE ELECTRICITY BOARD LIMITED",
                    "Kerala State Electricity Board Limited": "KERALA STATE ELECTRICITY BOARD  LIMITED",
                    "KRC Infrastructure and Projects Pvt Ltd": "KRC INFRASTRUCTURE AND PROJECTS PRIVATE LIMITED",
                    "KRC Infrastructure & Project Pvt Ltd": "KRC INFRASTRUCTURE AND PROJECTS PRIVATE LIMITED",
                    "Maharashtra State Electricity Distribution Company Limited (MSEDCL)": "Maharashtra State Electricity Distribution Co Limited",
                    "MSEDCL": "Maharashtra State Electricity Distribution Co Limited",
                    "Mind Space business Park pvt ltd": "MINDSPACE BUSINESS PARKS PRIVATE LIMITED",
                    "Mindspace Business Parks Pvt Ltd": "MINDSPACE BUSINESS PARKS PRIVATE LIMITED",
                    "Mindspace Business Parks Private Limited": "MINDSPACE BUSINESS PARKS PRIVATE LIMITED",
                    'New Delhi Municipal Council': "New Delhi Municipal Council",
                    "New_Delhi_Municipal council_NDMC": "New Delhi Municipal Council",
                    "Noida Power Company Limited": "Noida Power Company limited",
                    "Noida power Company ltd": "Noida Power Company limited",
                    "Noida Power Company.Ltd": "Noida Power Company limited", "NPCL": "Noida Power Company limited",
                    "North Western Railway": "North Western Railway", "Northern  Railway  UP": "Northern Railway UP",
                    "Northern  Railway UP": "Northern Railway UP", "Northern Railway UP": "Northern Railway UP",
                    "NORTHERN RAILWAY UP": "Northern Railway UP", "Northern Railway": "Northern Railway",
                    "Northern Railway Haryana": "Northern Railway-Haryana",
                    "Power Company of Karnataka Limited -PCKL": "Power Company of Karnataka Ltd",
                    "PCKL": "Power Company of Karnataka Ltd",
                    # "Power Company of Karnataka Ltd": "Power Company of Karnataka Ltd",
                    "Punjab State Power Corporation Ltd (PTC)": "Punjab State Power Corporation Limited",
                    "Rajasthan Urja Vikas Nigam Ltd (RUVNL)": "RAJASTHAN URJA VIKAS NIGAM LIMITED",
                    "Rajasthan Urja Vikas Nigam Ltd": "RAJASTHAN URJA VIKAS NIGAM LIMITED",
                    "Rajasthan Urja Vikas Nigam .ltd": "RAJASTHAN URJA VIKAS NIGAM LIMITED",
                    "Rajasthan Urja Vikas Nigam Limited": "RAJASTHAN URJA VIKAS NIGAM LIMITED",
                    "RUVNL": "RAJASTHAN URJA VIKAS NIGAM LIMITED", "South Western Railway": "South Western Railway",
                    "South  Western  Railway": "South Western Railway",
                    "South  Western Railway": "South Western Railway",
                    "Southern Power Distribution Company of Telangana Limited": "SOUTHERN POWER DISTRIBUTION COMPANY OF TELANGANA LIMITED",
                    "Southern Power Distribution Company of Telangana Limited (TSSPDCL)": "SOUTHERN POWER DISTRIBUTION COMPANY OF TELANGANA LIMITED",
                    "Tamilnadu Generation and Distribution Corporation Limited": "TAMILNADU GENERATION AND DISTRIBUTION CORPORATION LIMITED",
                    "Tamil Nadu  Generation and Distribution Corporation Limited": "TAMILNADU GENERATION AND DISTRIBUTION CORPORATION LIMITED",
                    "Tamilnadu Generation and Dist. Corp. Ltd TANGEDCO": "TAMILNADU GENERATION AND DISTRIBUTION CORPORATION LIMITED",
                    "TANGEDCO": "TAMILNADU GENERATION AND DISTRIBUTION CORPORATION LIMITED",
                    # "Torrent Power Ahmedabad": "Torrent Power Ahmedabad",
                    "TORRENT POWER LIMITED - AHMEDABAD DISTRIBUTION": "Torrent Power Ahmedabad",
                    "Torrent Power Limited - Dahej Distribution": "Torrent Power Limited - Dahej",
                    "TORRENT POWER LIMITED - SURAT DISTRIBUTION": "Torrent Power Surat",
                    "Torrent Power Ltd Surat": "Torrent Power Surat",
                    "Torrent Power Limited- Dahej": "Torrent Power Limited - Dahej",
                    "Torrent Power Ltd Dahej": "Torrent Power Limited - Dahej",
                    # "Torrent Power Surat": "Torrent Power Surat",
                    "U P Power Corporation Ltd": "UPPCL", "Uttar Pradesh Power Corporation Ltd (UPPCL)": "UPPCL",
                    "Uttar Pradesh Power Corporation Ltd": "UPPCL",
                    "Uttar Pradesh Power Corporation Limited (UPPCL)": "UPPCL",
                    "Uttarakhand Power Corporation Limited": "UTTARAKHAND POWER CORPORATION LIMITED",
                    "Uttarakhand Power Corporation": "UTTARAKHAND POWER CORPORATION LIMITED",
                    "Uttrakhand Power Corp Ltd": "UTTARAKHAND POWER CORPORATION LIMITED",
                    "Uttrakhand Power Corp.Ltd": "UTTARAKHAND POWER CORPORATION LIMITED",
                    "Vedanta Ltd_SEZ Unit_Jharsuguda": "Vedanta Limited SEZ UNIT, Jharsuguda",
                    "West Bengal State Electricity Distribution Company Limited (WBSEDCL)": "WEST BENGAL STATE ELECTRICITY DISTRIBUTION COMPANY LIMITED",
                    "West Central Railway": "WEST CENTRAL RAILWAY",

                    "Uttarakhand Power Corporation Ltd": "UTTARAKHAND POWER CORPORATION LIMITED",
                    # "Uttarakhand Power Corporation Limited (UPCL)": "UTTARAKHAND POWER CORPORATION LIMITED",
                    "TPL-Ahmedabad Discom": "TPL-Ahmedabad Discom",

                    "JBVNL": "JHARKHAND BIJLI VITRAN NIGAM LIMITED",
                    "CSPDL": "CHHATTISGARH STATE POWER DISTRIBUTION COMPANY LIMITED",
                    "NUPLLP": "NIDAR UTILITIES PANVEL LLP",  # "REMCL": "Railway Energy Management Company Limited",
                    "LBSCML": "LAXMIPATI BALAJI SUPPLY CHAIN MANAGEMENT LIMITED",
                    "RUVNL": "RAJASTHAN URJA VIKAS NIGAM LIMITED", "BSES": "BSES Rajdhani Power Limited",
                    "BYPL": "BSES Yamuna Power Limited", "IPCL": "India Power Corporation Limited",
                    "APPCC": "Andhra Pradesh Power Coordination Committee", "GUVNL": "Gujarat Urja Vikas Nigam Limited",
                    "MSEZL": "Mangalore SEZ Limited", "APDCL": "ASSAM POWER DISTRIBUTION COMPANY LIMITED",
                    # "MPPMCL": "Madhya Pradesh Power Management Company Limited",
                    "PCKL": "Power Company of Karnataka Ltd", "PSPCL": "Punjab State Power Corporation Limited",
                    "EON KHARADI INFRASTRUCTURE PVT LTD": "EON KHARADI INFRASTRUCTURE PRIVATE LIMITED, Phase -2",
                    # "SEZ BIOTECH SERVICES PRIVATE LIMITED": "RAIPUR ENERGEN LIMITED",
                    # "PFC Consulting Limited": "LAXMIPATI BALAJI SUPPLY CHAIN MANAGEMENT LIMITED",
                    # "Sundew Properties Limited": "LAXMIPATI BALAJI SUPPLY CHAIN MANAGEMENT LIMITED",
                    "TAMILNADU ELECTRICITY BOARD": "Tamil Nadu Electricity Board",
                    "Andhra Pradesh Power Co-Ordination Committee (APPCC)": "Andhra Pradesh Power Coordination Committee",
                    "TANGEDCO ltd": "TAMILNADU GENERATION AND DISTRIBUTION CORPORATION LIMITED",
                    # "MADC LTD": "Maharashtra Airport Development Company Limited",
                    # "RELIANCE ENERGY MUMBAI DISCOM": "TPL-Surat Discom",
                    "UPCL": "UTTARAKHAND POWER CORPORATION LIMITED", "KSEBL": "KSEB",
                    "MAHARASHTRA STATE ELECTRICITY CO LTD": "Maharashtra State Electricity Distribution Co Limited",
                    "CESC": "CESC LIMITED",
                    "HARYANA POWER PURCHASE CENTRE(A JOINT FORUM OF UHBVN&DHBVN)": "Haryana Power Purchase Centre",
                    # "AEML": "AEML SEEPZ Limited",
                    # "TPCL": "TPCL_U7 RLNG / The Tata Power Co Ltd (MTPS)",
                    "TAMILNADU GENERATION AND DISTRIBUTION CORPN LTD": "TAMILNADU GENERATION AND DISTRIBUTION CORPORATION LIMITED",
                    "HPSEBL": "HIMACHAL PRADESH STATE ELECTRICITY BOARD LIMITED", "BEST": "BEST Undertaking",
                    "Chandigarh Electricity Department": "CHANDIGARH",
                    "KRC Infrastructure and Projects Pvt Ltd": "KRC INFRASTRUCTURE AND PROJECTS PRIVATE LIMITED",
                    "MP Power Management Company Ltd": "M.P. POWER MANAGEMENT COMPANY LIMITED",
                    "Assam Power Distribution Company Ltd": "ASSAM POWER DISTRIBUTION COMPANY LIMITED",
                    "Torrent Power Limited": "Torrent Power Limited - Dahej",
                    "MPSEZ Utilities Private Limited": "MPSEZ Utilities Limited",
                    "SOUTHERN POWER DISTRIBUTION COMPANY OF TELANGANA LTD": "SOUTHERN POWER DISTRIBUTION COMPANY OF TELANGANA LIMITED",
                    "WEST BENGAL STATE ELECTRICITY DISTRIBUTION COMPANY LIMITED": "WEST BENGAL STATE ELECTRICITY DISTRIBUTION COMPANY LIMITED",
                    "Noida Power Company Limited": "Noida Power Company limited",
                    "JAWAHARLAL NEHRU PORT TRUST": "Jawaharlal Nehru Port Trust",
                    "GUJARAT URJA VIKAS NIGAM LIMITED": "GUJARAT URJA VIKAS NIGAM LIMITED",
                    "TATA POWER DELHI DISTRIBUTION LIMITED": "Tata Power Delhi Distribution Limited",
                    "MINDSPACE BUSINESS PARKS PRIVATE LIMITED": "MINDSPACE BUSINESS PARKS PRIVATE LIMITED",
                    "BSPHCL": "BSPHCL", "NIDP DEVELOPERS PRIVATE LIMITED": "NIDP DEVELOPERS PRIVATE LIMITED",
                    "GRIDCO LIMITED": "GRIDCO LIMITED",
                    "Gigaplex Estate Private Limited": "GIGAPLEX ESTATE PRIVATE LIMITED",
                    'Andhra Pradesh Power Co-Ordination Committee (Andhra Pradesh Power Coordination Committee)': 'Andhra Pradesh Power Coordination Committee'}

trader_state_mapping = {"Rajasthan": "Rajasthan", "Madhya Pradesh": "Madhya Pradesh", "Meghalaya": "Meghalaya",
                        "Odisha": "Odisha", "Telangana": "Telangana", "Delhi": "Delhi",
                        "Andhra Pradesh": "Andhra Pradesh", "Tamil Nadu": "Tamil Nadu", "Tripura": "Tripura",
                        "Goa": "Goa", "Uttar Pradesh": "Uttar Pradesh", "Punjab": "Punjab", "Haryana": "Haryana",
                        "Jharkhand": "Jharkhand", "Mizoram": "Mizoram", "Karnataka": "Karnataka",
                        "West Bengal": "West Bengal", "Himachal Pradesh": "Himachal Pradesh", "Nagaland": "Nagaland",
                        "Uttarakhand": "Uttarakhand", "Arunachal Pradesh": "Arunachal Pradesh", "Manipur": "Manipur",
                        "Maharashtra": "Maharashtra", "Sikkim": "Sikkim", "Chhattisgarh": "Chhattisgarh",
                        "Assam": "Assam", "Gujarat": "Gujarat", "Kerala": "Kerala", "Bihar": "Bihar",
                        "Chandigarh": "Chandigarh", "Puducherry": "Puducherry",
                        "Jammu and Kashmir": "Jammu and Kashmir", "Himachal Prades": "Himachal Pradesh",
                        "Madhya Pradhesh": "Madhya Pradesh", "Arunachal Prades": "Arunachal Pradesh",
                        "Himanchal Pradesh": "Himachal Pradesh", "Andhara Pradesh": "Andhra Pradesh",
                        "Andhrai Pradesh": "Andhra Pradesh", "Himachal\n Pradesh": "Himachal Pradesh",
                        "Madhya\n Pradesh": "Madhya Pradesh", "Arunachal\n Pradesh": "Arunachal Pradesh",
                        "Chhatisgarh": "Chhattisgarh", "West  Bengal": "West Bengal", "W est Bengal": "West Bengal",
                        "Chhattisga rh": "Chhattisgarh", "Uttar Pradhesh": "Uttar Pradesh",
                        "Andhra Prades": "Andhra Pradesh", "Chhattisg arh": "Chhattisgarh",
                        "Uttarakh and": "Uttarakhand", "Uttar Prades h": "Uttar Pradesh",
                        "Chhattishgarh": "Chhattisgarh", "Chhattisga\nrh": "Chhattisgarh",
                        "Chhattisgar h": "Chhattisgarh", "Chhattisgharh": "Chhattisgarh",
                        "Uttar Pradaesh": "Uttar Pradesh", "Maharashtr a": "Maharashtra",
                        "Maharashtr\na": "Maharashtra", "hhattisgarh": "Chhattisgarh",
                        "Madhya Prades": "Madhya Pradesh", "ndhra Pradesh": "Andhra Pradesh",
                        "Chhattisg\narh": "Chhattisgarh", "Chhattisgar": "Chhattisgarh",
                        "MadhyaPradesh": "Madhya Pradesh", "West Benagal": "West Bengal",
                        "Uttar\n Pradesh": "Uttar Pradesh", "Maharastra": "Maharashtra", "Uttrakhand": "Uttarakhand",
                        "TamilNadu": "Tamil Nadu", "Karnatak a": "Karnataka", "WestBengal": "West Bengal",
                        "West Benga": "West Bengal", "Telangan\na": "Telangana", "Maharshtra": "Maharashtra",
                        "Meghalaya ": "Meghalaya", "Meghalay": "Meghalaya", "Himachal\nPradesh": "Himachal Pradesh",
                        "Rajsthan": "Rajasthan", "Karnatka": "Karnataka", "Himachal Predesh": "Himachal Pradesh",
                        "runachal Prades": "Arunachal Pradesh", "Jammu And Kashmir": "Jammu and Kashmir",
                        "Meghalya": "Meghalaya", "Himachal Praedsh": "Himachal Pradesh", "Karnatak": "Karnataka",
                        "Arunachal\nPradesh": "Arunachal Pradesh", "himachal Pradesh": "Himachal Pradesh",
                        "Himachal pradesh": "Himachal Pradesh", "Madhya\nPradesh": "Madhya Pradesh",
                        "Madhya pradesh": "Madhya Pradesh", "madhya Pradesh": "Madhya Pradesh",
                        "Andhra\nPradesh": "Andhra Pradesh", "Himachal Prade": "Himachal Pradesh",
                        "Andhra pradesh": "Andhra Pradesh", "Madhya  Prades": "Madhya Pradesh",
                        "Madhva Pradesh": "Madhya Pradesh", "Madhya Pradosh": "Madhya Pradesh", "Gujarat ": "Gujarat",
                        "andhra Pradesh": "Andhra Pradesh", "Gujrat": "Gujarat", "Uttar\nPradesh": "Uttar Pradesh",
                        "Chattishgarh": "Chhattisgarh", "Uttar pradesh": "Uttar Pradesh",
                        "Andhra Prade": "Andhra Pradesh", "Odisha ": "Odisha", "Madhya Prade": "Madhya Pradesh",
                        "Odish a": "Odisha", "Uttar Pradosh": "Uttar Pradesh", "Uttar Pracesh": "Uttar Pradesh",
                        "Uttar Predesh": "Uttar Pradesh", " Punjab": "Punjab", "Punja b": "Punjab",
                        "Utter Pradesh": "Uttar Pradesh", " Odisha": "Odisha", "West BengaL": "West Bengal",
                        "West\nBengal": "West Bengal", "West bengal": "West Bengal", "West Bangal": "West Bengal",
                        "West Benaal": "West Bengal", "Odsha": "Odisha", "Maharashrra": "Maharashtra",
                        "west Bengal": "West Bengal", "Tamil nadu": "Tamil Nadu", "Tamil\nNadu": "Tamil Nadu",
                        "Maharasht": "Maharashtra", "Uttarakha": "Uttarakhand", "nachal Pradesh": "Arunachal Pradesh",
                        "Himachal Prad": "Himachal Pradesh", "AAadhya Pradesh": "Madhya Pradesh",
                        "Madhya Pradesh/WR": "Madhya Pradesh", "Uttar Pradesh/NR": "Uttar Pradesh",
                        "meghalaya": "Meghalaya", "karnataka": "Karnataka", "Chhattisgarh rh": "Chhattisgarh",
                        "Maghalaya": "Meghalaya", "Chhattisgarh\nrh": "Chhattisgarh", "KArnataka": "Karnataka",
                        "Telengana": "Telangana", "Madhya Pradei": "Madhya Pradesh", "Madhya Prade<": "Madhya Pradesh",
                        "Jammu & Kashmir": "Jammu and Kashmir", "Andhra Prad": "Andhra Pradesh",
                        "adhya Prade": "Madhya Pradesh", "ndhra Prade": "Andhra Pradesh",
                        "West Bengal/ER": "West Bengal", "Maharashtra ra": "Maharashtra",
                        "Himanchal Prad": "Himachal Pradesh", "Uttar Prad": "Uttar Pradesh",
                        "Jammu Kashmir": "Jammu and Kashmir", "Chhattisagr": "Chhattisgarh",
                        "Chattisaarh": "Chhattisgarh", "MadhyaPradesh/WR": "Madhya Pradesh",
                        "Madhya\npradesh": "Madhya Pradesh", "gujarat": "Gujarat", "Guiarat": "Gujarat",
                        "Karnataka/SR": "Karnataka", "UttarPradesh/NR": "Uttar Pradesh", "Chhattisg": "Chhattisgarh",
                        "GUjarat": "Gujarat", "DVC\nWest Bengal": "West Bengal", "andhra Prade": "Andhra Pradesh",
                        "madhya Prade": "Madhya Pradesh", "Jammu  & Kashmir": "Jammu and Kashmir",
                        "Chhatisgarh/WR": "Chhattisgarh", "Madhya Pradt": "Madhya Pradesh", "Tamilnadu": "Tamil Nadu",
                        "Jammu &Kashmir": "Jammu and Kashmir", "Madhya\nPradesh/WR": "Madhya Pradesh",
                        "Kerela": "Kerala", "Odissa": "Odisha", "sikkim": "Sikkim", "odisha": "Odisha",
                        "Andhra Pra": "Andhra Pradesh", "Odhisa": "Odisha", "Siikim": "Sikkim", "Odtsha": "Odisha",
                        "Odishn": "Odisha", "Odlsha": "Odisha", "WestBengal/ER": "West Bengal",
                        "Uttar\nPradesh/NR": "Uttar Pradesh", "Maharastra/WR": "Maharashtra", "kerala": "Kerala",
                        "Arunachal Pr": "Arunachal Pradesh", "west bengal": "West Bengal", "karnatka": "Karnataka",
                        "Mabarashzra": "Maharashtra", "WB, Jharkhand": "Jharkhand",
                        "Madhya Pradesh/WRLDC": "Madhya Pradesh", "Gujarat/WR": "Gujarat",
                        "Andhra Pradesh/SRLDC": "Andhra Pradesh", "Jammu & kashmir": "Jammu and Kashmir",
                        "Arunachal Pradesh (Assam)": "Arunachal Pradesh (Assam)", "delhi": "Delhi", "DElhi": "Delhi",
                        "Tamilnad u": "Tamil Nadu", "Jammu and_x000D_Kashmir": "Jammu and Kashmir",
                        "Uttarpardesh": "Uttar Pradesh", "TAMil Nadu": "Tamil Nadu", "Tamilanadu": "Tamil Nadu",
                        "Delhi(Andhra Pradesh)": "Delhi (Andhra Pradesh)", "B-har": "Bihar", "Briar": "Bihar",
                        "Sikkim/ER": "Sikkim", "Odisha/ER": "Odisha", "Punjab/NR": "Punjab",
                        "Himachal_x000D_Pradesh": "Himachal Pradesh",
                        "Arunachal Pradesh (Sikkim)": "Arunachal Pradesh (Sikkim)", "Madhya PradESH": "Madhya Pradesh",
                        "Meghayala": "Meghalaya", "Uttarprade": "Uttar Pradesh", "Madhya Pr": "Madhya Pradesh",
                        "Haryana DVC": "Haryana", "For Haryana": "Haryana", "Tamilnad": "Tamil Nadu",
                        "Telangana SLDC": "Telangana", "dhya Prad": "Madhya Pradesh", "Himachal P": "Himachal Pradesh",
                        "Chhattisgar_x000D_h": "Chhattisgarh",
                        "Arunachal Pradesh (Manipur)": "Arunachal Pradesh (Manipur)", "Tamil Nadu/SRLDC": "Tamil Nadu",
                        "Delhi/NR": "Delhi", "Bihar/ER": "Bihar", "Raipur": "Manipur", "achal Prad": "Himachal Pradesh",
                        "Andhra_x000D_Pradesh": "Andhra Pradesh", "Madhya_x000D_Pradesh": "Madhya Pradesh",
                        "Arunachal Pradesh (Himachal)": "Arunachal Pradesh (Himachal Pradesh)",
                        "Delhi(West Bengal)": "Delhi (West Bengal)", "Delhi(Maharashtra)": "Delhi (Maharashtra)",
                        "arnil Nadu": "Tamil Nadu", "Uttar_x000D_Pradesh": "Uttar Pradesh",
                        "Telangana/SRLDC": "Telangana", "KeralaSLDC": "Kerala",
                        "Hiamchal_x000D_Pradesh": "Himachal Pradesh", "Cdsha": "Odisha",
                        "Dadra and Nagar Havel i": "Dadra and Nagar Haveli and Daman and Diu",
                        "uttarpardesh": "Uttar Pradesh", "Haryana (Uttar Pradesh)": "Haryana",
                        "Madhya_x000D_pradesh": "Madhya Pradesh",
                        "Dadra and Nagar Haveli": "Dadra and Nagar Haveli and Daman and Diu", "Odisha SLDC": "Odisha",
                        "Guiaiat": "Gujarat", "Assam/NER": "Assam", "New Delhi": "Delhi", "Pradesh": "Uttar Pradesh",
                        "Gujarat/WRLDC": "Gujarat", "Telangana Haryana": "Telangana",
                        "Haryana (West Bengal)": "Haryana", "Andhra State": "Andhra Pradesh",
                        "Dadra and Nagar Haveli (UT)": "Dadra and Nagar Haveli and Daman and Diu",
                        "Jammu &_x000D_Kashmir": "Jammu and Kashmir",
                        "Arunachal Pradesh (Uttar Pradesh)": "Arunachal Pradesh", "GoA": "Goa", "Orissa": "Odisha",
                        "Himachal": "Himachal Pradesh", "Orrisa": "Odisha",
                        "Arunachal Pradesh (Andhra Pradesh)": "Arunachal Pradesh", "Delhi(Haryana)": "Delhi",
                        "Odftha": "Odisha", "Debi": "Delhi", "Gon": "Goa", "Manipur/NERLDC": "Manipur",
                        "Tamil": "Tamil Nadu",
                        "Dadra and\nNagar Haveli (UT)": "Dadra and Nagar Haveli and Daman and Diu",
                        "Dadra\nand Nagar Haveli (UT)": "Dadra and Nagar Haveli and Daman and Diu",
                        "Dadar And Nagar Haveli": "Dadra and Nagar Haveli and Daman and Diu",
                        "West Bengal (Uttar Pradesh)": "West Bengal (Uttar Pradesh)",
                        "adra and Nagar Have": "Dadra and Nagar Haveli and Daman and Diu",
                        "Haryana (Meghalaya)": "Haryana (Meghalaya)",
                        "Dadra & Nagar Haveli": "Dadra and Nagar Haveli and Daman and Diu", "Odisha Odisha": "Odisha",
                        "Dadra Nagar Haveli": "Dadra and Nagar Haveli and Daman and Diu",
                        "UTTAR\nPradesh": "Uttar Pradesh", "Uttar": "Uttarakhand",
                        "Dadara & Nagar Haveli": "Dadra and Nagar Haveli and Daman and Diu",
                        "Tamil Nadu & Rajasthan": "Tamil Nadu",
                        "Dadra & Nagar Havel": "Dadra and Nagar Haveli and Daman and Diu",
                        "Dad ar Nagar Haveli": "Dadra and Nagar Haveli and Daman and Diu",
                        "Haryana (Orrisa)": "Haryana (Odisha)", "Andhra": "Andhra Pradesh",
                        "Dadra & Nagar\nHaveli": "Dadra and Nagar Haveli and Daman and Diu",
                        "Dadra &\nNagar Haveli": "Dadra and Nagar Haveli and Daman and Diu",
                        "Dadra\n& Nagar Haveli": "Dadra and Nagar Haveli and Daman and Diu", "Deltv": "Delhi",
                        "Dadar Nagar Haveli": "Dadra and Nagar Haveli and Daman and Diu",
                        "adra and Nagar Haw": "Dadra and Nagar Haveli and Daman and Diu",
                        "Dadra Nager Haveli": "Dadra and Nagar Haveli and Daman and Diu",
                        "adra And Nagar have": "Dadra and Nagar Haveli and Daman and Diu",
                        "Haryana (Manipur)": "Haryana (Manipur)", "Arunach": "Arunachal Pradesh",
                        "Dadar &\nNagar Haveli": "Dadra and Nagar Haveli and Daman and Diu",
                        "Daman and Diu\n- Dadra and Nagar Haveli": "Dadra and Nagar Haveli and Daman and Diu",
                        "Uttarpradesh": "Uttar Pradesh", "Himachal Pradesh/SR": "Himachal Pradesh",
                        "Chhattishgarh/WR": "Chhattisgarh", "Andrapradesh": "Andhra Pradesh",
                        "Chhatisgarh ": "Chhattisgarh", "Rajasthan/NR": "Rajasthan", "Chhattisgar/SR": "Chhattisgarh",
                        "Madhya\nPardesh": "Madhya Pradesh", "Andhra Prade sh": "Andhra Pradesh",
                        "andhra pradesh": "Andhra Pradesh", "west  bengal": "West Bengal", "Karanataka": "Karnataka",
                        "utttar Pradesh": "Uttar Pradesh", "Punjab /NR": "Punjab", "TamilNadu/SR": "Tamil Nadu",
                        "Tamil Nadu/SR": "Tamil Nadu", "Himachal pradesh/SR": "Himachal Pradesh",
                        "andhra  Pradesh": "Andhra Pradesh", "madhya  Pradesh": "Madhya Pradesh",
                        "Madhya Pradesh/SR": "Madhya Pradesh", "Jammu and  Kashmir": "Jammu and Kashmir",
                        "AndhraPradesh/SR": "Andhra Pradesh", "Tamilnadu/SR": "Tamil Nadu",
                        "Uttarpradesh/NR": "Uttar Pradesh", "Chhattishgarh/ SR": "Chhattisgarh",
                        "DVC/West Bengal": "West Bengal", "Chattisgarh/WR": "Chhattisgarh",
                        "Jammu  &Kashmir": "Jammu and Kashmir", "andhrapradesh": "Andhra Pradesh",
                        "Haryana\nDVC": "Haryana", "Telangana\nSLDC": "Telangana", "Telangana\nHaryana": "Telangana",
                        "Dadra and Nagar Haveli\n(UT)": "Dadra and Nagar Haveli and Daman and Diu",
                        "Daman and Diu - Dadra and Nagar Haveli": "Dadra and Nagar Haveli and Daman and Diu",
                        "Bangladesh": "Bangladesh", "Haryana (Himachal)": "Haryana (Himachal Pradesh)",
                        "Delhi (Nepal)": "Delhi (Nepal)",
                        "Daman and Diu -\n Dadra and Nagar Haveli": "Dadra and Nagar Haveli and Daman and Diu",
                        "Daman and Diu - Dadra and Nagar\n Haveli": "Dadra and Nagar Haveli and Daman and Diu",
                        "Bhutan": "Bhutan", "Dadra and Nagar": "Dadra and Nagar Haveli and Daman and Diu",
                        "Nepal": "Kerala", "Haryana (AAeghalaya)": "Haryana (Meghalaya)",
                        "Daman and Diu - Dadra and Nagar\nHaveli": "Dadra and Nagar Haveli and Daman and Diu",
                        "HIMACHAL pradesh": "Himachal Pradesh", "Hyderabad": "Hyderabad",
                        "Daman and Diu": "Dadra and Nagar Haveli and Daman and Diu", "for Bangladesh": "Bangladesh",
                        "Delhi(Himachal)": "Delhi (Himachal Pradesh)",
                        "Daman and Diu UT": "Dadra and Nagar Haveli and Daman and Diu", "Chennai": "Chennai",
                        "Dadra & Na": "Dadra and Nagar Haveli and Daman and Diu", "Tangedco": "Tangedco",
                        "Mumbai": "Mumbai", "Discom": "Discom", "Jammu": "Jammu and Kashmir",
                        "Daman & Diu": "Dadra and Nagar Haveli and Daman and Diu",
                        "Daman &\nDiu": "Dadra and Nagar Haveli and Daman and Diu", "Solar\nProjects": "Solar Projects",
                        "Orissa/ERLDC": "Odisha", "biiutan": "Bhutan",
                        "a & Nagar H": "Dadra and Nagar Haveli and Daman and Diu",
                        "DADRA Nagar": "Dadra and Nagar Haveli and Daman and Diu", "bhutan": "Bhutan",
                        "Dadra & N": "Dadra and Nagar Haveli and Daman and Diu", "Orissa       ,": "Odisha",
                        "U P": "Uttar Pradesh", "J & K": "Jammu and Kashmir",
                        "Damodar Valley Corporation/ER": "Dadra and Nagar Haveli and Daman and Diu",
                        "Depending on Source": "Depending on Source", "GOA": "Goa",
                        "Damodar VallyCorporation/ER": "Damodar Vally Corporation", "GCA": "Goa", "WB": "West Bengal",
                        "TAMIL NADU": "Tamil Nadu", "ISGS": "ISGS", "TELANGANA a": "Telangana",
                        "TAMNIL NADU": "Tamil Nadu", "AP": "AP", "MeECL": "MeECL", "for NEA": "for NEA",
                        "RAJASTHAN N": "Tamil Nadu", "UTTAR PRA": "Uttar Pradesh", "UP": "Uttar Pradesh",
                        "DADRA & NAGAR HAVELI": "Dadra and Nagar Haveli and Daman and Diu",
                        "UTTAR PRAD": "Uttar Pradesh", "BHUTAN": "Bhutan", "DNH": "DNH", "HP": "Himachal Pradesh",
                        "DVC": "DVC", "MP": "Madhya Pradesh", "SR": "SR", "ANDHRA PRA": "Andhra Pradesh", "KR": "KR",
                        "HIMACHAL PR": "Himachal Pradesh",
                        "DADRA AND NAGAR HAVELI": "Dadra and Nagar Haveli and Daman and Diu", "M.P": "Madhya Pradesh",
                        "DRA & NAGAR HAV": "Dadra and Nagar Haveli and Daman and Diu", "TTAR PRADES": "Uttar Pradesh",
                        "ADHYA PRADE": "Madhya Pradesh", "NDHRA PRADE": "Andhra Pradesh", "WBSLDC": "West Bengal",
                        "ADRA & NAGAR HAVE": "Dadra and Nagar Haveli and Daman and Diu",
                        "DADRA & NAGAR HA": "Dadra and Nagar Haveli and Daman and Diu",
                        "MADHYA PRADES": "Madhya Pradesh", "GUJRAT": "Gujarat", "TAMILNAD": "Tamil Nadu",
                        "DAMAN& DIU": "Dadra and Nagar Haveli and Daman and Diu", "J&K": "Jammu and Kashmir",
                        "PSEB": "Punjab", "ASEB": "Assam", "GJSLDC": "GJSLDC", "CSEB": "CSEB", "BSEB": "BSEB",
                        "RAJASTHAN": "Rajasthan", "TELANGANA": "Telangana", "TELENGANA": "Telangana",
                        "TAMILNADU": "Tamil Nadu", "DAMAN & DIU": "Dadra and Nagar Haveli and Daman and Diu",
                        "UTTAR PRADESH H": "Uttar Pradesh", "UPSLDC": "Uttar Pradesh", "DELHI": "Delhi",
                        "GUJARAT": "Gujarat", "BIHAR": "Bihar", "ASSAM": "Assam", "NEPAL": "Nepal",
                        "MPPMCL": "Madhya Pradesh", "WESTBENGAL": "West Bengal", "JAMMU KASHMIR": "Jammu and Kashmir",
                        "UTTRAKHAND": "Uttar Pradesh", "RYANA": "Haryana", "ANDHRA PRADESH H": "Andhra Pradesh",
                        "APSLDC": "APSLDC", "WEST": "West Bengal", "UTTARAKHAND": "Uttarakhand",
                        "JAMMU& KASHMIR": "Jammu and Kashmir", "TELANGANA A": "Telangana", "MANIPUR": "Manipur",
                        "WEST BENGAL": "West Bengal", "HIMANCHAL PRADESH": "Himachal Pradesh",
                        "ADRA NAGAR HAVE": "Dadra and Nagar Haveli and Daman and Diu",
                        "HIMACHAL PRADES H": "Himachal Pradesh", "KWHEP": "KWHEP", "PUNJAB": "Punjab",
                        "ODISHA": "Odisha", "KERALA": "Kerala", "ER": "ER", "PSPCL": "PSPCL", "OSIDHA": "Odisha",
                        "DAMAN &D": "Dadra and Nagar Haveli and Daman and Diu", "KERELA": "Kerala", "ARYANA": "Haryana",
                        "ORISSA": "Odisha", "PUNJA3": "Punjab", "JHSLDC": "Jharkhand", "DLSLDC": "DLSLDC",
                        "KPTCL": "KPTCL", "JITPL": "JITPL", "TRIPURA": "Tripura", "HARYANA": "Haryana",
                        "SIKKIM": "Sikkim", "MEGHALAYA": "Meghalaya", "MAHARAS": "Maharashtra", "MIZORAM": "Mizoram",
                        "DISTRIBUTION CORPORATI": "Distribution Corporation", "JHARKHAND D": "Jharkhand",
                        "JAMMU AND_x000D_KASHMIR": "Jammu and Kashmir", "JAMMU &_x000D_KASHMIR": "Jammu and Kashmir",
                        "BANGLA DESH": "Bangladesh", "JHARKHAND": "Jharkhand", "MAHAR ASHTRA": "Maharashtra",
                        "BANGLADESH": "Bangladesh", "MAHARASH": "Maharashtra", "WEST_x000D_BENGAL": "West Bengal",
                        "UTTAR PRADESH": "Uttar Pradesh", "ANDHRAPRADESH": "Andhra Pradesh",
                        "DAMODAR VALLY CORPORATION": "Damodar Vally Corporation",
                        "DAMODAR VALLY": "Damodar Vally Corporation", "KARNATAKA": "Karnataka",
                        "ANDHRA PRADESH": "Andhra Pradesh", "CHATTISGARH": "Chattisgarh",
                        "MADHYA PRADESH": "Madhya Pradesh", "CHATTISHGAR": "Chattisgarh", "CHHATTISGAR": "Chattisgarh",
                        "KARANATAK": "Karnataka", "CHHATTISGARH": "Chattisgarh", "MAHARSHTRA": "Maharashtra",
                        "HIMACHAL PRADESH": "Himachal Pradesh", "MAHARASHTR": "Maharashtra",
                        "CHATTISHGARH": "Chattisgarh", "MAHSRSHTRA": "Maharashtra", "MAHARASHTRA": "Maharashtra",
                        "MAHARAS HTRA": "Maharashtra", "UTTAR_x000D_PRADESH": "Uttar Pradesh",
                        "HIMACHAL_x000D_PRADESH": "Himachal Pradesh",
                        "CHATTISGARH CHATTISGARH CHATTISGARH CHATTISGARH CHATTISGARH CHATTISGARH": "Chattisgarh",
                        'ANDHRA\nPRADESH': 'Andhra Pradesh', 'Chattisgarh': 'Chhattisgarh',
                        'Chhattisagrh     ': 'Chhattisagrh', 'Chhattisagrh': 'Chhattisagrh',
                        'HIMACHAL\nPRADESH': 'Himachal Pradesh', 'HIMACHAL PRADESH\nH': 'Himachal Pradesh',
                        'HIMACHAL PRADESH H': 'Himachal Pradesh', 'HIMACHAL PRADES\nH': 'Himachal Pradesh',
                        'JAMMU\n& KASHMIR': 'Jammu and Kashmir', 'JAMMU & KASHMIR': 'Jammu and Kashmir',
                        'JAMMU &\nKASHMIR': 'Jammu and Kashmir', 'MADHYA\nPRADESH': 'Madhya Pradesh',
                        'MADHYA PRADESH H': 'Madhya Pradesh', 'MADHYA PRADESH\nH': 'Madhya Pradesh',
                        'WEST\nBENGAL': 'West Bengal', 'MAHARAS\nHTRA': 'Maharashtra',
                        'UTTAR\nPRADESH': 'Uttar Pradesh', }

trader_category_mapping = {"IPP": "IPP", "ISGS": "ISGS", "Distribution Licensee": "Distribution Licensee",
    "Government": "Government", "Generator": "Generator", "Captive": "Captive", "Discom Consumer": "Discom Consumer",
    "State Utility": "State Utility", "Discom": "Discom", "Industrial Consumer": "Industrial Consumer",
    "Consumer": "Consumer", "Utility": "State Utility", "Thermal": "Thermal", "RE Power": "RE Power", "Hydro": "Hydro",
    "Deemed Distribution Licensee": "Deemed Distribution Licensee", "Trading Licensee": "Trading Licensee",
    "Industry": "Industry", "Non Solar": "Non Solar", "SPD": "SPD", "WPD": "WPD", "HPD": "HPD",
    "Power Exchange": "Power Exchange", "OA Consumer": "OA Consumer", "DVVNL": "DVVNL",
    "Trader/Discom": "Trader/Discom", "Trader/OAC": "Trader/OAC", "Bulk Consumer": "Bulk Consumer", "Solar": "Solar",
    "Industrial Buyer": "Industrial Buyer", "IEX": "IEX", "Small Hydro": "Small Hydro", "Bulk Power": "Bulk Power",
    "Trader (Government)": "Trader (Government)", "Hotel": "Hotel", "Buyer": "Buyer", "Biomass": "Biomass",
    "Nodal Agency": "Nodal Agency", "Central Govt. Organisation": "Central Government Organisation",
    "District Licensee": "District Licensee", "Bagasse": "Baggasse", "IPP ": "IPP", "Commercial": "Commercial",
    "Cogen": "Cogen", "District Licencee": "District Licensee", "Dicsom": "Discom", "Disocm": "Discom",
    "Deisom": "Discom", "Oiscom": "Discom", "Drstnoution Licensee": "Distribution Licensee",
    "Dctrfcution Licensee": "Distribution Licensee", "cogen": "Cogen", "hydro": "Hydro",
    "DeemedDistribution": "Distribution Licensee", "Dist. licensee": "District Licensee", "Power": "Power Exchange",
    "Discorn": "Discom", "Ootnbuton Licensee": "Distribution Licensee",
    "Dtstrrtxrton Licensee": "Distribution Licensee", "Trader": "Trader", "IPP I": "IPP", "Exchange": "Power Exchange",
    "Trader (Consumer)": "Trader (Consumer)", "Power_x000D_Exchnage": "Power Exchange",
    "State Licensee": "State Licensee", "Di scorn": "Discom", "Trader/DISCOM": "Trader/Discom",
    "Govt. Organisation": "Central Government Organisation", "CPP": "IPP", "StateLicensee": "State Licensee",
    "fPP": "IPP", "State DISCOM": "State Discom", "SHEP": "SHEP", "GAS": "Gas", "Seller": "Seller", "DISCOMS": "Discom",
    "DISTRIBUTION Licensee": "Distribution Licensee", "Govt. of UP": "Government of Uttar Pradesh",
    "Co-Gen IPP": "Cogen IPP", "StateDISCOM": "State Discom", "HYDRO": "Hydro",
    "DaofciXion bcw.sea": "Distribution Licensee", "Ofe.-ritnyjon Lk-sroeo": "Distribution Licensee",
    "DISCOM": "Discom", "PX": "Power Exchange", "Tamilnadu": "Tamil Nadu", "Meghalaya": "Meghalaya",
    "OA CONSUMER": "OA Consumer", "INDUSTRY": "Industry", "GED": "GED", "TRADER": "Trader", "BUYER": "Buyer",
    "TRUST": "Trust", "CONSUMER": "Consumer", "SELLER": "Seller", "ipp": "IPP", "GENERATOR": "Generator",
    "UTILITY": "State Utility", '-': '', 'Capative': 'Captive',
    'Deemed Distribution Licencee': 'Deemed Distribution Licensee', 'State_x000D_Utility': 'State Utility',
    '  Discom': 'Discom', 'Distribution_x000D_Licensee': 'Distribution Licensee', 'Trader/ Discom': 'Trader/Discom',
    'Industrial\nConsumer': 'Industrial Consumer', 'Industrial': 'Industrial Consumer',
    'Deemed_x000D_Distribution': 'Deemed Distribution Licensee',
    'Deemed_x000D_Distribution_x000D_Licencee': 'Deemed Distribution Licensee',
    'Deemed\nDistribution\nLicencee': 'Deemed Distribution Licensee',
    'Deemed_x000D_Distribution_x000D_Licensee': 'Deemed Distribution Licensee',
    'Deemed\nDistribution': 'Deemed Distribution Licensee', 'Utilitiy': 'State Utility',
    'State Utilit': 'State Utility', 'State': 'State Utility',
    'State Utility_x000D_State Utility_x000D_State Utility': 'State Utility', 'Distributio': 'Distribution Licensee',
    'Governme': 'Government', 'Distribution': 'Distribution Licensee',
    'Distribution\nLicensee': 'Distribution Licensee', 'OA_x000D_Consumer': 'OA Consumer', ' Industry': 'Industry',
    'Dicom': 'Discom', 'OA\nConsumer': 'OA Consumer', 'vernment': 'Government', 'vernmentHA': 'Government',
    'Industries': 'Industry', 'T rader (Government)': 'Trader (Government)',
    'T rader {Government)': 'Trader (Government)', 'O-.tnbutcn Licensee': 'Distribution Licensee',
    'DseritxAon Lsoer.seo': 'Distribution Licensee', "Grzn.'xZkn Licensee": 'Distribution Licensee',
    'Distribution License©': 'Distribution Licensee', 'Govornmont': 'Government',
    'Open\n Access consumer': 'Open Access Consumer', 'Open Access consumer': 'Open Access Consumer',
    'Open Access\n consumer': 'Open Access Consumer', 'Distribution l': 'Distribution Licensee',
    'Distribution licens': 'Distribution Licensee', 'Power Exchanges': 'Power Exchange',
    'dustrial Consume': 'Industrial Consumer', 'State_x000D_DISCOM': 'State Discom', 'Generators': 'Generator',
    'Generator s': 'Generator', 'Power Exchnage': 'Power Exchange', 'tate Utility': 'State Utility',
    'bagasse': 'Baggase', 'State\nUtility': 'State Utility', 'State Utility_x000D_State Utility': 'State Utility',
    'Power\nExchange': 'Power Exchange', 'Dist. Licencee': 'Distribution Licensee', 'State\nDISCOM': 'State Discom',
    'Discern': 'Discom', '.HYDRO': 'Hydro', 'Uility': 'State Utility', 'District licencee': 'District Licensee',
    'Power  Exchange': 'Power Exchange', 'Disco m': 'Discom', 'Open Access Consumer': 'OA Consumer',
    'Open\n Access Consumer': 'OA Consumer', 'State Utiity': 'State Utility', 'State\nLicensee': 'State Licensee',
    'Trader/Disco': 'Trader/Discom', 'Distribution License': 'Distribution Licensee', }

trader_time_mapping = {}