tam_data_mapping = {
	"Adani Electricity Mumbai Limited": "Adani Electricity Mumbai Limited",
	"Andhra Pradesh Central Power Distribution Corp Ltd": "Andhra Pradesh Central Power Distribution Corporation Limited",
	"Andhra Pradesh Central Power Distribution Corp.ltd": "Andhra Pradesh Central Power Distribution Corporation Limited",
	"APDCL (Assam)": "ASSAM POWER DISTRIBUTION COMPANY LIMITED",
	"ArcelorMittal Nippon Steel India Limited": "ArcelorMittal Nippon Steel India Limited",
	"Bharat Aluminium Company Limited": "BHARAT ALUMINIUM COMPANY LTD",
	"Bharat Aluminum Company ltd (Bulk consumer)": "BHARAT ALUMINIUM COMPANY LTD (Bulk Consumer)",
	"BHARAT ALUMINIUM COMPANY LTD (Bulk Consumer)": "BHARAT ALUMINIUM COMPANY LTD (Bulk Consumer)",
	"Bihar State Power Holding Company Ltd Patna": "Bihar State Power (Holding) Company Limited",
	"Bihar State Power Holding Company Limited": "Bihar State Power (Holding) Company Limited",
	"Bihar State Power Holding Company": "Bihar State Power (Holding) Company Limited",
	"BSES Yamuna Power Limited (BYPL)": "BSES Yamuna Power Limited",
	"C.S.P.DISTRIBUTION_CO._LTD.": "CHHATTISGARH STATE POWER DISTRIBUTION COMPANY LIMITED",
	"Central Railways_Maharashtra": "Central Railway",
	# "Central Railway": "Central Railway",
	"CESC": "CESC LIMITED",
	"CESC Limited": "CESC LIMITED",
	"CSP Distribution  Company ltd": "CHHATTISGARH STATE POWER DISTRIBUTION COMPANY LIMITED",
	"CSP Distribution Co Ltd": "CHHATTISGARH STATE POWER DISTRIBUTION COMPANY LIMITED",
	"Dadra and Nagar Haveli and Daman and Diu Power Distribution Corporation Limited": "Dadra and Nagar Haveli and Daman and Diu Power Distribution Corporation Lim",
	"DNH Power Distribution Corporation Ltd": "DNH Beneficiary",
	# "DVC": "DVC",
	"Electricity Department_Government of Goa WR": "Electricity Department, GOA_WR",
	"Gift Power Company Ltd": "GIFT Power Company Limited",
	"Gigaplex Estate Private Limited": "GIGAPLEX ESTATE PRIVATE LIMITED",
	"Gigaplex Estate pvt ltd": "GIGAPLEX ESTATE PRIVATE LIMITED",
	"GRIDCO": "GRIDCO LIMITED",
	# "GRIDCO LIMITED": "GRIDCO LIMITED",
	"GUJARAT URJA VIKAS NIGAM LTD": "GUJARAT URJA VIKAS NIGAM LIMITED",
	"GUVNL": "GUJARAT URJA VIKAS NIGAM LIMITED",
	"Gujarat Urja Vikas Nigam Limited": "GUJARAT URJA VIKAS NIGAM LIMITED",
	"Himachal Pradesh State Electricity Board Ltd": "HIMACHAL PRADESH STATE ELECTRICITY BOARD LIMITED",
	"HPSEB": "HIMACHAL PRADESH STATE ELECTRICITY BOARD LIMITED",
	"Kerala State Electricity Board (KSEB)": "KERALA STATE ELECTRICITY BOARD LIMITED",
	"Kerala State Electricity Board Limited": "KERALA STATE ELECTRICITY BOARD  LIMITED",
	"KRC Infrastructure and Projects Pvt Ltd": "KRC INFRASTRUCTURE AND PROJECTS PRIVATE LIMITED",
	"KRC Infrastructure & Project Pvt Ltd": "KRC INFRASTRUCTURE AND PROJECTS PRIVATE LIMITED",
	"Maharashtra State Electricity Distribution Company Limited (MSEDCL)": "Maharashtra State Electricity Distribution Co Limited",
	"MSEDCL": "Maharashtra State Electricity Distribution Co Limited",
	"Mind Space business Park pvt ltd": "MINDSPACE BUSINESS PARKS PRIVATE LIMITED",
	"Mindspace Business Parks Pvt Ltd": "MINDSPACE BUSINESS PARKS PRIVATE LIMITED",
	"Mindspace Business Parks Private Limited": "MINDSPACE BUSINESS PARKS PRIVATE LIMITED",
	'New Delhi Municipal Council': "New Delhi Municipal Council",
	"New_Delhi_Municipal council_NDMC": "New Delhi Municipal Council",
	"Noida Power Company Limited": "Noida Power Company limited",
	"Noida power Company ltd": "Noida Power Company limited",
	"Noida Power Company.Ltd": "Noida Power Company limited",
	"NPCL": "Noida Power Company limited",
	"North Western Railway": "North Western Railway",
	"Northern  Railway  UP": "Northern Railway UP",
	"Northern  Railway UP": "Northern Railway UP",
	"Northern Railway UP": "Northern Railway UP",
	"NORTHERN RAILWAY UP": "Northern Railway UP",
	"Northern Railway": "Northern Railway",
	"Northern Railway Haryana": "Northern Railway-Haryana",
	"Power Company of Karnataka Limited -PCKL": "Power Company of Karnataka Ltd",
	"PCKL": "Power Company of Karnataka Ltd",
	# "Power Company of Karnataka Ltd": "Power Company of Karnataka Ltd",
	"Punjab State Power Corporation Ltd (PTC)": "Punjab State Power Corporation Limited",
	"Rajasthan Urja Vikas Nigam Ltd (RUVNL)": "RAJASTHAN URJA VIKAS NIGAM LIMITED",
	"Rajasthan Urja Vikas Nigam Ltd": "RAJASTHAN URJA VIKAS NIGAM LIMITED",
	"Rajasthan Urja Vikas Nigam .ltd": "RAJASTHAN URJA VIKAS NIGAM LIMITED",
	"Rajasthan Urja Vikas Nigam Limited": "RAJASTHAN URJA VIKAS NIGAM LIMITED",
	"RUVNL": "RAJASTHAN URJA VIKAS NIGAM LIMITED",
	"South Western Railway": "South Western Railway",
	"South  Western  Railway": "South Western Railway",
	"South  Western Railway": "South Western Railway",
	"Southern Power Distribution Company of Telangana Limited": "SOUTHERN POWER DISTRIBUTION COMPANY OF TELANGANA LIMITED",
	"Southern Power Distribution Company of Telangana Limited (TSSPDCL)": "SOUTHERN POWER DISTRIBUTION COMPANY OF TELANGANA LIMITED",
	"Tamilnadu Generation and Distribution Corporation Limited": "TAMILNADU GENERATION AND DISTRIBUTION CORPORATION LIMITED",
	"Tamil Nadu  Generation and Distribution Corporation Limited": "TAMILNADU GENERATION AND DISTRIBUTION CORPORATION LIMITED",
	"Tamilnadu Generation and Dist. Corp. Ltd TANGEDCO": "TAMILNADU GENERATION AND DISTRIBUTION CORPORATION LIMITED",
	"TANGEDCO": "TAMILNADU GENERATION AND DISTRIBUTION CORPORATION LIMITED",
	# "Torrent Power Ahmedabad": "Torrent Power Ahmedabad",
	"TORRENT POWER LIMITED - AHMEDABAD DISTRIBUTION": "Torrent Power Ahmedabad",
	"Torrent Power Limited - Dahej Distribution": "Torrent Power Limited - Dahej",
	"TORRENT POWER LIMITED - SURAT DISTRIBUTION": "Torrent Power Surat",
	"Torrent Power Ltd Surat": "Torrent Power Surat",
	"Torrent Power Limited- Dahej": "Torrent Power Limited - Dahej",
	"Torrent Power Ltd Dahej": "Torrent Power Limited - Dahej",
	# "Torrent Power Surat": "Torrent Power Surat",
	"U P Power Corporation Ltd": "UPPCL",
	"Uttar Pradesh Power Corporation Ltd (UPPCL)": "UPPCL",
	"Uttar Pradesh Power Corporation Ltd": "UPPCL",
	"Uttar Pradesh Power Corporation Limited (UPPCL)": "UPPCL",
	"Uttarakhand Power Corporation Limited": "UTTARAKHAND POWER CORPORATION LIMITED",
	"Uttarakhand Power Corporation": "UTTARAKHAND POWER CORPORATION LIMITED",
	"Uttrakhand Power Corp Ltd": "UTTARAKHAND POWER CORPORATION LIMITED",
	"Uttrakhand Power Corp.Ltd": "UTTARAKHAND POWER CORPORATION LIMITED",
	"Vedanta Ltd_SEZ Unit_Jharsuguda": "Vedanta Limited SEZ UNIT, Jharsuguda",
	"West Bengal State Electricity Distribution Company Limited (WBSEDCL)": "WEST BENGAL STATE ELECTRICITY DISTRIBUTION COMPANY LIMITED",
	"West Central Railway": "WEST CENTRAL RAILWAY",
	
	"Uttarakhand Power Corporation Ltd": "UTTARAKHAND POWER CORPORATION LIMITED",
	# "Uttarakhand Power Corporation Limited (UPCL)": "UTTARAKHAND POWER CORPORATION LIMITED",
	"TPL-Ahmedabad Discom": "TPL-Ahmedabad Discom",
}

deep_data_mapping = {
	"JBVNL": "JHARKHAND BIJLI VITRAN NIGAM LIMITED",
	"CSPDL": "CHHATTISGARH STATE POWER DISTRIBUTION COMPANY LIMITED",
	"NUPLLP": "NIDAR UTILITIES PANVEL LLP",
	# "REMCL": "Railway Energy Management Company Limited",
	"LBSCML": "LAXMIPATI BALAJI SUPPLY CHAIN MANAGEMENT LIMITED",
	"RUVNL": "RAJASTHAN URJA VIKAS NIGAM LIMITED",
	"BSES": "BSES Rajdhani Power Limited",
	"BYPL": "BSES Yamuna Power Limited",
	"IPCL": "India Power Corporation Limited",
	"APPCC": "Andhra Pradesh Power Coordination Committee",
	"GUVNL": "Gujarat Urja Vikas Nigam Limited",
	"MSEZL": "Mangalore SEZ Limited",
	"APDCL": "ASSAM POWER DISTRIBUTION COMPANY LIMITED",
	# "MPPMCL": "Madhya Pradesh Power Management Company Limited",
	"PCKL": "Power Company of Karnataka Ltd",
	"PSPCL": "Punjab State Power Corporation Limited",
	"EON KHARADI INFRASTRUCTURE PVT LTD": "EON KHARADI INFRASTRUCTURE PRIVATE LIMITED, Phase -2",
	# "SEZ BIOTECH SERVICES PRIVATE LIMITED": "RAIPUR ENERGEN LIMITED",
	# "PFC Consulting Limited": "LAXMIPATI BALAJI SUPPLY CHAIN MANAGEMENT LIMITED",
	# "Sundew Properties Limited": "LAXMIPATI BALAJI SUPPLY CHAIN MANAGEMENT LIMITED",
	"TAMILNADU ELECTRICITY BOARD": "Tamil Nadu Electricity Board",
	"Andhra Pradesh Power Co-Ordination Committee (APPCC)": "Andhra Pradesh Power Coordination Committee",
	"TANGEDCO ltd": "TAMILNADU GENERATION AND DISTRIBUTION CORPORATION LIMITED",
	# "MADC LTD": "Maharashtra Airport Development Company Limited",
	# "RELIANCE ENERGY MUMBAI DISCOM": "TPL-Surat Discom",
	"UPCL": "UTTARAKHAND POWER CORPORATION LIMITED",
	"KSEBL": "KSEB",
	"MAHARASHTRA STATE ELECTRICITY CO LTD": "Maharashtra State Electricity Distribution Co Limited",
	"CESC": "CESC LIMITED",
	"HARYANA POWER PURCHASE CENTRE(A JOINT FORUM OF UHBVN&DHBVN)": "Haryana Power Purchase Centre",
	# "AEML": "AEML SEEPZ Limited",
	# "TPCL": "TPCL_U7 RLNG / The Tata Power Co Ltd (MTPS)",
	"TAMILNADU GENERATION AND DISTRIBUTION CORPN LTD": "TAMILNADU GENERATION AND DISTRIBUTION CORPORATION LIMITED",
	"HPSEBL": "HIMACHAL PRADESH STATE ELECTRICITY BOARD LIMITED",
	"BEST": "BEST Undertaking",
	"Chandigarh Electricity Department": "CHANDIGARH",
	"KRC Infrastructure and Projects Pvt Ltd": "KRC INFRASTRUCTURE AND PROJECTS PRIVATE LIMITED",
	"MP Power Management Company Ltd": "M.P. POWER MANAGEMENT COMPANY LIMITED",
	"Assam Power Distribution Company Ltd": "ASSAM POWER DISTRIBUTION COMPANY LIMITED",
	"Torrent Power Limited": "Torrent Power Limited - Dahej",
	"MPSEZ Utilities Private Limited": "MPSEZ Utilities Limited",
	"SOUTHERN POWER DISTRIBUTION COMPANY OF TELANGANA LTD": "SOUTHERN POWER DISTRIBUTION COMPANY OF TELANGANA LIMITED",
	"WEST BENGAL STATE ELECTRICITY DISTRIBUTION COMPANY LIMITED": "WEST BENGAL STATE ELECTRICITY DISTRIBUTION COMPANY LIMITED",
	"Noida Power Company Limited": "Noida Power Company limited",
	"JAWAHARLAL NEHRU PORT TRUST": "Jawaharlal Nehru Port Trust",
	"GUJARAT URJA VIKAS NIGAM LIMITED": "GUJARAT URJA VIKAS NIGAM LIMITED",
	"TATA POWER DELHI DISTRIBUTION LIMITED": "Tata Power Delhi Distribution Limited",
	"MINDSPACE BUSINESS PARKS PRIVATE LIMITED": "MINDSPACE BUSINESS PARKS PRIVATE LIMITED",
	"BSPHCL": "BSPHCL",
	"NIDP DEVELOPERS PRIVATE LIMITED": "NIDP DEVELOPERS PRIVATE LIMITED",
	"GRIDCO LIMITED": "GRIDCO LIMITED",
	"Gigaplex Estate Private Limited": "GIGAPLEX ESTATE PRIVATE LIMITED",
	'Andhra Pradesh Power Co-Ordination Committee (Andhra Pradesh Power Coordination Committee)': 'Andhra Pradesh Power Coordination Committee'
}

deep_tam_mapping = {
	"Adani Electricity Mumbai Limited": "Adani Electricity Mumbai Limited",
	"Andhra Pradesh Central Power Distribution Corp Ltd": "Andhra Pradesh Central Power Distribution Corporation Limited",
	"Andhra Pradesh Central Power Distribution Corp.ltd": "Andhra Pradesh Central Power Distribution Corporation Limited",
	"APDCL (Assam)": "ASSAM POWER DISTRIBUTION COMPANY LIMITED",
	"ArcelorMittal Nippon Steel India Limited": "ArcelorMittal Nippon Steel India Limited",
	"Bharat Aluminium Company Limited": "BHARAT ALUMINIUM COMPANY LTD",
	"Bharat Aluminum Company ltd (Bulk consumer)": "BHARAT ALUMINIUM COMPANY LTD (Bulk Consumer)",
	"BHARAT ALUMINIUM COMPANY LTD (Bulk Consumer)": "BHARAT ALUMINIUM COMPANY LTD (Bulk Consumer)",
	"Bihar State Power Holding Company Ltd Patna": "Bihar State Power (Holding) Company Limited",
	"Bihar State Power Holding Company Limited": "Bihar State Power (Holding) Company Limited",
	"Bihar State Power Holding Company": "Bihar State Power (Holding) Company Limited",
	"BSES Yamuna Power Limited (BYPL)": "BSES Yamuna Power Limited",
	"C.S.P.DISTRIBUTION_CO._LTD.": "CHHATTISGARH STATE POWER DISTRIBUTION COMPANY LIMITED",
	"Central Railways_Maharashtra": "Central Railway",
	# "Central Railway": "Central Railway",
	"CESC": "CESC LIMITED",
	"CESC Limited": "CESC LIMITED",
	"CSP Distribution  Company ltd": "CHHATTISGARH STATE POWER DISTRIBUTION COMPANY LIMITED",
	"CSP Distribution Co Ltd": "CHHATTISGARH STATE POWER DISTRIBUTION COMPANY LIMITED",
	"Dadra and Nagar Haveli and Daman and Diu Power Distribution Corporation Limited": "Dadra and Nagar Haveli and Daman and Diu Power Distribution Corporation Lim",
	"DNH Power Distribution Corporation Ltd": "DNH Beneficiary",
	# "DVC": "DVC",
	"Electricity Department_Government of Goa WR": "Electricity Department, GOA_WR",
	"Gift Power Company Ltd": "GIFT Power Company Limited",
	"Gigaplex Estate Private Limited": "GIGAPLEX ESTATE PRIVATE LIMITED",
	"Gigaplex Estate pvt ltd": "GIGAPLEX ESTATE PRIVATE LIMITED",
	"GRIDCO": "GRIDCO LIMITED",
	# "GRIDCO LIMITED": "GRIDCO LIMITED",
	"GUJARAT URJA VIKAS NIGAM LTD": "GUJARAT URJA VIKAS NIGAM LIMITED",
	"GUVNL": "GUJARAT URJA VIKAS NIGAM LIMITED",
	"Gujarat Urja Vikas Nigam Limited": "GUJARAT URJA VIKAS NIGAM LIMITED",
	"Himachal Pradesh State Electricity Board Ltd": "HIMACHAL PRADESH STATE ELECTRICITY BOARD LIMITED",
	"HPSEB": "HIMACHAL PRADESH STATE ELECTRICITY BOARD LIMITED",
	"Kerala State Electricity Board (KSEB)": "KERALA STATE ELECTRICITY BOARD LIMITED",
	"Kerala State Electricity Board Limited": "KERALA STATE ELECTRICITY BOARD  LIMITED",
	"KRC Infrastructure and Projects Pvt Ltd": "KRC INFRASTRUCTURE AND PROJECTS PRIVATE LIMITED",
	"KRC Infrastructure & Project Pvt Ltd": "KRC INFRASTRUCTURE AND PROJECTS PRIVATE LIMITED",
	"Maharashtra State Electricity Distribution Company Limited (MSEDCL)": "Maharashtra State Electricity Distribution Co Limited",
	"MSEDCL": "Maharashtra State Electricity Distribution Co Limited",
	"Mind Space business Park pvt ltd": "MINDSPACE BUSINESS PARKS PRIVATE LIMITED",
	"Mindspace Business Parks Pvt Ltd": "MINDSPACE BUSINESS PARKS PRIVATE LIMITED",
	"Mindspace Business Parks Private Limited": "MINDSPACE BUSINESS PARKS PRIVATE LIMITED",
	'New Delhi Municipal Council': "New Delhi Municipal Council",
	"New_Delhi_Municipal council_NDMC": "New Delhi Municipal Council",
	"Noida Power Company Limited": "Noida Power Company limited",
	"Noida power Company ltd": "Noida Power Company limited",
	"Noida Power Company.Ltd": "Noida Power Company limited",
	"NPCL": "Noida Power Company limited",
	"North Western Railway": "North Western Railway",
	"Northern  Railway  UP": "Northern Railway UP",
	"Northern  Railway UP": "Northern Railway UP",
	"Northern Railway UP": "Northern Railway UP",
	"NORTHERN RAILWAY UP": "Northern Railway UP",
	"Northern Railway": "Northern Railway",
	"Northern Railway Haryana": "Northern Railway-Haryana",
	"Power Company of Karnataka Limited -PCKL": "Power Company of Karnataka Ltd",
	"PCKL": "Power Company of Karnataka Ltd",
	# "Power Company of Karnataka Ltd": "Power Company of Karnataka Ltd",
	"Punjab State Power Corporation Ltd (PTC)": "Punjab State Power Corporation Limited",
	"Rajasthan Urja Vikas Nigam Ltd (RUVNL)": "RAJASTHAN URJA VIKAS NIGAM LIMITED",
	"Rajasthan Urja Vikas Nigam Ltd": "RAJASTHAN URJA VIKAS NIGAM LIMITED",
	"Rajasthan Urja Vikas Nigam .ltd": "RAJASTHAN URJA VIKAS NIGAM LIMITED",
	"Rajasthan Urja Vikas Nigam Limited": "RAJASTHAN URJA VIKAS NIGAM LIMITED",
	"RUVNL": "RAJASTHAN URJA VIKAS NIGAM LIMITED",
	"South Western Railway": "South Western Railway",
	"South  Western  Railway": "South Western Railway",
	"South  Western Railway": "South Western Railway",
	"Southern Power Distribution Company of Telangana Limited": "SOUTHERN POWER DISTRIBUTION COMPANY OF TELANGANA LIMITED",
	"Southern Power Distribution Company of Telangana Limited (TSSPDCL)": "SOUTHERN POWER DISTRIBUTION COMPANY OF TELANGANA LIMITED",
	"Tamilnadu Generation and Distribution Corporation Limited": "TAMILNADU GENERATION AND DISTRIBUTION CORPORATION LIMITED",
	"Tamil Nadu  Generation and Distribution Corporation Limited": "TAMILNADU GENERATION AND DISTRIBUTION CORPORATION LIMITED",
	"Tamilnadu Generation and Dist. Corp. Ltd TANGEDCO": "TAMILNADU GENERATION AND DISTRIBUTION CORPORATION LIMITED",
	"TANGEDCO": "TAMILNADU GENERATION AND DISTRIBUTION CORPORATION LIMITED",
	# "Torrent Power Ahmedabad": "Torrent Power Ahmedabad",
	"TORRENT POWER LIMITED - AHMEDABAD DISTRIBUTION": "Torrent Power Ahmedabad",
	"Torrent Power Limited - Dahej Distribution": "Torrent Power Limited - Dahej",
	"TORRENT POWER LIMITED - SURAT DISTRIBUTION": "Torrent Power Surat",
	"Torrent Power Ltd Surat": "Torrent Power Surat",
	"Torrent Power Limited- Dahej": "Torrent Power Limited - Dahej",
	"Torrent Power Ltd Dahej": "Torrent Power Limited - Dahej",
	# "Torrent Power Surat": "Torrent Power Surat",
	"U P Power Corporation Ltd": "UPPCL",
	"Uttar Pradesh Power Corporation Ltd (UPPCL)": "UPPCL",
	"Uttar Pradesh Power Corporation Ltd": "UPPCL",
	"Uttar Pradesh Power Corporation Limited (UPPCL)": "UPPCL",
	"Uttarakhand Power Corporation Limited": "UTTARAKHAND POWER CORPORATION LIMITED",
	"Uttarakhand Power Corporation": "UTTARAKHAND POWER CORPORATION LIMITED",
	"Uttrakhand Power Corp Ltd": "UTTARAKHAND POWER CORPORATION LIMITED",
	"Uttrakhand Power Corp.Ltd": "UTTARAKHAND POWER CORPORATION LIMITED",
	"Vedanta Ltd_SEZ Unit_Jharsuguda": "Vedanta Limited SEZ UNIT, Jharsuguda",
	"West Bengal State Electricity Distribution Company Limited (WBSEDCL)": "WEST BENGAL STATE ELECTRICITY DISTRIBUTION COMPANY LIMITED",
	"West Central Railway": "WEST CENTRAL RAILWAY",
	
	"Uttarakhand Power Corporation Ltd": "UTTARAKHAND POWER CORPORATION LIMITED",
	# "Uttarakhand Power Corporation Limited (UPCL)": "UTTARAKHAND POWER CORPORATION LIMITED",
	"TPL-Ahmedabad Discom": "TPL-Ahmedabad Discom",
	
	"JBVNL": "JHARKHAND BIJLI VITRAN NIGAM LIMITED",
	"CSPDL": "CHHATTISGARH STATE POWER DISTRIBUTION COMPANY LIMITED",
	"NUPLLP": "NIDAR UTILITIES PANVEL LLP",
	# "REMCL": "Railway Energy Management Company Limited",
	"LBSCML": "LAXMIPATI BALAJI SUPPLY CHAIN MANAGEMENT LIMITED",
	"RUVNL": "RAJASTHAN URJA VIKAS NIGAM LIMITED",
	"BSES": "BSES Rajdhani Power Limited",
	"BYPL": "BSES Yamuna Power Limited",
	"IPCL": "India Power Corporation Limited",
	"APPCC": "Andhra Pradesh Power Coordination Committee",
	"GUVNL": "Gujarat Urja Vikas Nigam Limited",
	"MSEZL": "Mangalore SEZ Limited",
	"APDCL": "ASSAM POWER DISTRIBUTION COMPANY LIMITED",
	# "MPPMCL": "Madhya Pradesh Power Management Company Limited",
	"PCKL": "Power Company of Karnataka Ltd",
	"PSPCL": "Punjab State Power Corporation Limited",
	"EON KHARADI INFRASTRUCTURE PVT LTD": "EON KHARADI INFRASTRUCTURE PRIVATE LIMITED, Phase -2",
	# "SEZ BIOTECH SERVICES PRIVATE LIMITED": "RAIPUR ENERGEN LIMITED",
	# "PFC Consulting Limited": "LAXMIPATI BALAJI SUPPLY CHAIN MANAGEMENT LIMITED",
	# "Sundew Properties Limited": "LAXMIPATI BALAJI SUPPLY CHAIN MANAGEMENT LIMITED",
	"TAMILNADU ELECTRICITY BOARD": "Tamil Nadu Electricity Board",
	"Andhra Pradesh Power Co-Ordination Committee (APPCC)": "Andhra Pradesh Power Coordination Committee",
	"TANGEDCO ltd": "TAMILNADU GENERATION AND DISTRIBUTION CORPORATION LIMITED",
	# "MADC LTD": "Maharashtra Airport Development Company Limited",
	# "RELIANCE ENERGY MUMBAI DISCOM": "TPL-Surat Discom",
	"UPCL": "UTTARAKHAND POWER CORPORATION LIMITED",
	"KSEBL": "KSEB",
	"MAHARASHTRA STATE ELECTRICITY CO LTD": "Maharashtra State Electricity Distribution Co Limited",
	"CESC": "CESC LIMITED",
	"HARYANA POWER PURCHASE CENTRE(A JOINT FORUM OF UHBVN&DHBVN)": "Haryana Power Purchase Centre",
	# "AEML": "AEML SEEPZ Limited",
	# "TPCL": "TPCL_U7 RLNG / The Tata Power Co Ltd (MTPS)",
	"TAMILNADU GENERATION AND DISTRIBUTION CORPN LTD": "TAMILNADU GENERATION AND DISTRIBUTION CORPORATION LIMITED",
	"HPSEBL": "HIMACHAL PRADESH STATE ELECTRICITY BOARD LIMITED",
	"BEST": "BEST Undertaking",
	"Chandigarh Electricity Department": "CHANDIGARH",
	"KRC Infrastructure and Projects Pvt Ltd": "KRC INFRASTRUCTURE AND PROJECTS PRIVATE LIMITED",
	"MP Power Management Company Ltd": "M.P. POWER MANAGEMENT COMPANY LIMITED",
	"Assam Power Distribution Company Ltd": "ASSAM POWER DISTRIBUTION COMPANY LIMITED",
	"Torrent Power Limited": "Torrent Power Limited - Dahej",
	"MPSEZ Utilities Private Limited": "MPSEZ Utilities Limited",
	"SOUTHERN POWER DISTRIBUTION COMPANY OF TELANGANA LTD": "SOUTHERN POWER DISTRIBUTION COMPANY OF TELANGANA LIMITED",
	"WEST BENGAL STATE ELECTRICITY DISTRIBUTION COMPANY LIMITED": "WEST BENGAL STATE ELECTRICITY DISTRIBUTION COMPANY LIMITED",
	"Noida Power Company Limited": "Noida Power Company limited",
	"JAWAHARLAL NEHRU PORT TRUST": "Jawaharlal Nehru Port Trust",
	"GUJARAT URJA VIKAS NIGAM LIMITED": "GUJARAT URJA VIKAS NIGAM LIMITED",
	"TATA POWER DELHI DISTRIBUTION LIMITED": "Tata Power Delhi Distribution Limited",
	"MINDSPACE BUSINESS PARKS PRIVATE LIMITED": "MINDSPACE BUSINESS PARKS PRIVATE LIMITED",
	"BSPHCL": "BSPHCL",
	"NIDP DEVELOPERS PRIVATE LIMITED": "NIDP DEVELOPERS PRIVATE LIMITED",
	"GRIDCO LIMITED": "GRIDCO LIMITED",
	"Gigaplex Estate Private Limited": "GIGAPLEX ESTATE PRIVATE LIMITED",
	'Andhra Pradesh Power Co-Ordination Committee (Andhra Pradesh Power Coordination Committee)': 'Andhra Pradesh Power Coordination Committee'
}
