state_mapping = {
    "Rajasthan": "Rajasthan",
    "Madhya Pradesh": "Madhya Pradesh",
    "Meghalaya": "Meghalaya",
    "Odisha": "Odisha",
    "Telangana": "Telangana",
    "Delhi": "Delhi",
    "Andhra Pradesh": "Andhra Pradesh",
    "Tamil Nadu": "Tamil Nadu",
    "Tripura": "Tripura",
    "Goa": "Goa",
    "Uttar Pradesh": "Uttar Pradesh",
    "Punjab": "Punjab",
    "Haryana": "Haryana",
    "Jharkhand": "Jharkhand",
    "Mizoram": "Mizoram",
    "Karnataka": "Karnataka",
    "West Bengal": "West Bengal",
    "Himachal Pradesh": "Himachal Pradesh",
    "Nagaland": "Nagaland",
    "Uttarakhand": "Uttarakhand",
    "Arunachal Pradesh": "Arunachal Pradesh",
    "Manipur": "Manipur",
    "Maharashtra": "Maharashtra",
    "Sikkim": "Sikkim",
    "Chhattisgarh": "Chhattisgarh",
    "Assam": "Assam",
    "Gujarat": "Gujarat",
    "Kerala": "Kerala",
    "Bihar": "Bihar",
    "Chandigarh": "Chandigarh",
    "Puducherry": "Puducherry",
    "Jammu and Kashmir": "Jammu and Kashmir",
    "Himachal Prades": "Himachal Pradesh",
    "Madhya Pradhesh": "Madhya Pradesh",
    "Arunachal Prades": "Arunachal Pradesh",
    "Himanchal Pradesh": "Himachal Pradesh",
    "Andhara Pradesh": "Andhra Pradesh",
    "Andhrai Pradesh": "Andhra Pradesh",
    "Himachal\n Pradesh": "Himachal Pradesh",
    "Madhya\n Pradesh": "Madhya Pradesh",
    "Arunachal\n Pradesh": "Arunachal Pradesh",
    "Chhatisgarh": "Chhattisgarh",
    "West  Bengal": "West Bengal",
    "Chattisgarh": "Chhattisgarh",
    "W est Bengal": "West Bengal",
    "Chhattisga rh": "Chhattisgarh",
    "Uttar Pradhesh": "Uttar Pradesh",
    "Andhra Prades": "Andhra Pradesh",
    "Chhattisg arh": "Chhattisgarh",
    "Uttarakh and": "Uttarakhand",
    "Uttar Prades h": "Uttar Pradesh",
    "Chhattishgarh": "Chhattisgarh",
    "Chhattisga\nrh": "Chhattisgarh",
    "Chhattisgar h": "Chhattisgarh",
    "Chhattisgharh": "Chhattisgarh",
    "Uttar Pradaesh": "Uttar Pradesh",
    "Maharashtr a": "Maharashtra",
    "Maharashtr\na": "Maharashtra",
    "hhattisgarh": "Chhattisgarh",
    "Madhya Prades": "Madhya Pradesh",
    "ndhra Pradesh": "Andhra Pradesh",
    "Chhattisg\narh": "Chhattisgarh",
    "Chhattisgar": "Chhattisgarh",
    "MadhyaPradesh": "Madhya Pradesh",
    "West Benagal": "West Bengal",
    "Uttar\n Pradesh": "Uttar Pradesh",
    "Maharastra": "Maharashtra",
    "Uttrakhand": "Uttarakhand",
    "TamilNadu": "Tamil Nadu",
    "Karnatak a": "Karnataka",
    "WestBengal": "West Bengal",
    "West Benga": "West Bengal",
    "Telangan\na": "Telangana",
    "Maharshtra": "Maharashtra",
    "Meghalaya ": "Meghalaya",
    "Meghalay": "Meghalaya",
    "Himachal\nPradesh": "Himachal Pradesh",
    "Rajsthan": "Rajasthan",
    "Karnatka": "Karnataka",
    "Himachal Predesh": "Himachal Pradesh",
    "runachal Prades": "Arunachal Pradesh",
    "Jammu And Kashmir": "Jammu and Kashmir",
    "Meghalya": "Meghalaya",
    "Himachal Praedsh": "Himachal Pradesh",
    "Karnatak": "Karnataka",
    "Arunachal\nPradesh": "Arunachal Pradesh",
    "himachal Pradesh": "Himachal Pradesh",
    "Himachal pradesh": "Himachal Pradesh",
    "Madhya\nPradesh": "Madhya Pradesh",
    "Madhya pradesh": "Madhya Pradesh",
    "madhya Pradesh": "Madhya Pradesh",
    "Andhra\nPradesh": "Andhra Pradesh",
    "Himachal Prade": "Himachal Pradesh",
    "Andhra pradesh": "Andhra Pradesh",
    "Madhya  Prades": "Madhya Pradesh",
    "Madhva Pradesh": "Madhya Pradesh",
    "Madhya Pradosh": "Madhya Pradesh",
    "Gujarat ": "Gujarat",
    "andhra Pradesh": "Andhra Pradesh",
    "Gujrat": "Gujarat",
    "Uttar\nPradesh": "Uttar Pradesh",
    "Chattishgarh": "Chhattisgarh",
    "Sikkim/ER": "Sikkim",
    "Uttar pradesh": "Uttar Pradesh",
    "Andhra Prade": "Andhra Pradesh",
    "Odisha ": "Odisha",
    "Chhattisagrh": "Chhattisgarh",
    "Madhya Prade": "Madhya Pradesh",
    "Odish a": "Odisha",
    "Uttar Pradosh": "Uttar Pradesh",
    "Uttar Pracesh": "Uttar Pradesh",
    "Uttar Predesh": "Uttar Pradesh",
    " Punjab": "Punjab",
    "Punja b": "Punjab",
    "Utter Pradesh": "Uttar Pradesh",
    " Odisha": "Odisha",
    "West BengaL": "West Bengal",
    "West\nBengal": "West Bengal",
    "West bengal": "West Bengal",
    "West Bangal": "West Bengal",
    "West Benaal": "West Bengal",
    "Odsha": "Odisha",
    "Maharashrra": "Maharashtra",
    "west Bengal": "West Bengal",
    "Tamil nadu": "Tamil Nadu",
    "Tamil\nNadu": "Tamil Nadu",
    "Maharasht": "Maharashtra",
    "Uttarakha": "Uttarakhand",
    "nachal Pradesh": "Arunachal Pradesh",
    "Himachal Prad": "Himachal Pradesh",
    "AAadhya Pradesh": "Madhya Pradesh",
    "Madhya Pradesh/WR": "Madhya Pradesh",
    "Uttar Pradesh/NR": "Uttar Pradesh",
    "meghalaya": "Meghalaya",
    "karnataka": "Karnataka",
    "Chhattisgarh rh": "Chhattisgarh",
    "Maghalaya": "Meghalaya",
    "Chhattisgarh\nrh": "Chhattisgarh",
    "KArnataka": "Karnataka",
    "Telengana": "Telangana",
    "Madhya Pradei": "Madhya Pradesh",
    "Madhya Prade<": "Madhya Pradesh",
    "Jammu & Kashmir": "Jammu and Kashmir",
    "Andhra Prad": "Andhra Pradesh",
    "adhya Prade": "Madhya Pradesh",
    "ndhra Prade": "Andhra Pradesh",
    "West Bengal/ER": "West Bengal",
    "Maharashtra ra": "Maharashtra",
    "Himanchal Prad": "Himachal Pradesh",
    "Uttar Prad": "Uttar Pradesh",
    "Jammu Kashmir": "Jammu and Kashmir",
    "Chhattisagr": "Chhattisgarh",
    "Chattisaarh": "Chhattisgarh",
    "MadhyaPradesh/WR": "Madhya Pradesh",
    "Madhya\npradesh": "Madhya Pradesh",
    "gujarat": "Gujarat",
    "Guiarat": "Gujarat",
    "Karnataka/SR": "Karnataka",
    "UttarPradesh/NR": "Uttar Pradesh",
    "Chhattisg": "Chhattisgarh",
    "GUjarat": "Gujarat",
    "DVC\nWest Bengal": "West Bengal",
    "andhra Prade": "Andhra Pradesh",
    "madhya Prade": "Madhya Pradesh",
    "Jammu  & Kashmir": "Jammu and Kashmir",
    "Chhatisgarh/WR": "Chhattisgarh",
    "Madhya Pradt": "Madhya Pradesh",
    "Tamilnadu": "Tamil Nadu",
"Jammu &Kashmir": "Jammu and Kashmir",
    "Madhya\nPradesh/WR": "Madhya Pradesh",
    "Kerela": "Kerala",
    "Odissa": "Odisha",
    "sikkim": "Sikkim",
    "odisha": "Odisha",
    "Andhra Pra": "Andhra Pradesh",
    "Odhisa": "Odisha",
    "Siikim": "Sikkim",
    "Odtsha": "Odisha",
    "Odishn": "Odisha",
    "Odlsha": "Odisha",
    "WestBengal/ER": "West Bengal",
    "Uttar\nPradesh/NR": "Uttar Pradesh",
    "Maharastra/WR": "Maharashtra",
    "kerala": "Kerala",
    "Arunachal Pr": "Arunachal Pradesh",
    "west bengal": "West Bengal",
    "karnatka": "Karnataka",
    "Mabarashzra": "Maharashtra",
    "WB, Jharkhand": "Jharkhand",
    "Madhya Pradesh/WRLDC": "Madhya Pradesh",
    "Gujarat/WR": "Gujarat",
    "Andhra Pradesh/SRLDC": "Andhra Pradesh",
    "Jammu & kashmir": "Jammu and Kashmir",
    "Arunachal Pradesh (Assam)": "Arunachal Pradesh (Assam)",
    "delhi": "Delhi",
    "DElhi": "Delhi",
    "Tamilnad u": "Tamil Nadu",
    "Jammu and_x000D_Kashmir": "Jammu and Kashmir",
    "Uttarpardesh": "Uttar Pradesh",
    "TAMil Nadu": "Tamil Nadu",
    "Tamilanadu": "Tamil Nadu",
    "Delhi(Andhra Pradesh)": "Delhi (Andhra Pradesh)",
    "B-har": "Bihar",
    "Briar": "Bihar",
    "Sikkim/ER": "Sikkim",
    "Odisha/ER": "Odisha",
    "Punjab/NR": "Punjab",
    "Himachal_x000D_Pradesh": "Himachal Pradesh",
    "Arunachal Pradesh (Sikkim)": "Arunachal Pradesh (Sikkim)",
    "Madhya PradESH": "Madhya Pradesh",
    "Meghayala": "Meghalaya",
    "Uttarprade": "Uttar Pradesh",
    "Madhya Pr": "Madhya Pradesh",
    "Haryana DVC": "Haryana",
    "For Haryana": "Haryana",
    "Tamilnad": "Tamil Nadu",
    "Telangana SLDC": "Telangana",
    "dhya Prad": "Madhya Pradesh",
    "Himachal P": "Himachal Pradesh",
    "Chhattisgar_x000D_h": "Chhattisgarh",
    "Arunachal Pradesh (Manipur)": "Arunachal Pradesh (Manipur)",
    "Tamil Nadu/SRLDC": "Tamil Nadu",
    "Delhi/NR": "Delhi",
    "Bihar/ER": "Bihar",
    "Raipur": "Manipur",
    "achal Prad": "Himachal Pradesh",
    "Andhra_x000D_Pradesh": "Andhra Pradesh",
    "Madhya_x000D_Pradesh": "Madhya Pradesh",
    "Arunachal Pradesh (Himachal)": "Arunachal Pradesh (Himachal Pradesh)",
    "Delhi(West Bengal)": "Delhi (West Bengal)",
    "Delhi(Maharashtra)": "Delhi (Maharashtra)",
    "arnil Nadu": "Tamil Nadu",
    "Chhattisagrh": "Chhattisgarh",
    "Uttar_x000D_Pradesh": "Uttar Pradesh",
    "Telangana/SRLDC": "Telangana",
    "KeralaSLDC": "Kerala",
    "Hiamchal_x000D_Pradesh": "Himachal Pradesh",
    "Cdsha": "Odisha",
    "Dadra and Nagar Havel i": "Dadra and Nagar Haveli and Daman and Diu",
    "uttarpardesh": "Uttar Pradesh",
    "Haryana (Uttar Pradesh)": "Haryana",
    "Madhya_x000D_pradesh": "Madhya Pradesh",
    "Dadra and Nagar Haveli": "Dadra and Nagar Haveli and Daman and Diu",
    "Odisha SLDC": "Odisha",
    "Guiaiat": "Gujarat",
    "Assam/NER": "Assam",
    "New Delhi": "Delhi",
    "Pradesh": "Uttar Pradesh",
    "Gujarat/WRLDC": "Gujarat",
    "Telangana Haryana": "Telangana",
    "Haryana (West Bengal)": "Haryana",
    "Andhra State": "Andhra Pradesh",
    "Dadra and Nagar Haveli (UT)": "Dadra and Nagar Haveli and Daman and Diu",
    "Jammu &_x000D_Kashmir": "Jammu and Kashmir",
    "Arunachal Pradesh (Uttar Pradesh)": "Arunachal Pradesh",
    "GoA": "Goa",
    "Orissa": "Odisha",
    "Himachal": "Himachal Pradesh",
    "Orrisa": "Odisha",
    "Arunachal Pradesh (Andhra Pradesh)": "Arunachal Pradesh",
    "Delhi(Haryana)": "Delhi",
    "Odftha": "Odisha",
    "Debi": "Delhi",
    "Gon": "Goa",
    "Manipur/NERLDC": "Manipur",
    "Tamil": "Tamil Nadu",
    "Dadra and\nNagar Haveli (UT)": "Dadra and Nagar Haveli and Daman and Diu",
    "Dadra\nand Nagar Haveli (UT)": "Dadra and Nagar Haveli and Daman and Diu",
    "Dadar And Nagar Haveli": "Dadra and Nagar Haveli and Daman and Diu",
    "West Bengal (Uttar Pradesh)": "West Bengal (Uttar Pradesh)",
    "adra and Nagar Have": "Dadra and Nagar Haveli and Daman and Diu",
    "Haryana (Meghalaya)": "Haryana (Meghalaya)",
    "Dadra & Nagar Haveli": "Dadra and Nagar Haveli and Daman and Diu",
    "Odisha Odisha": "Odisha",
    "Dadra Nagar Haveli": "Dadra and Nagar Haveli and Daman and Diu",
    "UTTAR\nPradesh": "Uttar Pradesh",
    "Uttar": "Uttarakhand",
    "Dadara & Nagar Haveli": "Dadra and Nagar Haveli and Daman and Diu",
    "Tamil Nadu & Rajasthan": "Tamil Nadu",
    "Dadra & Nagar Havel": "Dadra and Nagar Haveli and Daman and Diu",
    "Dad ar Nagar Haveli": "Dadra and Nagar Haveli and Daman and Diu",
    "Haryana (Orrisa)": "Haryana (Odisha)",
    "Andhra": "Andhra Pradesh",
    "Dadra & Nagar\nHaveli": "Dadra and Nagar Haveli and Daman and Diu",
    "Dadra &\nNagar Haveli": "Dadra and Nagar Haveli and Daman and Diu",
    "Dadra\n& Nagar Haveli": "Dadra and Nagar Haveli and Daman and Diu",
    "Deltv": "Delhi",
    "Dadar Nagar Haveli": "Dadra and Nagar Haveli and Daman and Diu",
    "adra and Nagar Haw": "Dadra and Nagar Haveli and Daman and Diu",
    "Dadra Nager Haveli": "Dadra and Nagar Haveli and Daman and Diu",
    "adra And Nagar have": "Dadra and Nagar Haveli and Daman and Diu",
    "Haryana (Manipur)": "Haryana (Manipur)",
    "Arunach": "Arunachal Pradesh",
    "Dadar &\nNagar Haveli": "Dadra and Nagar Haveli and Daman and Diu",
    "Daman and Diu\n- Dadra and Nagar Haveli": "Dadra and Nagar Haveli and Daman and Diu",


    "Uttarpradesh": "Uttar Pradesh",
    "Himachal Pradesh/SR": "Himachal Pradesh",
    "Chhattishgarh/WR": "Chhattisgarh",
    "Andrapradesh": "Andhra Pradesh",
    "Chhatisgarh ": "Chhattisgarh",
    "Rajasthan/NR": "Rajasthan",
    "Chhattisgar/SR": "Chhattisgarh",
    "Madhya\nPardesh": "Madhya Pradesh",
    "Andhra Prade sh": "Andhra Pradesh",
    "andhra pradesh": "Andhra Pradesh",
    "west  bengal": "West Bengal",
    "Karanataka": "Karnataka",
    "utttar Pradesh": "Uttar Pradesh",
    "Punjab /NR": "Punjab",
    "TamilNadu/SR": "Tamil Nadu",
    "Tamil Nadu/SR": "Tamil Nadu",
    "Himachal pradesh/SR": "Himachal Pradesh",
    "andhra  Pradesh": "Andhra Pradesh",
    "madhya  Pradesh": "Madhya Pradesh",
    "Madhya Pradesh/SR": "Madhya Pradesh",
    "Jammu and  Kashmir": "Jammu and Kashmir",
    "AndhraPradesh/SR": "Andhra Pradesh",
    "Tamilnadu/SR": "Tamil Nadu",
    "Uttarpradesh/NR": "Uttar Pradesh",
    "Chhattishgarh/ SR": "Chhattisgarh",
    "DVC/West Bengal": "West Bengal",
    "Chattisgarh/WR": "Chhattisgarh",
    "Jammu  &Kashmir": "Jammu and Kashmir",
    "andhrapradesh": "Andhra Pradesh",
    "Haryana\nDVC": "Haryana",
    "Telangana\nSLDC": "Telangana",
    "Telangana\nHaryana": "Telangana",
    "Dadra and Nagar Haveli\n(UT)": "Dadra and Nagar Haveli and Daman and Diu",
    "Daman and Diu - Dadra and Nagar Haveli": "Dadra and Nagar Haveli and Daman and Diu",
    "Bangladesh": "Bangladesh",
    "Haryana (Himachal)": "Haryana (Himachal Pradesh)",
    "Delhi (Nepal)": "Delhi (Nepal)",
    "Daman and Diu -\n Dadra and Nagar Haveli": "Dadra and Nagar Haveli and Daman and Diu",
    "Daman and Diu - Dadra and Nagar\n Haveli": "Dadra and Nagar Haveli and Daman and Diu",
    "Bhutan": "Bhutan",
    "Dadra and Nagar": "Dadra and Nagar Haveli and Daman and Diu",
    "Nepal": "Kerala",
    "Haryana (AAeghalaya)": "Haryana (Meghalaya)",
    "Daman and Diu - Dadra and Nagar\nHaveli": "Dadra and Nagar Haveli and Daman and Diu",
    "HIMACHAL pradesh": "Himachal Pradesh",
    "Hyderabad": "Hyderabad",
    "Daman and Diu": "Dadra and Nagar Haveli and Daman and Diu",
    "for Bangladesh": "Bangladesh",
    "Delhi(Himachal)": "Delhi (Himachal Pradesh)",
    "Daman and Diu UT": "Dadra and Nagar Haveli and Daman and Diu",
    "Chennai": "Chennai",
    "Dadra & Na": "Dadra and Nagar Haveli and Daman and Diu",
    "Tangedco": "Tangedco",
    "Mumbai": "Mumbai",
    "Discom": "Discom",
    "Jammu": "Jammu and Kashmir",
    "Daman & Diu": "Dadra and Nagar Haveli and Daman and Diu",
    "Daman &\nDiu": "Dadra and Nagar Haveli and Daman and Diu",
    "Solar\nProjects": "Solar Projects",
    "Orissa/ERLDC": "Odisha",
    "biiutan": "Bhutan",
    "a & Nagar H": "Dadra and Nagar Haveli and Daman and Diu",
    "DADRA Nagar": "Dadra and Nagar Haveli and Daman and Diu",
    "bhutan": "Bhutan",
    "Dadra & N": "Dadra and Nagar Haveli and Daman and Diu",
    "Orissa       ,": "Odisha",
    "U P": "Uttar Pradesh",
    "J & K": "Jammu and Kashmir",
    "Damodar Valley Corporation/ER": "Dadra and Nagar Haveli and Daman and Diu",
    "Depending on Source": "Depending on Source",
    "GOA": "Goa",
    "Damodar VallyCorporation/ER": "Damodar Vally Corporation",
    "GCA": "Goa",
    "WB": "West Bengal",
    "TAMIL NADU": "Tamil Nadu",
    "WEST BENGAL": "West Bengal",
    "ISGS": "ISGS",
    "TELANGANA a": "Telangana",
    "TAMNIL NADU": "Tamil Nadu",
    "AP": "AP",
    "MeECL": "MeECL",
    "for NEA": "for NEA",
    "RAJASTHAN N": "Tamil Nadu",
    "UTTAR PRA": "Uttar Pradesh",
    "UP": "Uttar Pradesh",
    "Bharat Aluminium Company                                        Chhattisgarh": "Bharat Aluminium Company                                        Chhattisgarh",
    "DADRA & NAGAR HAVELI": "Dadra and Nagar Haveli and Daman and Diu",
    "UTTAR PRAD": "Uttar Pradesh",
    "BHUTAN": "Bhutan",
    "JAMMU & KASHMIR": "Jammu and Kashmir",
    "DNH": "DNH",
    "HP": "Himachal Pradesh",
    "DVC": "DVC",
    "MP": "Madhya Pradesh",
    "SR": "SR",
    "ANDHRA PRA": "Andhra Pradesh",
    "KR": "KR",
    "HIMACHAL PR": "Himachal Pradesh",
    "DADRA AND NAGAR HAVELI": "Dadra and Nagar Haveli and Daman and Diu",
    "M.P": "Madhya Pradesh",
    "DRA & NAGAR HAV": "Dadra and Nagar Haveli and Daman and Diu",
    "TTAR PRADES": "Uttar Pradesh",
    "ADHYA PRADE": "Madhya Pradesh",
    "NDHRA PRADE": "Andhra Pradesh",
    "WBSLDC": "West Bengal",
    "UTTAR PRADESH": "Uttar Pradesh",
    "ADRA & NAGAR HAVE": "Dadra and Nagar Haveli and Daman and Diu",
    "DADRA & NAGAR HA": "Dadra and Nagar Haveli and Daman and Diu",
    "MADHYA PRADES": "Madhya Pradesh",
    "GUJRAT": "Gujarat",
    "TAMILNAD": "Tamil Nadu",
    "DAMAN& DIU": "Dadra and Nagar Haveli and Daman and Diu",
    "J&K": "Jammu and Kashmir",
    "PSEB": "Punjab",
    "ASEB": "Assam",
    "GJSLDC": "GJSLDC",
    "CSEB": "CSEB",
    "BSEB": "BSEB",
    "RAJASTHAN": "Rajasthan",
    "ANDHRA PRADESH": "Andhra Pradesh",
    "MADHYA PRADESH": "Madhya Pradesh",
    "TELANGANA": "Telangana",
    "TELENGANA": "Telangana",
    "TAMILNADU": "Tamil Nadu",
    "DAMAN & DIU": "Dadra and Nagar Haveli and Daman and Diu",
    "UTTAR PRADESH H": "Uttar Pradesh",
    "UPSLDC": "Uttar Pradesh",
    "DELHI": "Delhi",
    "GUJARAT": "Gujarat",
    "HIMACHAL PRADESH": "Himachal Pradesh",
    "BIHAR": "Bihar",
    "ASSAM": "Assam",
    "NEPAL": "Nepal",
    "Solar Projects located in Rajasthan, Punjab, Uttar Pradesh, Karnataka\n, Orissa,\nAndhra Pradesh, Tamil Nadu, Maharash tra\n& Northern Region = FGUTPS- 1,2 3&4, NCTPS-2, RhTPS-1,2 &3, SSTPS-\n1 & Tanda_2, Western Region = KSTPS-1\n&3, MSTPS-\n1&2,": "Solar Projects",
    "Solar\nProjects located in Rajasthan, Punjab, Uttar Pradesh, Karnataka\n, Orissa, Andhra Pradesh, Tamil Nadu, Maharash tra\n& Northern Region = FGUTPS- 1,2 3&4, NCTPS-2, RhTPS-1,2 &3, SSTPS-\n1 & Tanda_2, Western Region = KSTPS-1\n&3,\nMSTPS- 1&2,": "Solar Projects",
    "Solar\nProjects located in Rajasthan, Punjab, Uttar Pradesh, Karnataka\n, Orissa, Andhra Pradesh, Tamil Nadu, Maharash tra\n& Northern Region = FGUTPS- 1,2 3&4, NCTPS-2, RhTPS-1,2 &3, SSTPS-1\n& Tanda_2, Western Region = KSTPS-1\n&3, MSTPS-\n1&2,": "Solar Projects",
    "Solar Projects located in Rajasthan, Punjab, Uttar Pradesh, Karnataka\n, Orissa, Andhra Pradesh, Tamil Nadu, Maharash tra\n& Northern Region = FGUTPS- 1,2 3&4, NCTPS-2, RhTPS-1,2 &3, SSTPS-\n1 & Tanda_2, Western Region = KSTPS-1\n&3,\nMSTPS- 1&2, SPTPS- 1&2,": "Solar Projects",
"Solar Projects located in Rajasthan, Punjab, Uttar Pradesh, Karnataka, Orissa, Andhra Pradesh, Tamil Nadu, Maharasht ra & Northern Region = FGUTPS- 1,2 3&4, NCTPS-2, RhTPS-1,2 &3, SSTPS-1 & Tanda_2, Western Region = KSTPS-1 &3, MSTPS- 1&2,": "Solar Projects",
    "MPPMCL": "Madhya Pradesh",
    "WESTBENGAL": "West Bengal",
    "JAMMU KASHMIR": "Jammu and Kashmir",
    "UTTRAKHAND": "Uttar Pradesh",
    "Solar Projects located in Rajasthan, Punjab, Uttar Pradesh, Karnataka , Orissa, Andhra Pradesh, Tamil Nadu, Maharash tra &  Northern Region = FGUTPS- 1,2 3&4, NCTPS-2, RhTPS-1,2 &3, SSTPS-1 & Tanda_2, Western Region = KSTPS-1 &3, MSTPS- 1&2,": "Solar Projects",
    "Solar Projects located in Rajasthan , Punjab, Uttar Pradesh, Karnataka , Orissa, Andhra Pradesh, Tamil Nadu, Maharash tra & Northern Region = FGUTPS- 1,2 3&4, NCTPS-2, RhTPS-1,2 &3, SSTPS-1 & Tanda_2, Western Region = KSTPS-1 &3, MSTPS- 1&2,": "Solar Projects",
    "MADHYA PRADESH H": "Madhya Pradesh",
    "Solar Projects located in Rajasthan, Punjab, Uttar Pradesh, Karnataka , Orissa, Andhra Pradesh, Tamil Nadu, Maharasht ra & Northern Region = FGUTPS- 1,2 3&4, NCTPS-2, RhTPS- 1,2 &3, SSTPS-1, Western Region = KSTPS-1 &3, MSTPS- 1&2, SPTPS- 1&2, SLTPS-": "Solar Projects",
    "MADHYA PRADESH H": "Madhya Pradesh",
    "RYANA": "Haryana",
    "ANDHRA PRADESH H": "Andhra Pradesh",
    "APSLDC": "APSLDC",
    "WEST": "West Bengal",
    "UTTARAKHAND": "Uttarakhand",
    "JAMMU & KASHMIR": "Jammu and Kashmir",
    "Solar Projects located in Rajasthan , Punjab, Uttar Pradesh, Karnataka , Orissa, Andhra Pradesh, Tamil Nadu, Maharash tra &  Northern Region = FGUTPS- 1,2 3&4, NCTPS-2, RhTPS-1,2 &3, SSTPS-1 & Tanda_2, Western Region = KSTPS-1 &3, MSTPS- 1&2, SPTPS- 1&2,": "Solar Projects",
    "JAMMU& KASHMIR": "Jammu and Kashmir",
    "TELANGANA A": "Telangana",
    "MANIPUR": "Manipur",
    "WEST BENGAL": "West Bengal",
    "Solar Projects located in Rajasthan, Punjab, Uttar Pradesh, Karnataka , Orissa, Andhra Pradesh, Tamil Nadu, Maharasht ra & Northern Region = FGUTPS- 1,2 3&4, NCTPS-2, RhTPS- 1,2 &3, SSTPS-1 & Tanda_2, Western Region = KSTPS-1 &3, MSTPS- 1&2, SPTPS- 1&2, SLTPS-": "Solar Projects",
    "Solar Projects located in Rajasthan , Punjab, Uttar Pradesh, Karnataka , Orissa, Andhra Pradesh, Tamil Nadu, Maharasht ra & Northern Region = FGUTPS- 1,2 3&4, NCTPS-2, RhTPS- 1,2 &3, SSTPS-1 & Tanda_2, Western Region = KSTPS-1 &3, MSTPS- 1&2, SPTPS- 1&2, SLTPS-": "Solar Projects",
    "Projects located in Rajasthan, Punjab, Uttar Pradesh, Karnataka , Orissa, Andhra Pradesh, Tamil Nadu, Maharash tra & Northern Region = FGUTPS- 1,2 3&4, NCTPS-2, RhTPS-1,2 &3, SSTPS- 1 & Tanda_2, Western Region = KSTPS-1 &3, MSTPS- 1&2, SPTPS-": "Solar Projects",
    "JAMMU & KASHMIR": "Jammu and Kashmir",
    "HIMANCHAL PRADESH": "Himachal Pradesh",
    "ADRA NAGAR HAVE": "Dadra and Nagar Haveli and Daman and Diu",
    "HIMACHAL PRADES H": "Himachal Pradesh",
    "HIMACHAL PRADESH H": "Himachal Pradesh",
    "Solar Projects located in Rajasthan, Punjab, Uttar Pradesh, Karnataka , Orissa, Andhra Pradesh, Tamil Nadu, Maharasht ra &  Northern Region = FGUTPS- 1,2 3&4, NCTPS-2, RhTPS-1,2 &3, SSTPS- 1, Western Region = KSTPS-1 &3, MSTPS- 1&2,": "Solar Projects",
    "Solar Projects located in Rajasthan , Punjab, Uttar Pradesh, Karnataka , Orissa, Andhra Pradesh, Tamil Nadu, Maharash tra & Northern Region = FGUTPS- 1,2 3&4, NCTPS-2, RhTPS- 1,2 &3, SSTPS-1 & Tanda_2, Western Region = KSTPS-1 &3, MSTPS- 1&2, SPTPS- 1&2, SLTPS-": "Solar Projects",
    "HIMACHAL PRADESH H": "Himachal Pradesh",
    "KWHEP": "KWHEP",
    "PUNJAB": "Punjab",
    "ODISHA": "Odisha",
    "KERALA": "Kerala",
    "ER": "ER",
    "PSPCL": "PSPCL",
    "OSIDHA": "Odisha",
    "DAMAN &D": "Dadra and Nagar Haveli and Daman and Diu",
    "Solar Projects located in Rajasthan, Punjab, Uttar Pradesh, Karnataka , Orissa, Andhra Pradesh, Tamil Nadu, Maharasht ra & Northern Region = FGUTPS- 1,2 3&4, NCTPS-2, RhTPS- 1,2 &3, SSTPS-1 & Tanda_2, Western Region = KSTPS-1 &3, MSTPS- 1&2, SPTPS- 1&2, SLTPS- 1,KGNST": "Solar Projects",
    "KERELA": "Kerala",
    "ARYANA": "Haryana",
    "ORISSA": "Odisha",
    "PUNJA3": "Punjab",
    "JHSLDC": "Jharkhand",
    "DLSLDC": "DLSLDC",
    "KPTCL": "KPTCL",
    "JITPL": "JITPL",
    "Solar Projects located in Rajasthan, Punjab, Uttar Pradesh, Karnataka, Orissa, Andhra Pradesh, Tamil Nadu, Maharashtra & Northern Region = FGUTPS-1,2 3&4, NCTPS-2, RhTPS-1,2 &3, SSTPS-1 & Tanda_2, Western Region = KSTPS-1 &3, MSTPS-1&2, SPTPS-1&2, SLTPS- 1,KGNST_1, GSTPS-": "Solar Projects",
    "Solar Projects located in Rajasthan, Punjab, Uttar Pradesh, Karnataka, Orissa, Andhra Pradesh, Tamil Nadu, Maharashtra & Northern Region = FGUTPS-1,2 3&4, NCTPS- 2, RhTPS-1,2 &3, SSTPS-1 & Tanda_2, Western Region = KSTPS-1 &3, MSTPS-1&2, SPTPS-1&2, SLTPS- 1,KGNST_1, GSTPS-": "Solar Projects",
    "TRIPURA": "Tripura",
    "HARYANA": "Haryana",
    "SIKKIM": "Sikkim",
    "MEGHALAYA": "Meghalaya",
    "MAHARAS": "Maharashtra",
    "MIZORAM": "Mizoram",
    "Solar Projects located in Rajasthan, Punjab, Uttar Pradesh, Karnataka , Orissa, Andhra Pradesh, Tamil Nadu, Maharasht ra & Northern Region = FGUTPS- 1,2 3&4, NCTPS-2, RhTPS- 1,2 &3, SSTPS-1, Western Region = KSTPS-1 &3, MSTPS- 1&2, SPTPS- 1&2, SLTPS- 1,VSTPS-": "Solar Projects",
"Solar Projects located in Rajasthan, Punjab, Uttar Pradesh, Karnataka, Orissa, Andhra Pradesh, Tamil Nadu, Maharasht ra & Northern Region = FGUTPS- 1,2 3&4, NCTPS-2, RhTPS- 1,2 &3, SSTPS-1, Western Region = KSTPS-1 &3, MSTPS- 1&2, SPTPS- 1&2, SLTPS- 1,VSTPS-": "Solar Projects",
    "Solar Projects located in Rajasthan, Punjab, Uttar Pradesh, Karnataka, Orissa, Andhra Pradesh, Tamil Nadu, Maharasht ra & Northern Region = FGUTPS- 1,2 3&4, NCTPS-2, RhTPS- 1,2 &3, SSTPS-1, Western Region = KSTPS-1 &3, MSTPS- 1&2, SPTPS- 1&2, SLTPS- 1,VSTPS- 1,2,3 4 &5": "Solar Projects",
    "Solar Projects located in Rajasthan, Punjab, Uttar Pradesh, Karnataka, Orissa, Andhra Pradesh, Tamil Nadu, Maharasht ra & Northern Region = FGUTPS- 1,2 3&4, NCTPS-2, RhTPS- 1,2 &3, SSTPS-1, Western Region = KSTPS-1 &3, MSTPS- 1&2, SPTPS- 1&2, SLTPS- 1,GSTPS- 1,VSTPS-": "Solar Projects",
    "DISTRIBUTION CORPORATI": "Distribution Corporation",
    "JHARKHAND D": "Jharkhand",
    "JAMMU AND_x000D_KASHMIR": "Jammu and Kashmir",
    "JAMMU &_x000D_KASHMIR": "Jammu and Kashmir",
    "BANGLA DESH": "Bangladesh",
    "JHARKHAND": "Jharkhand",
    "MAHAR ASHTRA": "Maharashtra",
    "BANGLADESH": "Bangladesh",
    "MAHARASH": "Maharashtra",
    "WEST_x000D_BENGAL": "West Bengal",
    "UTTAR PRADESH": "Uttar Pradesh",
    "ANDHRAPRADESH": "Andhra Pradesh",
    "DAMODAR VALLY CORPORATION": "Damodar Vally Corporation",
    "DAMODAR VALLY": "Damodar Vally Corporation",
    "KARNATAKA": "Karnataka",
    "ANDHRA PRADESH": "Andhra Pradesh",
    "CHATTISGARH": "Chattisgarh",
    "MADHYA PRADESH": "Madhya Pradesh",
    "CHATTISHGAR": "Chattisgarh",
    "CHHATTISGAR": "Chattisgarh",
    "KARANATAK": "Karnataka",
    "Solar Projects located in Rajasthan, Punjab, Uttar Pradesh, Karnataka, Orissa, Andhra Pradesh, Tamil Nadu, Maharashtra & Northern Region = FGUTPS-1,2 3&4, NCTPS-2, RhTPS-1,2 &3, SSTPS-1 & Tanda_2, Western Region = KSTPS-1 &3, MSTPS-1&2, SPTPS-1&2, SLTPS- 1,KGNST_1, GSTPS- 1,LSTPS_1,VS TPS-1,2,3 4 &5 Southern Region = RSTPS-1&3, TSTPS-2, SMPTS- 2,KUDGI-1, Eastern Region": "Solar Projects",
    "CHHATTISGARH": "Chattisgarh",
    "Solar Projects located in Rajasthan, Punjab, Uttar Pradesh, Karnataka, Orissa, Andhra Pradesh, Tamil Nadu, Maharashtra & Northern Region = FGUTPS-1,2 3&4, NCTPS- 2, RhTPS-1,2 &3, SSTPS-1 & Tanda_2, Western Region = KSTPS-1 &3, MSTPS-1&2, SPTPS-1&2, SLTPS- 1,KGNST_1, GSTPS- 1,LSTPS_1,V STPS-1,2,3 4 &5  Southern Region = RSTPS-1&3, TSTPS-2, SMPTS- 2,KUDGI-1, Eastern Region =FSTPS-1&3, KhTPS-1&2, TSTPS-1": "Solar Projects",
    "Solar Projects located in Rajasthan, Punjab, Uttar Pradesh, Karnataka, Orissa, Andhra Pradesh, Tamil Nadu, Maharashtra & Northern Region = FGUTPS-1,2 3&4, NCTPS-2, RhTPS-1,2 &3, SSTPS-1 & Tanda_2, Western Region = KSTPS-1 &3, MSTPS-1&2, SPTPS-1&2, SLTPS- 1,KGNST_1, GSTPS- 1,LSTPS_1,VST PS-1,2,3 4 &5 Southern Region = RSTPS-1&3, TSTPS-2, SMPTS- 2,KUDGI-1, Eastern Region =FSTPS-1&3, KhTPS-1&2, TSTPS-1": "Solar Projects",
    "Solar Projects located in Rajasthan, Punjab, Uttar Pradesh, Karnataka, Orissa, Andhra Pradesh, Tamil Nadu, Maharashtra & Northern Region = FGUTPS- 1,2 3&4, NCTPS-2, RhTPS- 1,2 &3, SSTPS-1 & Tanda_2, Western Region = KSTPS-1 &3, MSTPS-1&2, SPTPS-1&2, SLTPS-1,KGNST_1, GSTPS- 1,LSTPS_1,VSTPS-1,2,3 4 &5 Southern Region = RSTPS- 1&3, TSTPS-2, SMPTS- 2,KUDGI-1, Eastern Region =FSTPS-1&3, KhTPS-1&2, TSTPS-1": "Solar Projects",
    "MAHARSHTRA": "Maharashtra",
    "HIMACHAL PRADESH": "Himachal Pradesh",
    "MAHARASHTR": "Maharashtra",
    "CHATTISHGARH": "Chattisgarh",
    "MAHSRSHTRA": "Maharashtra",
    "Solar Projects located in Rajasthan, Punjab, Uttar Pradesh, Karnataka, Orissa, Andhra Pradesh, Tamil Nadu, Maharashtra & Northern Region = FGUTPS- 1,2 3&4, NCTPS-2, RhTPS- 1,2 &3, SSTPS-1 & Tanda_2, Western Region = KSTPS-1 &3, MSTPS-1&2, SPTPS- 1&2, SLTPS-1,KGNST_1, GSTPS-1,LSTPS_1,VSTPS- 1,2,3 4 &5 Southern Region = RSTPS-1&3, TSTPS-2, SMPTS-2,KUDGI-1, Eastern Region =FSTPS-1&3, KhTPS-1&2, TSTPS-1": "Solar Projects",
    "Solar Projects located in Rajasthan, Punjab, Uttar Pradesh, Karnataka, Orissa, Andhra Pradesh, Tamil Nadu, Maharashtra & Northern Region = FGUTPS-1,2 3&4, NCTPS-2, RhTPS-1,2 &3, SSTPS-1 & Tanda_2, Western Region = KSTPS-1 &3, MSTPS-1&2, SPTPS- 1&2, SLTPS- 1,KGNST_1, GSTPS- 1,LSTPS-1,VSTPS- 1,2,3 4 &5 Southern Region = RSTPS-1&3, TSTPS-2, SMPTS- 2,KUDGI-1, Eastern Region =FSTPS-1&3, KhTPS-1&2, TSTPS-1": "Solar Projects",
    "MAHARASHTRA": "Maharashtra",
    "MAHARAS HTRA": "Maharashtra",
    "UTTAR_x000D_PRADESH": "Uttar Pradesh",
    "HIMACHAL_x000D_PRADESH": "Himachal Pradesh",
    "CHATTISGARH CHATTISGARH CHATTISGARH CHATTISGARH CHATTISGARH CHATTISGARH": "Chattisgarh"
}